### ISSUE TITLE
Timeline bei WebMs

### ISSUE THREAD

**Issue by aPollO2k** [mopsalarm/Pr0#102]
Eine timeline bei webms mit der Möglichkeit die Clips vorzuspulen wäre ziemlich nice

**Comment by mopsalarm** [comment]
Hmm, leider ist das eher problematisch. Ich hab bei meinem letzen Versuch sehr komische Zeitangaben bekommen. Für GIF und WEBM sollte es aber eigentlich kein Problem sein.
Vorspulen werde ich wahrscheinlich aber erstmal nicht integrieren. Ich lasse es aber mal offen
