### ISSUE TITLE
Aufhängen beim Vorladen

### ISSUE THREAD

**Issue by marsteff** [mopsalarm/Pr0#104]
Hey,

das Vorladen Future hat sich wohl bei mir aufgehangen. Steht seit Stunden in der Statusleiste und lässt sich nicht entfernen. Vllt sollte man eine Funktion einbauen, um es manuell abbrechen zu können.

**Comment by mopsalarm** [comment]
Einfach drauf drücken sollte das abbrechen. 
Wenn es ewig bleibt, dann ist wohl die App im Hintergrund beendet worden. Muss mal gucken was man da machen kann. Wo du das jetzt sagst: nen wakelock brauchen wir da noch...

**Comment by marsteff** [comment]
Rauf drücken bewirkt lediglich, dass die Leiste geschlossen wird. Das Item bleibt jedoch erhalten. Die App lässt sich auch weiterhin benutzen.

**Comment by mopsalarm** [comment]
Wakelock beim Vorladen ist eingebaut. De hält zur Sicherheit maximal 10 Minuten. We'll see was das bingt! :)
