### ISSUE TITLE
Aufhängen des gesamten Handys samt Neustart 

### ISSUE THREAD

**Issue by marsteff** [mopsalarm/Pr0#105]
Hallo,

Hatte es jetzt 2 mal in Folge, dass mein Handy sich komplett aufgehangen hat, ich nichts mehr machen konnte und es dann selbstständig einen Neustart durchgeführt hat (Mit Optimierung der apps, was natürlich länger dauert). Ich kann den Fehler auch schwer eingrenzen, da ich lediglich in der Top Ansicht war. Kannst ja mal nachsehen ob er noch geschafft hat, einen Bugreport zu erstellen. War mit einem Xperia Z2 Android 5.1.1. Zur zeitlichen Abgrenzung, gestern Abend und heute früh sind die Abstürze passiert. Ich hätte ja eigentlich gedacht,  dass das BS solch einen komplette Absturz verhindern sollte.

**Comment by mopsalarm** [comment]
Ich habe nichts dergleichen in meinen Crashlytics Logs und kann mir auch nichts im der App vorstellen, dass zu so einem Problem führt.
Ich tippe eher drauf, dass der Grund wo anderes liegt und entweder zufällig aufgetreten ist oder die App das irgendwie ausgelöst hat (zb nen Bug in einem Exposed Modul getriggert hat oder ähnliches). 
So oder so, wenn es nicht reproduzierbar ist, kann ich nicht machen.

**Comment by GottZ** [comment]
@marsteff stell mal den video decoder auf software um. vielleicht hilft das. es gibt immer wieder fälle von snapdragon cpu's bei denen bei zu langer nutzung des video decoders einfach irgendwann tschüs sagt.
