### ISSUE TITLE
Pausieren von gifs/webms

### ISSUE THREAD

**Issue by dirtyd1994** [mopsalarm/Pr0#106]
hey,
Wie ich bereits auf pr0 erwähnt, hatte ich vor deiner App eine andere Pr0 App bei der es möglich war gifs und webms mit einem tap zu pausieren... wäre eine Verbesserung über das du dir gedanken machen könntest es einzubauen.

mfg dirty

**Comment by mopsalarm** [comment]
Hm, geht auf der Website auch nicht direkt. Werde ich wohl rauslassen.
