### ISSUE TITLE
Systemcrash Android 5.1.1 - Cyanogen oneplus

### ISSUE THREAD

**Issue by davel88** [mopsalarm/Pr0#107]
Seit dem letzten Android Update treten bei mir schwerwiegende Fehler auf. Ich nehme an, dass es in Verbindung mit der Pr0gramm App steht. 

Folgende Probleme sind aufgetreten:
- Chrome stürzt sofort beim öffnen ab
- Youtube Videos können nicht abegspielt werden (unendliche Ladezeiten)
- Spontane Neustarts des Handys
- Pr0gramm App lädt Bilder sehr langsam und Videos führen zum Absturz der App

Aufgrund dieser Probleme habe ich das Handy formatiert, und es hat alles wieder funktioniert. Nach ein paar Tagen (intensiver) Nutzung der App trat das Problem wieder auf. Der Cache der Pr0gramm App konnte nicht gelöscht werden, und beim Deinstallieren ist das Gerät wieder abgestürzt. Nach erfolgreicher Deinstallation läuft mein Gerät wieder richtig. Schade.

**Comment by mopsalarm** [comment]
Die App macht nichts besonderes. Ich habe die App auch auf nem cm Handy entwickelt. Probiere mal den Software Dekoder zu aktivieren. Cache löschen funktioniert 1a. Das ganze liegt eher an deinem Cyanogenmod, dem Netzwerk oder irgendwas anderes
