### ISSUE TITLE
App wird beendet nach resume aus history, drücken auf "<-"

### ISSUE THREAD

**Issue by poyopaya** [mopsalarm/Pr0#108]
Wenn man die App resumed und anschließend auf zurück (<-) drückt wird diese beendet.

Edit: Hat eventuell etwas hiermit zu tuen: https://github.com/mopsalarm/Pr0/issues/98

**Comment by mopsalarm** [comment]
Fixed.

**Comment by poyopaya** [comment]
Hab ich bemerkt.
Vielen Dank!
