### ISSUE TITLE
Pin / NSFW / NSFL Sperre

### ISSUE THREAD

**Issue by bratkartoffel** [mopsalarm/Pr0#109]
Hoi,

da mein Neffe (8) mit meinem Handy gerne mal rumspielt und ich mich nicht jedes mal davor bei pr0 abmelden will würde ich mich sehr über eine Art Pin-Schutz / NSFW / NSFL Sperre freuen. Würde ihn nur ungern bei der Suche nach einem neuen Spiel über g0re oder ähnliches stolpern lassen...

Könnte man in den Einstellungen die Filter-Settings nicht mit einer Art einfacher PIN absichern? 
Alternativ könnte man den Start der App auch komplett (ähnlich owncloud) mit einer PIN absichern.

Grüsse,
Ein Kellerkind

**Comment by mopsalarm** [comment]
Hm, findet sich jemand, der das einbaut?
