### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#11]
Da nicht alle auf Pr0 des Englischen mächtig sind, wäre eine Übersetzung der App ins Deutsche gut. Dafur müss (glaube ich) nur eine values-de/strings.xml angelegt werden.

**Comment by kratostav** [comment]
mach ich

**Comment by kratostav** [comment]
Fertig bitte jemanden nachzukontrollieren

**Comment by mopsalarm** [comment]
Da sind noch einige Fehler drin. Teilweise sogar vom Sinn. (um 90%, nicht auf)... Wenn du kannst, ließ es nochmal Kontrolle. Bin gerade nur auf dem Handy unterwegs, darum kann ich leider gerade nicht viel genauer ausführen.

**Comment by kratostav** [comment]
Ok danke mach das morgen nochmal
Am 05.03.2015 22:37 schrieb "mopsalarm" <notifications@github.com>:

**Comment by mopsalarm** [comment]
Habe noch ein paar Fehler markiert. Siehe ![screenshot](https://cloud.githubusercontent.com/assets/11006365/6537527/e73f0630-c457-11e4-8d86-005ebabe9de7.png)

Bugreport würde ich zusammenschreiben, und eher: "Es ist ein Fehler beim Dekodieren der Antwort der API aufgetreten". Bei den gifs ist vielleicht schöner: "GIFs im Speicher dekodieren" und "GIFs in eine temporäre Datei speichern" und "Lädt GIFs in den Speicher".

Kannst du noch weitere Sprachen oder kennst du noch leute, die weitere Sprachen kennen? Dann könntest du da vielleicht noch weitere Übersetzungen nachpflegen.
