### ISSUE TITLE
Crash bei Tippen auf selektierten Text

### ISSUE THREAD

**Issue by schr3j** [mopsalarm/Pr0#110]
Wenn man in den Kommentaren Text auswählt und diesen anschließend antippt crasht die App. Gerade keinen Debugger zur Hand, ist aber ja leicht reproduzierbar. Nexus 5/Android 6.

**Comment by mopsalarm** [comment]
Probiere mal in anderen Apps. Im Emulator stürzt das z.B. auch bei der Suchapp ab. Liegt also eher an Android 6.

**Comment by schr3j** [comment]
Also in der Google App (der neusten) und Inbox stürzt es nicht ab. Wenn ich nachher mal Zeit hab häng ich mal den Debugger dran...

**Comment by mopsalarm** [comment]
Das ist sehr wahrscheinlich der hier: http://i.imgur.com/H8RugaR.png
Aber wie gesagt, das scheint nicht aus der App heraus zu kommen.
