### ISSUE TITLE
Text in Bildern unlesbar

### ISSUE THREAD

**Issue by DaPutzy** [mopsalarm/Pr0#116]
Ich habe es häufig das Posts die viel Text beinhalten in der App nicht lesbar sind.

Aktuelles Beispiel: http://pr0gramm.com/top/1073679

*In der App:*

![pr0 app](http://i.imgur.com/RZNZE3X.png)

*Desktop:*

![pr0 aufm rechner](http://i.imgur.com/dF4HMvD.png)

Es gibt auch aber Fälle wo es einwandfrei funktioniert, z.Bsp. die [Knastgeschichten](http://pr0gramm.com/top/pr0Knast)...

Vllt lässt sich da etwas dran drehen? :)

**Comment by schr3j** [comment]
Soweit ich weiß müsste das auf die Komprimierung von Bildern (hauptsächlich "musste scrollen") bei mobiler Nutzung zum Datensparen zurückzuführen sein. Wenn Du in den Vollbildmodus wechselst, sollte das Bild in voller Auflösung geladen werden und man kann die Schrift lesen ;)
Ob das allerdings bei WLAN auch so ist weiß ich nicht.

**Comment by DaPutzy** [comment]
Unter Umständen Dasselbe Problem wie bei https://github.com/mopsalarm/Pr0/issues/47?

Im Vollbild ist es lesbar, danke!

**Comment by schr3j** [comment]
Auch da bin ich mir nicht sicher, ich glaube aber dann werden Bilder mit "musste scrollen" immer in der maximalen Auflösung geladen. Das kann aber @mopsalarm besser beantworten, ich hab jetzt keine lust das im Code zu suchen :stuck_out_tongue_winking_eye:

**Comment by mopsalarm** [comment]
Das hat nichts mit Datensparen zu tun. Das Bild wird einfach mit einer bestimmten Maximalgröße (ich glaube 4096px) geladen. Die Größe ist unabhängig von der maximalen Texturgröße der Hardware.  Wenn man in den Vollbild wechselt, wird die maximale Texturgröße gewählt. Das kann dann 8000px sein. Ich dachte, 4k reicht für fast alle Post. Das Problem ist sonst nämlich, dass das Bild gar nicht angezeigt wird, wenn entweder die Textur zu groß ist oder das h komprimierte Bild nicht in den Speicher passt. Mal gucken, vllt kann ich da demnächst nochmal was machen.

**Comment by yenon** [comment]
@mopsalarm Hab mit dieser Library sehr gute Erfahrungen gemacht: https://github.com/davemorrissey/subsampling-scale-image-view
Wie der Name schon sagt, werden Bildbereiche dynamisch geladen und wieder entladen. Damit wurden schon Bilder von ~20000x20000 Pixeln sicher geladen. (Ein bisschen warten muss man dann aber schon)
Falls es geht, machst du einen lurker glücklich.

**Comment by mopsalarm** [comment]
Auf die hin ich letztens auch gestoßen. Ist in der aktuellen Beta bereits drin.

**Comment by DaPutzy** [comment]
Super Arbeit! :+1:
