### ISSUE TITLE
 Speichere Meldungen

### ISSUE THREAD

**Issue by DominikTV** [mopsalarm/Pr0#118]
Ich fänds praktisch, wenn die Meldungen (siehe Bild), sollte man sie mit OK bestätigen, nach einem Update nicht immer wieder zurückgesetzt werden und man sie erneut bestätigen muss.

Bild: http://i.imgur.com/lgwaB0A.jpg

Ist nur ne kleinere Sache, dennoch wollte ich das Feedback da lassen. Klasse Arbeit, mach weiter so :)

**Comment by mopsalarm** [comment]
Leider werden die Meldungen jetzt schon von zu vielen ignoriert. Ich habe manchmal das Gefühl, dass ich die Nachricht vor jedem Video anzeigen müsste.
