### ISSUE TITLE
zugriff auf pr0.wibbly-wobbly.de

### ISSUE THREAD

**Issue by f0o** [mopsalarm/Pr0#120]
Im rahmen der Transparenz, was genau ist hinter dieser domain?

**Comment by mopsalarm** [comment]
Zusatzservices für die App. Suche im Code mal danach. Gif2webm, extra Kategorien, meta Informationen zu posts, api proxy, feedback, Vorschaubildchen, etc.

**Comment by f0o** [comment]
:+1: für die info!
gibt es eine möglichkeit dies auf die pr0-server zu schieben wenn die app mehr momentum bekommt?
Ich denke so ein droplet von digitalocean wird nicht das wahre sein für dauerhaftes benutzen.

**Comment by mopsalarm** [comment]
Warum, wo ist das Problem mit nem Droplet?
