### ISSUE TITLE
rep0st integration

### ISSUE THREAD

**Issue by PDDStudio** [mopsalarm/Pr0#124]
Eine Integration von [rep0st](http://rep0st.rene8888.at/) in die pr0 App wäre hilfreich und würde das hin- und her wechseln von der App und dem Browser vermeiden. Würde auch ggf den Leuten welche die Seite nicht kennen eine Hilfe geben zum schauen ob ein potenzieller rep0st besteht oder nicht. 
Das ganze ist mehr ein enhancement/feature request als ein bug report

**Comment by mopsalarm** [comment]
Da habe ich mich damals gegen entschieden, da das Bild dann sowohl an rep0st als auch an pr0gramm versendet werden muss. Das ist gerade auf Mobile doof.
Worüber man reden kann, ist die pr0gramm eigene rep0st Erkennung zu verwenden.

**Comment by PDDStudio** [comment]
Okay zwei mal das Bild hochladen ist unnötig da gebe ich dir recht. Aber auch die pr0gramm eigene Schnittstelle wäre natürlich eine Möglichkeit um die reposts zu verringern. Unterstützt diese auch gif/webm?

**Comment by schr3j** [comment]
Wäre doch schick zumindest einen Button einzubauen der eine optionale rep0st Prüfung ermöglicht. Kann man ja dann dazu schreiben dass das ganze doppelt hochgeladen werden muss ;)

**Comment by mopsalarm** [comment]
Normale pr0gramm Repost Erkennung ist jetzt eingebaut.

**Comment by mYnDstrEAm** [comment]
Wieso wurde das Issue geschlossen?

Einen zusätzlichen Button auf den 3 Punkten rechts oben für die Repost-Erkennung wäre echt cool und einfach zu implementieren: er muss nur auf http://rep0st.rene8888.at/checkurl/_UrlDesBildes_ verlinken.

**Comment by mopsalarm** [comment]
Und was soll "url des Bildes" sein, wenn man ein Bild selbst hochladen möchte?

**Comment by mYnDstrEAm** [comment]
@mopsalarm Stimmt, das wäre dann noch eine _zusätzliche_ rep0st-Erkennung. Ich habe mich hier bloß auf die Reporterkennung bereits geposteter Bilder bezogen. Dafür müsste man das Bild beim Upload irgendwie auch auf rep0st.rene8888 hochladen. Allerdins habe ich keine Ahnung wie bzw. ob das derzeit schon möglich ist - wenn nicht müsste man hier ein neues Issue erstellen: https://github.com/ReneHollander/rep0st

Aber wie gesagt, der erste Teil sollte recht einfach zu implementieren sein...

**Comment by mopsalarm** [comment]
Welcher erste Teil? Einen Link zu prüfen? Das baue ich nicht ein, dafür kannst du auf die Website gehen.
Upload zu rep0st würde bedeuten, dass das Bild zweimal hochgeladen werden muss, was insbesondere im mobilen Netz schlecht ist.
ReneHollander hat meinen initialen Algorithmus in rep0st rausgenommen und benutzt nun (unter anderem) phash, was pr0gramm selbst auch schon macht. Sehe also den mehrgewinn nicht.
