### ISSUE TITLE
App haengt beim abspielen von Videos

### ISSUE THREAD

**Issue by aktentasche** [mopsalarm/Pr0#125]
Version: 1.88 (beta channel)

Schritte zum reproduzieren: 
1. Starte app
2. Durch "Top" Bilder swipen 
3. Bei Videos (webm vermute ich mal) haengt sich die App auf
4. Nach einiger Zeit erscheint der uebliche "Force quit" etc.. Dialog

100% reproduzieren laesst sich der Fehler nicht, er tritt sporadisch auf. Erwaehnenswert ist, dass mein Telefon eine x86 Architektur hat (Asus Zenfone 2 mit stock ROM aber XPrivacy)

catlog screenshots: http://www.abload.de/gallery.php?key=o7tq95ta

Ich werde mal nicht den cache leeren um den Fehler reproduzieren zu koennen.

**Comment by mopsalarm** [comment]
Hast du Softwaredekoder aktiv? Mache bitte ein logcat ohne es zu filtern, so fehlt die Hälfte. Speichere es dann in eine Datei

**Comment by aktentasche** [comment]
Softwaredekoder: unsicher, siehe hier: http://abload.de/img/screenshot_2016-02-159gl4h.jpg

logcat: werde ich machen beim naechsten crash

**Comment by mopsalarm** [comment]
Wenn das häckchen da ist, dann ist der an.

**Comment by aktentasche** [comment]
Ok. Ist mMn etwas unklar, da man denken koennte, dass die oberste CheckBox alles deaktiviert. (Auch wenn der text was anderes sagt)

**Comment by aktentasche** [comment]
[logcat.txt](https://github.com/mopsalarm/Pr0/files/132045/logcat.txt)

Habe nun den Softwaredecoder deaktiviert.

**Comment by mopsalarm** [comment]
Ich sehe

1. dass die App irgendwo hängengeblieben ist, bzw blockiert. Leider habe ich keine Ahnung wo. 
2. dass der Softwaredekoder sehr wohl noch aktiv ist.

**Comment by aktentasche** [comment]
Das "nun" impliziert, dass der Softwaredekoder erst nach dem log deaktiviert wurde.

Ich schliesse das Ticket, da der Fehler mit dem Hardwaredekoder wohl nicht mehr auftritt.

**Comment by mopsalarm** [comment]
Achso das hab ich nicht verstanden. Trotzdem witzig, sonst ist das genau andersherum: es bleibt mit dem Hardwarecodec hängen und Softwaredekoder nicht
