### ISSUE TITLE
iOS Version?

### ISSUE THREAD

**Issue by deada92** [mopsalarm/Pr0#126]
Hallo zusammen,

obwohl die Android version super toll ist wollte ich ftragen, ob Ihr mir erlauben würdet für iOS eine zu erstellen?

#plsNoBann

**Comment by mopsalarm** [comment]
Mach. Viel Erfolg.

**Comment by deada92** [comment]
Habt ihr evtl. eine API gebaut für die Android version die ich wieder benutzen kann?

**Comment by mopsalarm** [comment]
Guck in den Code rein, da gibt's ein api Interface und Objekte die auf json gemappt werden. Aber die kannst du nicht direkt verwenden, da das alles Java ist.

**Comment by deada92** [comment]
Alles klar ich versuch mal ein wrapper zu bauen..
