### ISSUE TITLE
[Request] Kommentar-url kopieren

### ISSUE THREAD

**Issue by poyopaya** [mopsalarm/Pr0#127]
durch klicken / halten auf kommentar zeit url des kommtars in zwischenablage kopieren, um diesen referenzieren zu können.

**Comment by mopsalarm** [comment]
Siehe #128 - mir fehlt da noch ein Layout wie man diese ganzen Extraoperationen unterbringen kann.

**Comment by mopsalarm** [comment]
In der nächsten Version drin.
