### ISSUE TITLE
Touch Target für Kommentare einklappen zu klein

### ISSUE THREAD

**Issue by schr3j** [mopsalarm/Pr0#128]
Das Touch Target zum einklappen von Kommentaren ist aktuell nur der Text des Kommentars (wie es scheint).
Das ist etwas unpraktisch zu treffen wenn sich das Kommentar z.B. am unteren Rand befindet und aus nur einer Zeile besteht.
Besser wäre es vielleicht den gesamten Kommentar als Target zu verwenden.

**Comment by mopsalarm** [comment]
Ich hätte eigentlich lieber auch noch was besseres als draufklicken. Das k-fav Herz an der Seite gefällt mir auch nicht so gut da. Aber gleichzeitig sollen die Aktionen auch irgendwie immer präsent sein. Ideen?

**Comment by poyopaya** [comment]
wie wärs mit nem floating button? siehe deviantart app - bei halten des fb ploppen andere funktionen auf.

https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions
https://www.youtube.com/watch?v=skSApXvi4xM

**Comment by poyopaya** [comment]
ansonsten kommentar halten lässt kontextmenü aufp0loppen und man kann zwischen "text auswählen", "kommentar verlinken", "kommentar bearbeiten [mod]", usw auswählen

**Comment by mopsalarm** [comment]
fab: ist quatsch, es werden ja mehrere Kommentare gleichzeitig angezeigt. 
Lange drücken: würde ich gerne vermeiden, da das für einen neuen Benutzer hier nicht erkennbar ist, dass er durch längeres drücken Aktionen ausführen kann.

**Comment by schr3j** [comment]
Ich würde die verschiedenen Aktionen vielleicht in die 3. Zeile, also hinter Antworten setzen.
Die Zeile würde dann vielleicht so aussehen:
> x Punkte  vor x Minuten  Antworten  ❤︎  ▼  ⠇
Für das ▼ zum auf und zu klappen vielleicht ein besseres Symbol.
Das ⠇wäre halt ein overflow menu aus Android für zusätzlichen kram wie Kommentar-url kopieren (#127) und andere geschichten...
Dazu müsste die Zeile allerdings etwas größer werden und verbraucht dann logischerweise auch mehr Platz...

**Comment by poyopaya** [comment]
die idee ist auch nicht schlecht, allerding leidet da die wurstfingerfraktion drunter.
das mit dem kommentar halten kann man mit einem guide erklären (wie bei android erstes mal starten; blauer fokus auf icon im launcher). beispiel: http://i.stack.imgur.com/cE3EU.png

**Comment by mopsalarm** [comment]
Ich bin kein Fan von guides, die siehst du einmal, und dann hat die Hälfte der Benutzer die Funktion vergessen. Sowas muss "mitten in die fresse rein", um hier mal die *beste Band der Welt* zu zitieren. Ich finde die Idee von @schr3j gar nicht schlecht. Allerdings dann vllt mit größeren Symbolen, damit die Wurstfingerfraktion nicht zu sehr leidet. Auf kleinen Geräten ist diese Anzeige bereits zweizeilig, wenn ich mich recht erinnere. 
Lust jemand ein Grafikprogramm zu bemühen? Ansonsten experimentiere ich morgen oder am Wochenende mal, je nachdem wann ich Zeit finde.

**Comment by poyopaya** [comment]
jop. 
gut dann versuch ich mal mein glück und bemühe meine paintskills.

**Comment by poyopaya** [comment]
![bild_newfunctions](https://cloud.githubusercontent.com/assets/6437182/13934656/8a840ae8-efb3-11e5-9556-59bdd2ce04f2.png)
so in der art oder sollen die funtionen anders angeordnet werden?

**Comment by mopsalarm** [comment]
Ich würde dann wohl sogar den Antworten Text durch einen antworten Pfeil ersetzen und nen expand Pfeil aus den Material icons von Google dazu packen. Dann braucht man aktuell auch die drei Punkte gar nicht. Und dann vllt einfach vertikal zentriert mit dem Namen und der Punkte/Datumsanzeige?

**Comment by poyopaya** [comment]
V2:
![bild_newfunctions2](https://cloud.githubusercontent.com/assets/6437182/13935634/93bde390-efb8-11e5-9512-b867247694ae.png)

**Comment by mopsalarm** [comment]
Okay, ich habs zuerst so umgesetzt: ![20160322-144752](https://cloud.githubusercontent.com/assets/11006365/13954152/ddc8266c-f03f-11e5-9d3e-a98e4a4aa0a4.png)

Aber habe mich dann für ein Menu mit den nicht so wichtigen Funktionen entschiedenen: ![20160322-150532](https://cloud.githubusercontent.com/assets/11006365/13954151/ddc7596c-f03f-11e5-95f6-6776f5790656.png)

Was meint ihr?

**Comment by mopsalarm** [comment]
![20160322-152843](https://cloud.githubusercontent.com/assets/11006365/13954849/ccf341a2-f042-11e5-9c4a-6a64c494c6b4.png)
So siehts nun aus.

**Comment by poyopaya** [comment]
Was hats mit dem +13 badge auf sich?

**Comment by mopsalarm** [comment]
13 zusammengeklappte Kindkommentare

**Comment by poyopaya** [comment]
Merkst du?
Darauf wäre ich nicht gekommen.

Versuch mal diesen aufklapp-/ zuklappbutton mit der Zahl zu kombinieren, dann ist das optisch noch etwas besser und ist besonders für kleinere Display kompakter

**Comment by mopsalarm** [comment]
Ich überlege aber gerade die Aktionen vor die User/Datum Infos zu schieben.

**Comment by mopsalarm** [comment]
Es gibt aber keinen Aufklappbutton mehr. Der ist in das drei Punkte Menü gewandert. Die Badge taucht nach dem zuklappen auf. Kannst es mal in der aktuellen Beta ausprobieren. 
Daran das zu kombinieren habe ich auch gedacht, als es noch ein extra Button war.

**Comment by poyopaya** [comment]
Welches Layout ist dafür verantwortlich?
Dann pack ich das mal in den Android Studio Designer und gucks mir auch mal an.

Kann man dich eventuell auch im IRC erreichen?
Dann brauchen wir das hier weniger und dokumentieren die Fortschritte hier.

**Comment by poyopaya** [comment]
Hab die Beta drauf.
Läuft soweit ganz rund.
Allerdings bleiben Kommentare beim rotieren nicht zugeklappt

**Comment by mopsalarm** [comment]
Ja mir state ist noch nichts. Müsste den state des CommentAdapter monsters speichern. Das muss eh aufgeräumt werden. 
comment_layout oder layout_comment oder so ist dafür verantwortlich. Siehst du da auch in der klasse in onCreateViewHolder oder so. 
Ich bin gleich Zuhause, kann in den #pr0gramm channel kommen

**Comment by mopsalarm** [comment]
Oder gibt's nicht inzwischen so einem git Chat? Gitter oder so?

**Comment by mopsalarm** [comment]
Okay Kinders, kann ich es so raushauen, wie es in der aktuellen Beta ist?  Irgendwelche größeren Probleme damit?

**Comment by poyopaya** [comment]
Soweit ich es auf meinem S3 testen konnte, hat es funktioniert. Eventuell
noch leichtes Feintuning, damit es auf allen Größen passend groß angezeigt
wird. Aber von mir schonmal ein ok!

**Comment by mopsalarm** [comment]
Die Größe sollte durch die Verwendung von dp eigentlich überall (in mm) ungefähr gleich groß sein.

**Comment by schr3j** [comment]
Also mir gefällt das so ziemlich gut ;)

**Comment by mopsalarm** [comment]
Ich denke ich bau es wieder aus. Im Schnitt klappen am Tag 20 User Kommentare zu...

**Comment by schr3j** [comment]
Ja, das Feature find ich persönlich auch nicht besonders nützlich. Es ist viel zu umständlich (zumindest so wie es aktuell verfügbar ist) Kommentare einzuklappen um es vernünftig zu nutzen. Wäre es ein Icon würden es vielleicht mehr Leute verwenden.
Immerhin ist es eher ein Feature welches mehrmals nacheinander aufgerufen wird. Den Kommentarlink kann man gerne über ein Overflow Menü erreichen. Ich fände sogar die Antworten Funktion in einem Overflow Menü annehmbar da ich denke dass das Zusammenklappen meiner Meinung nach wohl, wenn überhaupt, häufiger verwendet würde als Antworten.
Als Symbol, falls du es testen willst, würde Pfeile nach oben (oder vllt nach rechts) und unten wählen, nach unten solange das Kommentar ausgeklappt ist und nach oben (bzw. rechts) wenn es zugeklappt ist. Die Pfeile dabei einfach nur als v bzw ^/> (natürlich in schöner)
