### ISSUE TITLE
Readme anpassen

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#13]
Die readme müsste etwas mehr auf dem laufenden gehalten werden. Ein Changelog wäre auch nicht schlecht.

**Comment by X39** [comment]
>Die readme müsste etwas mehr auf dem laufenden gehalten werden. Ein Changelog wäre auch nicht schlecht.

sagt der entwickler?
es wäre dein job den changelog einer jeden revision zu erstellen (btw. es ist nie zu spät an zu fangen ... daher die frage warum es immer noch nicht getan wurde ...)

http://keepachangelog.com/

bzgl format des changelogs ... ich hab mir irgend wann dieses format angeeignet:

    -|MILESTONE: RC 1.0|-
    BETA 2.1
    	Fixed
    		\- foo
    	Added
    	Removed
    		|v- bar
    		||- foobar
    		|\- barbar
    		\v- foofoo
    		 \- barfoo
    	Changed

wobei das auch nur vorliebe ist ...
jedoch gerade bei größeren projekten (wie diesem hier) sind changelogs unabdinglich

**Comment by mopsalarm** [comment]
Ah ich Pflege inzwischen immerhin schon eines mit, dass dem User angezeigt wird
