### ISSUE TITLE
API Dokumentation

### ISSUE THREAD

**Issue by maciossek** [mopsalarm/Pr0#131]
Gibt es eine Doku der API? Bzw. muss man sich explizit mit der API Authentifizieren als neue Anwendung? Vielleicht habe ich etwas Freizeit und setze mich an eine iPhone App.

**Comment by mopsalarm** [comment]
Gibt keine offizielle Doku. Musst dich nicht authentifizieren. Gucke dir das Interface Api.java an, das sollte als Doku ausreichen. ;)

**Comment by maciossek** [comment]
Alles klar, soweit war ich schon. Danke!
