### ISSUE TITLE
App auch auf F-Droid anbieten.

### ISSUE THREAD

**Issue by fabio963** [mopsalarm/Pr0#132]
Es wäre sinvoll die App auf dem alternativen Appstore für freie open source software anzubieten ( https://f-droid.org/ ). Autoupdatessollte man dann aber ausschalten. Wenn es doch Probleme gibt kann man AntiFeatures angeben ( https://f-droid.org/wiki/page/Antifeatures )

**Comment by mopsalarm** [comment]
Sorry, abgelehnt. Ich denke die wenigsten Benutzer im pr0gramm nutzen f-droid. Dafür  muss ich dann aber eine extra Version der App pflegen. Sehe ich nicht ein, da Autoupdate ja auch gut funktioniert.

**Comment by fabio963** [comment]
Es sollte nicht nötig sein den kompletten Autoupdate-Code zu entfernen. Entweder man schaltet es in der F-Droid Version aus (vielleicht automatisch Erkennung möglich) oder beim ersten Start wird dem Nutzer aller Versionen gefragt ob das Autoupdate der App aktiviert werden soll.

**Comment by mopsalarm** [comment]
Es geht nicht drum, den Autoupdate Code zu deaktivieren, sondern dass ich eine zweite Version pflegen muss. Andere App-Id, evnt anderer Buildprozess über f-droid (ich meine mal gelesen zu haben, dass die das aus deinem Code bauen?), etc. Dafür ist mir der Nutzen halt leider zu gering.

Ich habe jetzt immer noch zwei PlayStore-App-Varianten, die immer noch von einigen hundern Benutzern benutzt werden, die musste ich nach dem aus aus dem PlayStore auch noch ewig mitpflegen. Da habe ich keine Lust mehr zu - schon gar nicht für die 50 Leute auf pr0gramm, die f-droid nutzen.

Aus idiologischen Motiven finde ich die Idee allerdings gut :/

**Comment by fabio963** [comment]
Schade eigentlich. Ich würde ja helfen aber mir fehlt die Zeit und vor allem das wissen.

**Comment by BO41** [comment]
Ich bin mir nicht sicher, ob da wirklich so ein großer Aufwand nötig ist.
Vielleicht hat sich der ganze Prozess mittlerweile auch vereinfacht. [quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/)

Man könnte ja mal eine Umfrage machen, wie viele heute f-droid verwenden bzw die App dort gerne sehen würde. Vielleicht findet sich auch jemand der helfen kann :)

Ich denke F-Droid ist gerade der richtige Ort für eine Community wie diese :wink: 
(keine Zensur, gesunder Geschmack und nicht Geld geil)

**Comment by ketograph** [comment]
Ich würde mich auch freuen, wenn es auf F-Droid verfügbar wäre. 
Das dürfte aber nicht trivial umsetzbar sein: F-Droid [verbietet proprietäre Tracking/Analytic Tools wie Crashlytics und Firebase sowie Googles "play services"]( https://f-droid.org/de/docs/Inclusion_Policy/). 

Die werden aber verwendet (Pr0/app/build.gradle):
* [Firebase](https://github.com/mopsalarm/Pr0/blob/3dd7bd3cbbec69a23ee356696229082e5091eedd/app/build.gradle#L4)
* [Google Play Services](https://github.com/mopsalarm/Pr0/blob/3dd7bd3cbbec69a23ee356696229082e5091eedd/app/build.gradle#L179)

**Comment by mopsalarm** [comment]
Tur mir leid, ich sehe auch immer noch keinen Grund dafür.

**Comment by mist** [comment]
Für die, die F-Droid als Hauptstore nutzen, wäre es eine einfach möglichkeit die App ohne Benutzerinteraktion zu updaten.

Wärst du denn aufgeschlossen, wenn sich jemand anderes hierum kümmern würde?

**Comment by mopsalarm** [comment]
Nein, das rechtfertigt für mich den Aufwand nicht.

**Comment by mist** [comment]
Ich sehe für dich den Aufwand nicht ganz, wenn sich jemand anderes komplett drum kümmert die F-Droid-Version zu machen

**Comment by mrmaffen** [comment]
> @fabio963 Ich will die App nicht auf F-Droid haben weil ich dessen Updatefunktion so toll finden sondern weil für den Nutzer die Prüfung der Seriösität der Webseite leichter wird. Im Internet einfach apps herunterzuladen ist nicht empfehlenswert, auf f-droid ist das viel sicherer.

Seh ich absolut genauso. Sowohl die Idee eines Open-Source Stores wie F-Droid zu unterstützen als auch komplikationslos die Seriösität einschätzen zu können, sind für mich die Gründe warum diese oberaffentittengeile App auf F-Droid landen sollte. Den Buildprozess muss man einmal definieren und dann spuckt es dir automatisiert die F-Droid APK aus. Wenn das jemand anderes machen würde, seh ich für dich erst recht null Aufwand.

**Comment by mopsalarm** [comment]
Hm, verstehe. Ich kenne mich da nicht so sehr aus, wieso ist die Seriosität im f-droid store größer, als direkt von der offiziellen Website? Kann nicht jeder die App forken, patchen und dann in den f-droid store packen?

**Comment by mrmaffen** [comment]
Meine Annahme ist, dass F-Droid die APK entpackt und durchscannt bzgl Malware bzw fischigem Code. Glaub man kann auch nen Buildprozess auf F-Droid einrichten, sodass direkt der Quellcode geprüft und anschließend die APK automatisiert gebaut werden kann. Das hat natürlich alles seine Grenzen, aber immerhin besser als nichts.

**Comment by mopsalarm** [comment]
Ja, und das verstehe ich nicht. Die App ist open source, du kannst den Code hier direkt einsehen, du kannst die dir auch selbst bauen, wenn du möchtest. Fischigen Code erkennt f-droid auch nicht automatisch, wenn ich das nicht möchte. Wenn du nicht gerade die 30 tausend Zeilen Code genau durch gehen möchtest, musst du mir sowieso vertrauen, dass da keine scheiße drin ist, und dass ich genau das baue, was hier im Repository ist. Ich sehe also echt nicht den großen Vorteil.
Ich kann demnächst mal gucken, wie viel Aufwand das ist.

**Comment by mist** [comment]
F-Droid baut die App selber und lädt nie externe Binarys hoch. Es wird jedoch angestrebt, einen reproduzierbaren Buildprozess zu schaffen, sodass sowohl die F-Droid-Version, als auch die offizielle Version dieselben Prüfsummen haben.

> Kann nicht jeder die App forken, patchen und dann in den f-droid store packen?

Nicht direkt. Es wird schon ein grundlegender Check vor Aufnahme gemacht und die Entwickler werden gefragt, ob sie das möchten. Sprich wenn ich jetzt einfach forke, wird sie so leicht nicht in den Store kommen, da ich nicht die offizielle Version bin. Der Prozess hat bestimmt Angriffsvektoren, aber erstmal geht das nicht.

Für mich als Nutzer hat es also folgende Vorteile
- Updates passieren automatisch ohne mein Zutun
- Zweimalig (Installation+1. Update): Es fällt der Aufwand bezüglich "Externe Quellen erlauben" weg, (denn f-droid ist korrekt konfiguriert keine externe Quelle bzw. es muss nur einmalig für alle Apps erlaubt werden)
- Das Vertrauen, dass Source und Binary gleich sind, ist massiv höher

Ansonsten hatte ich ja indirekt mal angeboten zu schauen, dass du dich um nichts kümmern musst (außer einverstanden zu sein), das Angebot gilt weiterhin (jedoch hab ich mich selbst in den Gesamtprozess auch noch nicht eingelesen).

**Comment by mrmaffen** [comment]
> [https://f-droid.org/de/about/](https://f-droid.org/de/about/): F-Droid is a non-profit volunteer project. Although every effort is made to ensure that everything in the repository is safe to install, you use it AT YOUR OWN RISK. Wherever possible, applications in the repository are built from source, and that source code is checked for potential security or privacy issues. This checking is far from exhaustive and there are no guarantees.

Also meine Hauptmotivation war auch das Vertrauen besser einschätzen zu können, aber jetzt wo ich nen bisschen drüber nachgedacht habe ... Updates gibt es auch ohne F-Droid automatisch. Der Aufwand bzgl "externe Quellen" is verschwindend minimal. Und das Vertrauen, dass die hier angebotene APK und die Source übereinstimmen, ist hier auf Github komplett gegeben.

Glaub am Ende isses einfach Convenience und nen bisschen Security. Mein Prozess die App zu installieren war am Anfang auf F-Droid zu suchen und als das gescheitert ist, musste ich mich erstmal schlau machen, welche Quelle jetzt die offizielle ist. Das ging natürlich gut über die Verlinkung auf pr0, die ich zuerst nicht gesehen hatte. Bleibt nur zu hoffen, dass das Fußvolk nicht die APK aus einem der zig shady Stores lädt, die von Google und co ganz oben angezeigt werden. Aber ob F-Droid das Problem wirklich ausreichend vermindert ist auch fragwürdig.
