### ISSUE TITLE
Best of Kategorie frei einstellbar

### ISSUE THREAD

**Issue by TheBigFudge** [mopsalarm/Pr0#133]
Hey Mopsalarm,

erst einmal danke für deine wahnsinnig gute Arbeit! Nutze deine App jeden Tag. Jedoch fände ich es toll wenn man die Best of Kategorie frei einstellen kann. Beispielsweise auf +500 Benis. Das jetzige Minimum ist 1000.

**Comment by mopsalarm** [comment]
Ist bewusst so geregelt.

**Comment by TheBigFudge** [comment]
Darf ich fragen warum?

**Comment by mopsalarm** [comment]
1. Meiner Meinung nach ist 500 nur "top"  nicht "best of" 
2. Bekommt meine kleine vm Probleme. Das könnte man natürlich etwas optimieren. 

Möglich wäre, weswegen ich das hier auch noch wieder geöffnet habe, ist so eine Art Schieberegler direkt in der best of Kategorie umstellen kann.

**Comment by TheBigFudge** [comment]
1. Ich finde die Entscheidung könnte man dem Nutzer selbst überlassen. Bei mir ist es halt so, dass ich für "top" oft keine zeit habe und mir nur "Best of" anschaue. Dafür verpasst man halt auch posts mit 800 oder 900, für die eigentlich noch Zeit wäre. 

2. Wenn das ganze natürlich wirklich Probleme verursacht, sollte man es lassen. Man muss ja eh vom DAU ausgehen.

**Comment by mopsalarm** [comment]
Ich habe früher auch gedacht, dass ich dem User viele Entscheidungen gebe.. Das war ein Fehler. Die pr0gramm User sind die dümmsten die es gibt.

**Comment by TheBigFudge** [comment]
Das glaube ich dir. Naja danke für deine Antwort, jetzt kenne ich wenigstens die Gründe die dagegen sprechen.
