### ISSUE TITLE
Öffnen von Links in Externer App

### ISSUE THREAD

**Issue by Fragmin** [mopsalarm/Pr0#134]
Die Reddit is Fun App hat eine Funktion mit welcher man Regeln anlegen kann welche links wie geöffnet werden sollen

https://i.imgur.com/6ZIECWZ.png

Sowas wäre meiner Meinung nach Praktisch, wenn z.b imgur links direkt in der App und nicht erst im Browser geöffnet werden.

**Comment by mopsalarm** [comment]
Abgelehnt. Das ist Aufgabe deines Systems, nicht der App. Der User kann ja imgur als Standard für imgur Links einstellen. Falls der User gleichzeitig einen Incognito-Browser nutzen will, kann er auch den in seinem System einstellen. Hat aber auf jedenfall nichts in der App zu suchen.
