### ISSUE TITLE
Sound kurz hörbar obwohl gemuted

### ISSUE THREAD

**Issue by MoritzJT** [mopsalarm/Pr0#135]
Unter Alien Dalvik, der Android VM für SailfishOS ist zu beginn eines Videos trotz MUTE kurz Ton zu hören. Bei der Vorschau tritt das Problem ebenfalls auf.

**Comment by mopsalarm** [comment]
Habe ich von ein paar Leuten gehört, weiß leider nicht, was ich dagegen tun kann. 
Ich mache eigentlich Leise, direkt bevor playback beginnt (https://github.com/mopsalarm/Pr0/blob/8d1645c7d0179eb2e0fa7eb91c655a4962f25bd6/app/src/main/java/com/pr0gramm/app/ui/views/viewer/video/ExoVideoPlayer.java#L253)

Könnte es noch direkt nach dem prepare hier probieren https://github.com/mopsalarm/Pr0/blob/8d1645c7d0179eb2e0fa7eb91c655a4962f25bd6/app/src/main/java/com/pr0gramm/app/ui/views/viewer/video/ExoVideoPlayer.java#L150
Aber ich weiß nicht, ob das zusätzlich was bringt.

**Comment by MoritzJT** [comment]
Evtl. kommen schwächere oder schlechtere Systeme da nicht hinterher und reagieren asynchron, was Video & Tonwiedergabe und deren Sync angeht?

Müsste mich jetzt erstmal länger einlesen. Eine Hilfe beim Programmieren kann ich nicht bieten. Den Durchblick, wie es aufgebaut ist hast ja nur du.

Wenn ich also jetzt Vorschlage TON generell nicht mit zu übergeben, muss das ja nicht unbedingt der technischen Realität in der App entsprechen.

Man könnte es auch als Anreiz sehen in ein ordentliches System zu investieren...

**Comment by mopsalarm** [comment]
Probiere diese Version der App. Habe hinter das prepare ein `setMuted(true);` gesetzt.  Garantiere für nichts.

[app-open-release.apk.zip](https://github.com/mopsalarm/Pr0/files/330626/app-open-release.apk.zip)

**Comment by MoritzJT** [comment]
Die neue Version spielt keinen Ton mehr ab, wenn der gemuted ist. Allerdings in der Vorschau, bei nicht gemuted sein auch nicht.

Damit kann ich aber dennoch besser leben!

Danke

**Comment by mopsalarm** [comment]
Hm da war bei mir vorher schon kein Ton. Muss den mit dem zweiten Finger aktivieren. Muss ich mir morgen nochmal angucken.

**Comment by mopsalarm** [comment]
Ich schiebe jetzt gleich eine Beta dazu aus.

**Comment by mopsalarm** [comment]
Sollte nun gefixt sein, sonst wieder melden.
