### ISSUE TITLE
Kommentarinhalt verschwindet

### ISSUE THREAD

**Issue by Scarwolf** [mopsalarm/Pr0#136]
Wenn ich einen bestimmten Kommentar runtervote verschwindet der Inhalt, der Kommentar ist relativ lang, vieleicht liegts daran.

Hab hier mal n' Video davon: https://streamable.com/ugei (Buggt am Anfang ein wenig, sorry)
Betroffener Kommentar: https://pr0gramm.com/new/1383957:comment9515448

**Comment by mopsalarm** [comment]
Joa, liegt an deinem Gerät. Bzw an älteren Geräten, ist bekannt, kann ich aber jetzt nicht wirklich was machen. Trotzdem danke dafür!
