### ISSUE TITLE
/stalk/ Links werden nicht in der App geöffnet

### ISSUE THREAD

**Issue by schr3j** [mopsalarm/Pr0#138]
Die Links des pr0mium Features stelzen (z.B. https://programm.com/stalk/1410147) werden nicht in der App geöffnet (nur mit einem Links aus FB Messenger getestet, Code fehlt aber sowieso).
Ist jetzt nicht besonders dringlich sollte die App meiner Meinung nach aber können. 

Falls es nicht möglich ist den Feed dazu zu laden (jeder stelzt ja andere Accounts) wäre es schick einfach nur den verlinkten Post anzuzeigen.

**Comment by mopsalarm** [comment]
Da müssen nur die pattern in der Manifest xml und  ein paar reguläre Ausdrücke angepaßt werden.

**Comment by mightyBroccoli** [comment]
Nur so am Rande: Kann es sein das es daran liegt das der Link gar kein pr0 Link ist. 
[https://programm.com/stalk/1410147](url) =/= [https://pr0gramm.com/stalk/1410147](url)

**Comment by mopsalarm** [comment]
Das wäre ein Argument.  https://pr0gramm.com/stalk/1410147

**Comment by mopsalarm** [comment]
Nope, geht trotzdem nicht. Ich fix das nachher.

**Comment by mopsalarm** [comment]
Wenn ich so drüber nachdenke, machen stalk-Links überhaupt keinen Sinn. :-1: Die gelten ja (fast) nur für dich selbst.

**Comment by mopsalarm** [comment]
Fixed in https://github.com/mopsalarm/Pr0/commit/07679762dcfb536673db5eb0558b2fba6c79b4af

**Comment by schr3j** [comment]
Ja, sorry, da hab ich mich wohl verschrieben. Ja die Links gelten fast nur für einen selbst, es wäre halt cool wenn die App trotzdem einfach den korrekten Post anzeigt, selbst wenn der User kein pr0mium hat.

**Comment by mopsalarm** [comment]
Ach so. Hm mal gucken, ja, lässt sich machen. Plan ich mal für morgen ein!
