### ISSUE TITLE
pr0-tv

### ISSUE THREAD

**Issue by select** [mopsalarm/Pr0#139]
Hi, da ich kein Account habe bei pr0 habe wollte ich mal hier nach einem kleinen Feeback für meine brand neue pr0-tv Extension fragen. 

https://chrome.google.com/webstore/detail/pr0-tv/ncihhdjknepiomhfmhjkgfmofhmkbdme

Ist noch etas buggy aber wenns dann erst mal läuft ... :P

**Comment by mopsalarm** [comment]
Falscher Ort. Kauf dir pr0mium und mache einen Upload.
