### ISSUE TITLE
App am Tablet

### ISSUE THREAD

**Issue by kratostav** [mopsalarm/Pr0#14]
Also die App schaut am Tablet sehr gut aus is glaub ich nichts mehr zu machen.
Ich habs jetzt auf meinen Nexus 7 getestet.
![device-2015-03-06-110744](https://cloud.githubusercontent.com/assets/5694929/6523556/463ed1f4-c3f1-11e4-9180-7a9c5028c667.png)

**Comment by mopsalarm** [comment]
Aber auf einem 10" Tablet sollte man schon was machen, denke ich. Aber das hat momentan keine Priorät, würde ich sagen.
