### ISSUE TITLE
Tags abonnieren

### ISSUE THREAD

**Issue by dbelz** [mopsalarm/Pr0#140]
Ich hätte gerne ein Feature, um Tags abonnieren zu können. 

Würdet ihr sowas umsetzen oder soll man bei Interesse einfach einen Pull request stellen?

VG
Daniel

**Comment by mopsalarm** [comment]
Du kannst einfach nach etwas in Top oder Neu suchen und dann ein Lesezeichen für deine Suche anlegen.

**Comment by mYnDstrEAm** [comment]
Relevantes Issue: https://github.com/mopsalarm/Pr0/issues/161
