### ISSUE TITLE
Feature request: SOCKS Proxy

### ISSUE THREAD

**Issue by vredez** [mopsalarm/Pr0#141]
Wäre cool wenn die App eine Verbindung über einen SSH-Tunnel (aka SOCKS Proxy) zum pr0gramm Server aufbauen kann.
Pr0gramm ist in vielen Standard-Blacklists enthalten, wodurch ich z.B. die App nicht auf der Arbeit im WLAN nutzen kann ¯\\_(ツ)_/¯.

//edit: Genauer gesagt: Ich würde gerne Verbindungsdaten zu einem SSH-Server irgendwo eingeben können (Addresse, Name, Passwort/SSH-Key).

**Comment by mopsalarm** [comment]
Sorry, aber das ist nicht Sache der App sondern deines Systems. Richtige die ein VPN ein.
