### ISSUE TITLE
Neue Option: Sound an/aus bei Start

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#143]
Derzeit muss man noch raten ob der Sound letztes mal eingeschaltet wurde oder nicht - ich merke mir sowas jedenfalls nicht und habe ihn gerne per Default aus.  
(Ähnlich wie die Option _Zeige 'sfw' beim Start_)

**Comment by mopsalarm** [comment]
Sound wird nach 10min automatisch ausgeschaltet.

**Comment by mYnDstrEAm** [comment]
@mopsalarm das wusste ich nicht. Das ist schon mal ganz nützlich. Ich denke aber, dass die meisten das nicht wissen werden.  
Und auch so wäre die Option praktisch: also zB wenn man den Sound immer an haben möchte oder ihn auch schon 5 min nach einem erneuten Start aus haben möchte.
