### ISSUE TITLE
Windows UWP

### ISSUE THREAD

**Issue by Aegasx3** [mopsalarm/Pr0#144]
Hallo erstmal,
Ich hätte da mal so ein Anreiz, eine Windows 10 UWP App. Ein ehemaliger User Gibilmanno Vincenzo hat da schon einen Grundstein gelegt ( https://github.com/PepperMelon/pr0gramm-viewer-universalapp.git ).
Ein zweiten gibt es auch schon https://github.com/deify/pr0grammUWP
 Benis up für eine WIn 10

**Comment by mopsalarm** [comment]
Hier geht's um die Android App, für die Windows App schreibe doch in dem Windows App repo ein Issue.
