### ISSUE TITLE
pr0 widget

### ISSUE THREAD

**Issue by Yothri** [mopsalarm/Pr0#146]
Hallo,

mir is gerad ne Idee gekommen, weiß aber nicht ob sich das technisch umsetzen lässt weil ich mich mit der pr0gramm API noch nicht gut genug auskenne.

Und zwar wäre ein widget richtig geil wo man die größe einstellen kann und dort immer der neueste post angezeigt wird (ob nun neu oder beliebt) kann man sich dann in den Widget einstellungen aussuchen.

Wenn man dann so am Handy aufm Desktop ist und das pr0 widget hat wäre das doch mal mega geil.

Hoffe die Idee gefällt noch mehreren :)

Grüße

**Comment by mopsalarm** [comment]
Ich persönlich glaube nicht, dass das besonders gefragt ist.

**Comment by Yothri** [comment]
Wäre es denn technisch möglich? Vielleicht begebe ich mich irgendwann mal daran und lade es als Pull Request hoch wenn es fertig und getestet ist.

**Comment by mopsalarm** [comment]
Klar ist es technisch möglich

**Comment by Yothri** [comment]
Okay.

Danke für die Rückmeldung.
