### ISSUE TITLE
Offline Modus

### ISSUE THREAD

**Issue by masterka00** [mopsalarm/Pr0#147]
Es gibt ja schon die Möglichkeit Medien vorzuladen. Wenn man diese dann jedoch ohne Internet Zugriff anschauen möchte gibt es ständig Fehler.

Schön wäre ein Offline Modus, in dem man den vorgeladenen Content inclusive Tags und Kommentaren anschauen kann.

Gibt es als Workaround eine Möglichkeit die vorgeladenen Medien außerhalb der App zu browsen?

**Comment by mopsalarm** [comment]
Nope, sorry wird es nicht geben.
