### ISSUE TITLE
Favoriten-Symbol falsch dargestellt

### ISSUE THREAD

**Issue by FallenKN** [mopsalarm/Pr0#148]
![img_20161005_235313](https://cloud.githubusercontent.com/assets/13277346/19133125/02d544c8-8b57-11e6-8d52-c89d5bea0797.png)

Das Herz-Symbol zum Hinzufügen von Posts und Kommentaren wird nicht von allen Schriftarten unterstützt und wird als Stern angezeigt.
Ziemlich schwer mit dem Daumen zu treffen..

**Comment by mopsalarm** [comment]
Das plus und minus auch nicht. Du sollst aber auch die Schrift nicht ändern. Das geht standardmäßig auch gar nicht auf Android. Womit änderst du die?

**Comment by FallenKN** [comment]
@mopsalarm Hab ich nicht, Hersteller wie Huawei und Samsung verpassen ihren Geräten nicht nur eine angepasste Benutzeroberfläche sondern auch andere Schriftarten

**Comment by mopsalarm** [comment]
Das kann sein, das trifft aber nicht auf Textfelder zu, auf denen ich die Schriftart explizit selbst setze, oder gar die Text selbst zeichne, wie dort. Da muss ich erstmal davon ausgehen, dass du zb Xposed oder irgendwelche andere Schweinerei benutzt.

**Comment by FallenKN** [comment]
@mopsarlarm Habe nichts geändert war bei meinem mobilen Endgerät von Huawei schon so, und Schweinereien benutze ich nicht da mein Gerät nichtmal gewurzelt ist.

**Comment by mopsalarm** [comment]
Sorry, aber ich kann nichts dazu im Internet finden und es auch nicht reproduzieren. Ich schiebs mal auf dein Gerät. Könntest nochmal die App öffnen, auf einen Post gehen, wo das Icon nicht richtig angezeigt wird, und dann sofort zurück, und Feedback über die App direkt schreiben. Dann bekomme ich evnt ein Log, mit dem ich vielleicht was anfangen kann.

**Comment by FallenKN** [comment]
@mopsalarm trotzdem vielen dank für die Mühe. Feedback ist raus!
