### ISSUE TITLE
Ton ein/aus Taster nicht sichtbar wenn Tablet im Querformat 

### ISSUE THREAD

**Issue by JoK3R-GER** [mopsalarm/Pr0#149]
Bei meinem Tablet (Samsung Galaxy Tab S2 8 Zoll) ist der Ton Button bei Videos nicht immer zusehen.
Siehe Screenshots hier [http://m.imgur.com/a/vCO8C](url)
EDIT: Edits nicht beachten, da hat mein Tablet Blödsinn gemacht

**Comment by mopsalarm** [comment]
Ist bekannt, danke. Tablets werden sehr wenig benutzt, deswegen haben sie aktuell nicht die höchste Priorität. Steht aber auf der Liste.

**Comment by mopsalarm** [comment]
In commit 276f3bd gefixt.
