### ISSUE TITLE
App Parsing Fehler bei der Installation 

### ISSUE THREAD

**Issue by ToPon123** [mopsalarm/Pr0#151]
Gerät: LG G3 (d855)
System: neuste Cyanogenmod 13 Nightly 

Habe apk schon mehrmals heruntergeladen, aber kann sie trotzdem nicht installieren. Immer wieder Parsing Fehler.

**Comment by mopsalarm** [comment]
Ich kann mich nur wiederholen, das Problem liegt bei dir. Die Datei funktioniert. Prüfe, ob der Download erfolgreich war, die Datei muss etwa 2.9mb groß sein. Alternativ lade sie am PC herunter und kopiere sie über Dropbox auf dein Telefon.
