### ISSUE TITLE
Kompatibilität zu One Plus 3T (Android 7.0) 

### ISSUE THREAD

**Issue by lSonnYl** [mopsalarm/Pr0#155]
Guten Tag,

ich möchte mich erst einmal bei allen Entwicklern für die pr0gramm App bedanken :) echt super App!
Mein Problem ist derzeit, dass ich diese auf meinem neuen Handy (One Plus 3T mit Android 7.0) nicht installiert bekomme. Trotz erlaubter Installation von unbekannten Quellen wird direkt beim öffnen der Datei die Fehlermeldung "Beim Parsen des Pakets ist ein Fehler aufgetreten".
Das Handy wurde bereits neugestartet sowie die App erneut heruntergeladen, beides ohne Erfolg.
Anbei ist ein Screenshot der Fehlermeldung, sowie die Daten zum Handy.

![screenshot_20170225-094246](https://cloud.githubusercontent.com/assets/26022524/23330359/404c0034-fb4c-11e6-90df-c7ed4027ad60.png)
![screenshot_20170225-110337](https://cloud.githubusercontent.com/assets/26022524/23330361/45c0a718-fb4c-11e6-89fc-84b80f8d50b0.png)
![screenshot_20170225-110341](https://cloud.githubusercontent.com/assets/26022524/23330363/4703b9a8-fb4c-11e6-9f8e-3ff71f335b65.png)

**Comment by mopsalarm** [comment]
Wo hast du die App heruntergeladen? Sieht für mich nach einem fehlerhaft heruntergeladenen Paket aus

**Comment by lSonnYl** [comment]
Top danke für die schnelle Reaktion :+1: 
Habe sie direkt von der pr0gramm Seite (https://app.pr0gramm.com/#download) heruntergeladen.

**Comment by mopsalarm** [comment]
Dann probiere es noch mal und validiere, dass die heruntergeladene Datei eine Größe  von 2 bis 3 MB hat.

**Comment by lSonnYl** [comment]
Hat sich erledigt... war leider ein Fehler meinerseits. Die heruntergeladene App muss mit dem Programm Downloads geöffnet werden und nicht über den Dateimanager. Beim Dateimanager wird vermutlich ein anderes Programm zur Ausführung genutzt, welches nicht für Installationsdateien gedacht ist.
Danke für deine schnelle Antworten jetzt klappt alles :+1:
