### ISSUE TITLE
Betrifft die Website: FAQ aktualisieren

### ISSUE THREAD

**Issue by DominikTV** [mopsalarm/Pr0#156]
Ich denke mal, dass kann auch aktualisiert werden 😃 

![2017-03-07 16_48_02-pr0gramm app](https://cloud.githubusercontent.com/assets/7671638/23664559/282ee4f0-0356-11e7-86b6-f42e5326e65e.png)

**Comment by mopsalarm** [comment]
Stimmt natürlich.
