### ISSUE TITLE
Werbung

### ISSUE THREAD

**Issue by f0o** [mopsalarm/Pr0#157]
Es ist sehr schade, dass mit dem heutigen release nun auch Werbung in der App ist.

My 2ct

**Comment by mopsalarm** [comment]
Jo, aber du kannst dir ja pr0mium holen, oder die 5000 Euro übernehmen, die cloudflare jetzt monatlich haben möchte. So viel Geld hast du nicht? Dann schau dir die Werbung an. 
https://pr0gramm.com/new/1815096:comment13934177

**Comment by f0o** [comment]
Passt schon, kann ja immernoch cherry pick merge von upstream machen und lokal eine werbe-freie version bauen

**Comment by schrej** [comment]
How to act like a FTB.
