### ISSUE TITLE
Kein Deepsleep im Lockscreen

### ISSUE THREAD

**Issue by affelwafro** [mopsalarm/Pr0#158]
Moin moin,
ich wollte dich auf einen kleinen Bug aufmerksam machen den ich die Tage entdeckt habe.
Ich habe manchmal das Phaenomen das mein Telefon im Lockscreen nicht mehr in den Deepsleep uebergeht.

Der Bug ist jedes mal reproduzierbar bei mir auf folgende Weise,
- App starten
- dann scrolle ich mich durch die ersten paar Uploads bis ein webm kommt
- waehrend das webm laeuft des Telefon sperren
- Telefon mit dem Homebutton aufwecken um die Zeit zu ueberpruefen
- Display schaltet sich nicht mehr ab
- App beenden, alles ist wieder normal

Wenn ich den Sperrbutton betaetige um das Handy aufzuwecken geht das Display meist wieder aus. Beim Homebutton bleibt es jedes mal. Jetzt gerade waehrend ich den Text verfasse laeuft das Display schon 5 Minuten. Normalerweise gehts nach 10 Sekunden wieder aus.
Komischerweise tritt der Effekt nach dem ersten Mal dann auch bei Bildern auf.

Ich nutze ein Samsung Galaxy S6 (SM-G920F) mit Lollipop v5.1.1
Wenn ich dir mit Logcats behilflich sein kann geb Bescheid (sofern das hier ueberhaupt was bringt).

Fuer Rueckfragen stehe ich dir gern zur Verfuegung.

Liebe Gruesse

**Comment by mopsalarm** [comment]
Moin. Ich kann das Problem nicht reproduzieren, ich habe aber auch keinen Homebutton. Selbst wenn, ist das nichts, was ich aus der App heraus beeinflussen kann, da ich den wakelock nicht selbst hole sondern die View.keepScreenOn Funktionalität verwende. Wenn da ein Bug drin ist, dran von Samsung oder dem alten Android. Ohnehin schieben ich es auf Samsung, da die gerne mal was verhunzten ;)
