### ISSUE TITLE
Klickbare Posts bei Funden bei der Repost-Suche vor einem Upload

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#160]
Vor einem Upload wird ja - zumindest bei Bildern - geprüft ob das vorher schon mal gepostet wurde. Funde werden dann als kleine Bildchen angezeigt. Diese sind derzeit leider nicht klickbar. Es wäre cool, wenn man die anklicken könnte um dann zum entsprechenden Post zu gelangen.  
Also zum Beispiel um zu checken, ob das wirklich das gleiche Bild ist oder nur ähnlich aussieht oder um Soße nachzureichen oder weil man einfach schauen will wie sich der vorherige Post gemacht hat.

**Comment by mopsalarm** [comment]
Ich könnte ohne Schwierigkeit ein kleines Popup einblenden mit dem vergrößerten Bild/Video. So wie wenn man auf einen Post im Feed länger drückt.

**Comment by mYnDstrEAm** [comment]
Das wäre nützlich um zu checken, ob das wirklich das gleiche Bild ist oder nur ähnlich aussieht aber nicht für andere Sachen. Im Normalfall möchte ich gerne direkt zum Post springen - aber evtl kann man den Popup ja permanent anzeigen bis man woanders hin tapt und den Link im Popup inkludieren. Andernfalls fände ich es aber besser wenn die Bildchen verlinkt wären.

**Comment by mopsalarm** [comment]
Ich bin der Meinung, dass das Bild öffnen reicht.
