### ISSUE TITLE
Systemproxy verwenden

### ISSUE THREAD

**Issue by skuzzle** [mopsalarm/Pr0#162]
Moin,

ich habe auf meinem Android einen Proxy Server für mein WLAN angegeben. Es scheint aber so, als würde die App diesen Proxy nicht automatisch nutzen. Wäre es möglich hierfür vllt eine Einstellungsoption anzubieten?

**Comment by mopsalarm** [comment]
Lässt sich sicher machen, werde ich mir mal anschauen.

**Comment by mopsalarm** [comment]
Ist das noch der Fall? Ich kann das Problem nicht (mehr) reproduzieren.
