### ISSUE TITLE
Automatisches Leeren des Caches

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#164]
Die pr0gramm App ist bei mir eine von nur zwei Apps die wirklich viel Speicherplatz mit ihrem Cache verbrauchen. Der Cache wächst bei mir immer sehr schnell auf 200MB. Leeren kann ich ihn über Anwendungsmanager -> pr0gramm -> Speicher -> CACHE LEEREN

Es wäre gut wenn die App den Cache automatisch löschen würde. Möglicherweise könnte es auch eine Option dazugeben. Möglich wäre beispielsweise den Cache zu säubern...

* ...beim Schließen der App
* ...ab einer bestimmten Größe des Caches
* ...in bestimmten Intervallen (zum Beispiel alle 5 Tage)

**Comment by mopsalarm** [comment]
Nein, das würde den Sinn eines Caches ja zerstören. Es geht ja da rum, dass die Medien, wenn möglich, nicht ein zweites heruntergeladen werden müssen. Wenn ich den Cache immer leer machen würde, könnte ich ihn ja auch ganz abschalten.

**Comment by mYnDstrEAm** [comment]
Stimmt; wenn man aber wenig Speicherplatz hat oder eben Speicherplatz freimachen möchte wäre das allerdings schon praktisch. Von daher der Vorschlag das einen Optionspunkt zu machen.  
Also eine Option für das automatische Löschen des Caches und/oder einen Button zum Löschen des Caches (eventuell mit Hinweis, dass dies dazu führt das Dateien erneut runtergeladen werden).

**Comment by mopsalarm** [comment]
https://www.google.de/amp/s/amp.reddit.com/r/tasker/comments/446hyb/clear_cache_action/
