### ISSUE TITLE
Verhalten von doubleTapToUpvote

### ISSUE THREAD

**Issue by 657870** [mopsalarm/Pr0#167]
Ich habe die Option doubleTapToUpvote aktiv. Im Potrait Mode funktioniert es wie erwartet. Wird die App im Landscape Mode bedient so erfolgt keine Aktion für ein double tap.

**Comment by mopsalarm** [comment]
Sorry, aber das kann ich nicht reproduzieren. Kannst du ein Video davon machen?

**Comment by 657870** [comment]
Kann ich jetzt auch nachvollziehen. Am Smartphone funktioniert die Option ordnungsgemäß. Am Samsung TAB S2 nicht. Die Darstellung ist auch eine andere. Man hat ja eine Side by Side Ansicht. Links der Container für die Medien rechts die Kommentarliste und in dieser Ansicht funktioniert doubleTapToUpvote nicht. Falls noch notwendig, versuche ich heute Abend ein Video davon herzustellen.

**Comment by 657870** [comment]
Video hinzugefügt
[doubleTapToUpvote.zip](https://github.com/mopsalarm/Pr0/files/1542995/doubleTapToUpvote.zip)

**Comment by mopsalarm** [comment]
Danke. Schaue ich mir morgen mal an.

**Comment by mopsalarm** [comment]
Kann ich nicht reproduzieren: https://www.dropbox.com/s/k9meh901w98eo3i/VID_20171209_130609.mp4?dl=0

**Comment by 657870** [comment]
Interessanterweise kann ich deinen Test reproduzieren. Der Unterschied zu meinem Video liegt am Inhalt im Container. Bei Webm funktioniert doubleTapToUpvote, auch bei mir. Bei Bildern habe ich das Verhalten aus meinem Video.

**Comment by mopsalarm** [comment]
So, f18e415 sollte das fixen.
