### ISSUE TITLE
Suchlinks mit Leerzeichen sind nicht korrekt verlinkt

### ISSUE THREAD

**Issue by pr0tools** [mopsalarm/Pr0#169]
*Habe gerade kein besseres Beispiel zur Hand*
![bildschirmfoto](https://user-images.githubusercontent.com/33316308/34337968-3c2e543c-e964-11e7-8160-84a7e071972f.png)

Wenn man dann auf den Link klickt, landet man bspw nur auf "Dachs", ohne "awww".

[Relatierter Kommentar](http://pr0gramm.com/new/2297377:comment19277191)

**Comment by mopsalarm** [comment]
Läuft inzwischen
