### ISSUE TITLE
Musikwiedergabe stoppt bei webms

### ISSUE THREAD

**Issue by BenjaminBrossi** [mopsalarm/Pr0#17]
Wenn man Musik hört und auf ein webm wechselt, wird die Wiedergabe gestoppt.

**Comment by DaDude** [comment]
Wird sogar schon gestoppt, wenn man auf ein Bild wechselt, auf das ein webm folgt. Wahrscheinlich wird das vorgeladen oder?

**Comment by mopsalarm** [comment]
Ja, der ViewPager läd immer links und rechts vom aktuell angezeigten Bild bereits ein PostFragment mit dem entsprechenden Player.
Das Problem ist, dass das VideoView den Audiofokus holt. Solange ich/jemand nicht einen stabilen eigenen Player implementiert (hatte irgenwdann schonmal angefangen), muss das aktuell noch so sein. :/
