### ISSUE TITLE
App stürzt regelmäßig ab

### ISSUE THREAD

**Issue by 0x2A** [mopsalarm/Pr0#170]
Seit dem letzten update stürzt die app regelmäßig ab, vor allem bei größeren posts.
Maze Alpha
Android 7.0
Kernel 4.4.15+

**Comment by mopsalarm** [comment]
Erstelle mir bitte ein logcat von so einem Absturz, sonst kann ich leider nichts tun. Sehe auch in crashlytics nichts zu so einem Telefon.

**Comment by 0x2A** [comment]
Ich habe mal einen logverlauf von App start bis Absturzt auf pastebin hochgeladen:

https://pastebin.com/Fcikiuq3

**Comment by mopsalarm** [comment]
Ich sehe da keinen Absturz im Log.

**Comment by 0x2A** [comment]
Könnte auch sein. Werde nochmal mit adb eine gescheite log erstellen und schauen ob ich was finde. Wenn nicht muss ich wohl damit leben.
