### ISSUE TITLE
Best Of Lesezeichen nach Update verschwunden

### ISSUE THREAD

**Issue by amixor35** [mopsalarm/Pr0#171]
Habe die App nun mehrmals deinstalliert und wieder installiert, jedoch scheint das Best of Lesezeichen irgendwie verschwunden zu sein.

**Comment by mopsalarm** [comment]
Die App prüft periodisch, ob der Endpunkt für die Kategorien erreichbar ist. Wenn nicht, werden die extra Kategorien ausgeblendet.
