### ISSUE TITLE
"Repost" Overlay nur, wenn Repost-Tag an vorderer Stelle steht

### ISSUE THREAD

**Issue by DominikTV** [mopsalarm/Pr0#173]
Idee:
Wäre es möglich, das Repost-Overlay nur anzeigen zu lassen, wenn der Repost-Tag an vorderer stelle steht? Er wird, z.B. [hier ](https://pr0gramm.com/top/2554373) angezeigt, obwohl der Tag an letzter stelle steht, weil irgendjemand den Tag ohne Beweis hinzu gefügt hat (deshalb wurde dieser auch gedownvoted).
Ich hoffe, ich konnte erklären, was ich meine :smile:

**Comment by mopsalarm** [comment]
Um das Banner anzuzeigen wird im Hintergrund einfach eine Suche nach Repost durchgeführt. Wird der Tag heruntergevoted, ist er unter dem Suchbegriff nicht mehr zu finden. Bei mir wird der Post deswegen auch gar nicht als Repost markiert.

**Comment by DominikTV** [comment]
@mopsalarm Tatsache, mittlerweile ist er auch nicht mehr als Repost markiert. Heute morgen war das aber noch so, wenn ich dass das nächste mal sehe, gebe ich ansonsten nochmal bescheid.
Wie weit geht denn die Suche? Bzw. ab wann wird der Tag nicht mehr gefunden?

**Comment by mopsalarm** [comment]
Es wird ein Konfidenzwert aus der Anzahl der up und downvotes berechnet und der bei der Suche verwendet. Genaue Werte wie 0.3 bringen dir jetzt nicht viel.
