### ISSUE TITLE
Anleitung zum compilen

### ISSUE THREAD

**Issue by HaxXorHardy** [mopsalarm/Pr0#177]
Gibt es eine Anleitung um die App zu compilen? Unix oder win? Was sind die Voraussetzungen dafür?

LG Hardy

**Comment by mopsalarm** [comment]
Nein, wenn du das fragst, bist du hier wahrscheinlich falsch.
Lese etwas über gradle und über Android Development. Google hat viel und gute Doku.
https://developer.android.com/training/basics/firstapp/
