### ISSUE TITLE
Favoriten teilweise nicht als Favoriten gekennzeichnet

### ISSUE THREAD

**Issue by d-Rickyy-b** [mopsalarm/Pr0#178]
Steps to reproduce:

1) Favoriten öffnen
2) Einen Hochlad auswählen und damit öffnen

Weder Herz, noch Blussi sind rot markiert. Tritt wahrscheinlich nur bei im Browser markierten favs auf, nicht bei denen, die direkt in der App favorisiert wurden.

**Comment by mopsalarm** [comment]
Ist bereits gefixt und kommt mit dem nächsten Release.
