### ISSUE TITLE
Sucherlauf leeren/bearbeiten

### ISSUE THREAD

**Issue by holzmaster** [mopsalarm/Pr0#181]
Bin Tippen in der Suche tauchen vorherige Suchbegriffe auf. Kann man daraus einzelne Einträge löschen?

Cool wäre:
- Liste aller gespeicherten Vorschläge
- Liste leeren können
- (Einzelne Elemente entfernen)

**Comment by mopsalarm** [comment]
Moin, das wird wahrscheinlich nicht passieren. Aufwand gegen Nutzen und so. Aber du kannst alle Einträge löschen - oder einen PR einstellen!

**Comment by holzmaster** [comment]
Find ich okay. Wie lösche ich alle? Kann ich ausstellen, dass es gespeichert wird?

**Comment by mopsalarm** [comment]
In den Einstellungen gibt es einen Knopf zum Löschen der Suchhistorie

**Comment by holzmaster** [comment]
Hab ihn jetzt gefunden. Er sticht nicht als Button heraus. Wenn man ihn drückt passiert nichts. Deshalb mein letzter Vorschlag: Einen Toast anzeigen, nachdem der Verlauf gelöscht wurde (hab sonst den Eindruck, dass nichts passiert).

**Comment by MartinX3** [comment]
Ein haptisches Feedback fände ich auch schön.
