### ISSUE TITLE
Gesehene Einträge wahlweise ausblenden

### ISSUE THREAD

**Issue by MartinX3** [mopsalarm/Pr0#182]
Eine Möglichkeit, statt einen Haken anzuzeigen, den Eintrag auszublenden wäre nett.

**Comment by mopsalarm** [comment]
Das wird es nicht geben. Dabei geben sich zu viele unbeantwortete Fragen zum Verhalten. Sorry.

**Comment by MartinX3** [comment]
Gut, vom Verhalten her hätte ich gesagt, dass die App den Eintrag einfach als leeres Arrayfeld ausblenden müsste, statt ein Overlay mit einem Haken drauf zu setzen.

Und bei der Option "Bilder als gesehen markieren" gibt es ja bereits Radiobuttons, dort könnte man ein weiteres mit dem Text "Ausblenden" hinzufügen.

Welche unbeantworteten Fragen zum Verhalten blieben noch?

**Comment by mopsalarm** [comment]
Was ist, wenn die letzten 120 Posts ausgeblendet sind, lade ich direkt die nächste Seite? Was ist eben ich einem Link zu einem gestehenen Post anklicke und zurück drück, ist es dann weg oder da? Was ist wenn ich die Suche nutze, sind die Posts dann auch weg? Wenn ich alles zum Tag "Katze" angucke, muss ich dann nach ein paar Tagen immer die ersten 5 Seiten laden bis ich ungesehene Ergebnisse bekomme? Wenn ich Suchen anders behandle, was gilt dann alles als Suche? Anschauen der Uploads eines Users, oder blende ich da auch für Posts aus? Was ist, wenn ich den coolen Post von gestern wieder sehen will, muss ich dann jedesmal die Einstellung ändern, damit der Post wieder angezeigt wird?

**Comment by MartinX3** [comment]
> Was ist, wenn die letzten 120 Posts ausgeblendet sind, lade ich direkt die nächste Seite?
Man könnte Anhand der Bildschirmgröße erreichnen, wie viele Einträge auf einen Bildschirm passen.
Anhand dessen und der Zahl der angesehenen Einträge könnte man errechnen, wie viele Seiten angezeigt werden müssten, oder?

Btw. die pr0-API bietet keine Möglichkeit nur noch nicht angesehene Inhalte zu empfangen?
Gabs da nicht mal die News, dass der "bereits gesehen" Status synchronisiert wird?

> Was ist eben ich einem Link zu einem gestehenen Post anklicke und zurück drück, ist es dann weg oder da?

Er wäre weg. Ich sehe ja auch den Haken, wenn ich wieder zurück gehe.

> Was ist wenn ich die Suche nutze, sind die Posts dann auch weg?

Natürlich, ich habe sie ja bereits gesehen.

> Wenn ich alles zum Tag "Katze" angucke, muss ich dann nach ein paar Tagen immer die ersten 5 Seiten laden bis ich ungesehene Ergebnisse bekomme?

Siehe erste Antwort.

> Wenn ich Suchen anders behandle, was gilt dann alles als Suche?

Wie meinst du das?

> Anschauen der Uploads eines Users, oder blende ich da auch für Posts aus?

Genau, man blendet sie aus.
Die werden ja auch je nach Filter ausgeblendet.
Hmmm, man könnte daraus auch einen lokalen Filter machen.

> Was ist, wenn ich den coolen Post von gestern wieder sehen will, muss ich dann jedesmal die Einstellung ändern, damit der Post wieder angezeigt wird?

Natürlich, die Filter muss ich auch von Hand ändern.

Man könnte natürlich auch einen Schalter hinter diesem Menüpunkt mit dem 3-Punkte-Piktogram hinterlegen.

**Comment by mopsalarm** [comment]
Die pr0gramm Api ist userunabgängig, der Gesehen Status kann also nicht in die Suche einfließen. Ich möchte nicht 5 Suchanfragen stellen bis Ergebnisse kommen und ich möchte auch nicht mal Posts anzeigen und mal nicht. Achte mal drauf wie du das pr0gramm so benutzt, ich wette du müsstest diese Option täglich mehrmals hin und herschalten. Das ist nicht schön.
Die Idee gibt's schon länger, aber es gibt keine gute Lösung bisher, deswegen ist das weiterhin abgelehnt.

**Comment by MartinX3** [comment]
Dann sollte die API überarbeitet werden, ganz im Sinne von REST und der benötigten Funktionalität.
Immerhin wird diese APP als die offizielle auf der Homepage ausgewiesen.
