### ISSUE TITLE
"Pr0gramm wurde geschlossen" App Crash 

### ISSUE THREAD

**Issue by 0dr** [mopsalarm/Pr0#183]
Seit 1.154.1 funktioniert die App nicht mehr. (Aktuellster Test mit 1.154.7)
Kurz nach dem ausführen beendet sich diese mit o.g. Nachricht. 

Der Crash scheint erst aufzutreten wenn die ersten Bilder fertig geladen wurden, da man manchmal auch bis in die Einstellungen gelangt.

Das Gerät ist ein "Wiko Rainbow light" 
Android 5
Kernell 3.10.54+

**Comment by mopsalarm** [comment]
Kannst du am PC ein mit adb ein logcat von dem Absturz anlegen?

**Comment by 0dr** [comment]
Wenn man es nicht vom phone loggen kann, wird es ein paar Tage dauern bis ich wieder Zugriff auf einen PC habe.

**Comment by mopsalarm** [comment]
Sollte alles wieder laufen
