### ISSUE TITLE
App Crash bei großem Content

### ISSUE THREAD

**Issue by 0x2A** [mopsalarm/Pr0#187]
Ich hatte dieses Problem schon einmal mit einer älteren Version, nun ist es wieder aufgetaucht:
Wenn ich in der App einen längeren Post anzeige, stürzt diese ab, meist mit der Meldung "Die Anwendung wurde beendet".
Ich habe mal die Git version auf meinem Phone debugged und folgende Log erhalten:

"I/[RxIoScheduler-7] FancyExifThumbnailGenerator: Building fancy thumbnail took 41.1204 ms
I/[main] FeedFragment: Lifecycle 127483941: DESTROY_VIEW
I/[main] DrawerFragment: Lifecycle 1754246: CREATE_VIEW
I/[main] DrawerFragment: Moving to index: 13
I/[main] DrawerFragment: Lifecycle 1754246: START
I/[main] DrawerFragment: Lifecycle 1754246: RESUME
I/[main] DrawerFragment: Setting feed item activate at 13 to PostFragment{58280f1 id=0x7f0900f6}
I/[main] PostFragment: Injecting services took 10.5354 ms
I/[main] PostFragment: Lifecycle 92438769: ATTACH
I/[main] PostFragment: Lifecycle 92438769: CREATE
I/[main] PostFragment: Injecting services took 3.9834 ms
I/[main] PostFragment: Lifecycle 255846711: ATTACH
I/[main] PostFragment: Lifecycle 255846711: CREATE
I/[main] PostFragment: Injecting services took 4.4292 ms
I/[main] PostFragment: Lifecycle 4163814: ATTACH
I/[main] PostFragment: Lifecycle 4163814: CREATE
I/[main] PostFragment: Lifecycle 92438769: CREATE_VIEW
I/[main] PostFragment: MediaView.newInstance took 173.8986 ms
I/[AsyncTask #3] Decoder: Decoder.init(context, https://img.pr0gramm.com/2018/12/05/c6b412fc9388d8f9.jpg) called
I/[main] PostFragment: Initialize media view took 206.4667 ms
I/[main] PostFragment: Got new list of 0 comments
I/[main] PostFragment: Lifecycle 92438769: START
I/[main] PostFragment: Switching viewer state to true
I/[main] MediaView[2870188]: Should start playing media
I/[main] PostFragment: Lifecycle 92438769: RESUME
V/FA: Setting current screen to name, class: Item, Item
V/FA: Recording user engagement, ms: 14887
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=Feed, firebase_previous_id(_pi)=8584918085266836570, firebase_previous_screen(_pn)=Feed, firebase_screen_class(_sc)=Item, firebase_screen_id(_si)=8584918085266836582, firebase_screen(_sn)=Item}]
I/[main] PostFragment: Lifecycle 255846711: CREATE_VIEW
D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=14887, firebase_screen_class(_sc)=Feed, firebase_screen_id(_si)=8584918085266836570, firebase_screen(_sn)=Feed}]
W/ExifInterface: Stop reading file since a wrong offset may cause an infinite loop: 0
I/[RxIoScheduler-22] FancyExifThumbnailGenerator: Building fancy thumbnail took 17.7147 ms
I/[main] VideoMediaView: Using exo player to play videos.
I/[main] ExoVideoPlayer: Create ExoPlayer instance
I/ExoPlayerImpl: Init 621e5e0 [ExoPlayerLib/2.8.4] [Alpha_X, Alpha_X, MAZE, 24]
I/[main] PostFragment: MediaView.newInstance took 364.4654 ms
I/[main] PostFragment: Adding view android.widget.ProgressBar{45d3e17 G.ED..... ......I. 0,0-0,0} to placeholder
I/[main] PostFragment: Adding view androidx.appcompat.widget.AppCompatSeekBar{a66f10e GFED..... ......I. 0,0-0,0} to placeholder
I/[main] PostFragment: Adding view androidx.appcompat.widget.AppCompatImageView{9d5662f V.ED..C.. ......ID 0,0-0,0 #7f0900ea app:id/mute} to placeholder
I/[main] PostFragment: Initialize media view took 437.3950 ms
I/[main] PostFragment: Got new list of 0 comments
I/[main] PostFragment: Lifecycle 4163814: CREATE_VIEW
I/[main] PostFragment: MediaView.newInstance took 24.9688 ms
W/ExifInterface: Stop reading file since a wrong offset may cause an infinite loop: 0
I/[main] PostFragment: Initialize media view took 49.4030 ms
I/art: Background sticky concurrent mark sweep GC freed 6827(713KB) AllocSpace objects, 2(40KB) LOS objects, 0% free, 22MB/22MB, paused 5.486ms total 47.013ms
I/[RxIoScheduler-25] FancyExifThumbnailGenerator: Building fancy thumbnail took 22.1194 ms
I/[main] PostFragment: Got new list of 0 comments
I/[main] PostFragment: Lifecycle 255846711: START
I/[main] PostFragment: Switching viewer state to false
I/[main] MediaView[2870194]: Should stop playing media
I/[main] ExoVideoPlayer: Stopping exo player now
I/[main] VideoMediaView: Stored current position 0
I/[main] PostFragment: Lifecycle 255846711: RESUME
W/FA: setCurrentScreen cannot be called with the same class and name
I/[main] PostFragment: Lifecycle 4163814: START
I/[main] PostFragment: Switching viewer state to false
I/[main] MediaView[2870143]: Should stop playing media
I/[main] PostFragment: Lifecycle 4163814: RESUME
W/FA: setCurrentScreen cannot be called with the same class and name
I/art: Compiler allocated 7MB to compile void android.widget.TextView.onMeasure(int, int)
I/Choreographer: Skipped 112 frames!  The application may be doing too much work on its main thread.
I/BufferQueue: [unnamed-29175-0](this:0x716c817800,id:0,api:0,p:-1,c:-1) BufferQueue core=(29175:com.pr0gramm.app.dev)
I/BufferQueueConsumer: [unnamed-29175-0](this:0x716c817800,id:0,api:0,p:-1,c:29175) connect(C): consumer=(29175:com.pr0gramm.app.dev) controlledByApp=true
I/BufferQueueConsumer: [unnamed-29175-0](this:0x716c817800,id:0,api:0,p:-1,c:29175) setConsumerName: unnamed-29175-0
                       [SurfaceTexture-0-29175-0](this:0x716c817800,id:0,api:0,p:-1,c:29175) setConsumerName: SurfaceTexture-0-29175-0
I/BufferQueueConsumer: [SurfaceTexture-0-29175-0](this:0x716c817800,id:0,api:0,p:-1,c:29175) setDefaultBufferSize: width=1080 height=360
I/GLConsumer: [SurfaceTexture-0-29175-0] attachToContext
I/[AsyncTask #2] Decoder: Decoder.decodeRegion(Rect(0, 0 - 1052, 1430), 1) called
I/[AsyncTask #3] Decoder: Decoder.decodeRegion(Rect(0, 2860 - 1052, 4291), 1) called
I/[AsyncTask #1] Decoder: Decoder.decodeRegion(Rect(0, 1430 - 1052, 2860), 1) called
I/[AsyncTask #2] FallbackRegionDecoder: Using fallback decoder com.pr0gramm.app.util.decoders.FallbackRegionDecoder@444abdf now.
I/art: Background sticky concurrent mark sweep GC freed 4780(370KB) AllocSpace objects, 1(2MB) LOS objects, 0% free, 33MB/33MB, paused 6.541ms total 98.229ms
I/art: Background partial concurrent mark sweep GC freed 1740(99KB) AllocSpace objects, 5(640KB) LOS objects, 10% free, 33MB/37MB, paused 3.647ms total 112.188ms
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
                   Chrome build fingerprint:
                   70.0.3538.110
                   353811052
                   ### ### ### ### ### ### ### ### ### ### ### ### ###
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 29371 (AsyncTask #1)
W/MALI: winsysp_window_buffer_get:2393: [MALI] warning, dequeueBuffer takes more than 300ms here. Total elapse time: 21690395
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'"

**Comment by mopsalarm** [comment]
Das sieht nach einem Problem mit deinem Android aus, nicht mit der App. Probiere es doch mal im Android Emulator, tritt der Fehler da auch auf?

**Comment by 0x2A** [comment]
Nein da tritt er tatsächlich nicht auf...weißt du eventuell wie ich feststellen kann was mit meinem Android nicht stimmt? Fatal signal 11 hilft ja nicht gerade viel...

**Comment by mopsalarm** [comment]
Ne, Sorry, das liegt außerhalb meines Bereiches. Dabei handelt es sich dann meist um Fehler in den Anpassungen der Hersteller oder Unzulänglichkeiten der Hardware oder Treiber.
