### ISSUE TITLE
Tag-Suche nicht schliessbar per 'X' Button

### ISSUE THREAD

**Issue by ezsnipes** [mopsalarm/Pr0#188]
Hallo,

mir ist eben etwas aufgefallen - nichts gravierendes aber dennoch nennenswert.

Nach dem oeffnen der Tag-Suche kann man diese nicht mehr mit einem klick auf den `X` Button schliessen.
Der `Pfeil zurueck` Button funktioniert dagegen einwandfrei.

Eine kurze darstellung ist im Anhang.
Das Handy bei dem der Fehler auftrat ist ein `Huawei P20 Lite` mit `Android 8.0.0` & `EMIUI 8.0.0`.

Falls ich noch etwas vergessen habe, bitte bescheid geben 👍 

![20190214_093344](https://user-images.githubusercontent.com/34411645/52774694-234f0e80-303e-11e9-8ce4-9eea2768b8ab.gif)

**Comment by mopsalarm** [comment]
Der x Button löscht die Eingabe.

**Comment by mopsalarm** [comment]
Und wieso ist der Hintergrund weiß?

**Comment by ezsnipes** [comment]
Oh okay, gut zu wissen.
Ich hatte es als schliessen option interpretiert.

Der weisse Hintergrund kommt von der Recording App die ich benutzt hatte, ist in 'echt' der dunkle Hintergrund wie er sein soll. (Denke mal encoding fehler beim recording oder so)

**Comment by mopsalarm** [comment]
:+1: danke
