### ISSUE TITLE
Wordbreak im Profil ohne Silbentrennung

### ISSUE THREAD

**Issue by ckanitz** [mopsalarm/Pr0#189]
![signal-attachment-2019-03-27-142152](https://user-images.githubusercontent.com/9444820/55079128-e134d600-509b-11e9-8dc1-218173370ac4.jpeg)

One Plus X
Android 9
Aktuellste Version der App
Schriftgröße im System ist erhöht (falls das hier Einfluss haben sollte)

**Comment by mopsalarm** [comment]
Unschön. Ja wahrscheinlich hat die erhöhte Schriftgröße damit was zu tun. Werde ich mir nachher anschauen.

**Comment by mopsalarm** [comment]
Gefixt
