### ISSUE TITLE
Automatische Bildskalierung

### ISSUE THREAD

**Issue by ComiR** [mopsalarm/Pr0#190]
Bei den aktuellen Pixelmonstern würde sich bei Hochlads eine automatische Skalierung übergroßer Bilder anbieten. Die seitenverhältniserhaltende Skalierung von Bildern > 20,25 MPx auf <= 20,25MPx wäre mMn vollkommen ausreichend.

Beispiel: Mate 20 Pro: 41,5 MPx - 7728px\*5368px wird herunterskaliert auf 5400px\*3750px. Berechnung trivial, überlasse ich dem Implementierenden ;)

**Comment by mopsalarm** [comment]
Verstehe das Problem nicht. Meinst du beim Hochladen? Da werden Bilder, die von der Dateigröße aus zu groß sind bereits automatisch (bzw mit Nachfrage) herunterskaliert. Oder meinst du etwas anderes?

**Comment by ComiR** [comment]
Hmm. Ist das nur wenn die Dateigröße zu groß ist? Dann besteht das Problem vermutlich nur dann, wenn zwar die Dateigröße passen würde, jedoch die Pixelanzahl (20,25 MPx) nicht. D.h. um bei obigem Beispiel zu bleiben, dass die Datei mit den unskalierten Abmessungen trotzdem nur <=10/20MB groß ist.

**Comment by mopsalarm** [comment]
Richtig. Das Limit von 20mp hatte ich nicht im Kopf. Das lässt sich einbauen.

**Comment by mopsalarm** [comment]
Gibt's in der aktuellen Beta. Nicht ganz so fancy, aber dürfte funktionieren.
