### ISSUE TITLE
Markierbarer Text beim Antworten auf Kommentare

### ISSUE THREAD

**Issue by holzmaster** [mopsalarm/Pr0#191]
Momentan kann man nur in der Kommentarübersicht Texte markieren. Wenn man auf einen antworten will, geht es dort nicht.

Ist wichtig für's Zitieren etc.

**Comment by mopsalarm** [comment]
Klingt nach einer Kleinigkeit die ich übersehen habe. Werde ich nachher nachpflegen.

**Comment by holzmaster** [comment]
Danke!
