### ISSUE TITLE
User mit Binde- oder Unterstrich im Namen werden in der Suche nicht gefunden + Profil kann nicht angezeigt werden.

### ISSUE THREAD

**Issue by RundesBalli** [mopsalarm/Pr0#193]
Wenn man versucht einen User mit _ (Unterstrich) oder - (Bindestrich) im Namen **per Direktlink** aufzurufen, dann werden nur die Uploads geladen, der Rest (Benisanzeige, Anzahl d. Kommentare/Uploads/Tags, Badges) fehlt komplett.
![Screenshot_20190507-135813](https://user-images.githubusercontent.com/46271553/57297774-cd37b780-70d0-11e9-893a-c4a6a1ccb3b4.jpg)

Wenn man versucht einen o.g. User **über die Suchfunktion** zu finden, dann wird nichts angezeigt:
![Screenshot_20190507-135532](https://user-images.githubusercontent.com/46271553/57297785-d88ae300-70d0-11e9-8da5-80c1ef56aa32.jpg)
![Screenshot_20190507-135544](https://user-images.githubusercontent.com/46271553/57297786-d88ae300-70d0-11e9-9a4a-d129aa5d4c3e.jpg)
![Screenshot_20190507-135604](https://user-images.githubusercontent.com/46271553/57297787-d88ae300-70d0-11e9-8bb3-6ac25abcea5a.jpg)

Das Problem konnte mit folgenden Usern reproduziert werden:
[Die_Quelle](https://pr0gramm.com/user/Die_Quelle)
[ange_](https://pr0gramm.com/user/ange_)
[icke-bgl](https://pr0gramm.com/user/icke-bgl)

Ich weiß leider nicht in welcher Datei die Suche der User stattfindet, sonst hätte ich eine PR erstellt.
Das korrekte Regex müsste lauten:
`/^[a-zA-Z0-9-_]{2,32}$/`

Viele Grüße
RB

Nachtrag:
Hier ist noch eine Liste von Usernamen, die ein - oder _ enthalten:
`ange_, benno_O, bunga_bunga, chu_, Cjs_3f, dafuq_, das_ike, da_rob, Death_On_Socks, Die_Quelle, Dj_DeS, dok_gonzo, Halb-Benis, icke-bgl, Luke_Skywanker, mvs_, omfg_ownz, Peter-Pan, Polly_Zist, psy_bootsvogel, Silentsbro_, the_fulk ,Titfck_McGee, Uncle_Dolan, Yu_Y3v0n`

Nachtrag 2:
Wenn man per Direktlink versucht solch einem User eine PN zu schreiben (/inbox/messages/Die_Quelle zum Beispiel), dann werden die Nachrichten normal geladen und alles funktioniert.

**Comment by NuGetHub** [comment]
Der reguläre Ausdruck findet sich hier:
https://github.com/mopsalarm/Pr0/blob/b50065a401098c342e62403fda81a9d6208230b9/app/src/main/java/com/pr0gramm/app/util/Linkify.kt#L29

**Comment by RundesBalli** [comment]
Danke an @NuGetHub für den Nachtrag.

Des Weiteren im Auftrag von @NLDev folgender Nachtrag:

![grafik](https://user-images.githubusercontent.com/46271553/57298839-6a93eb00-70d3-11e9-8e1b-54af2b19a087.png)

**Comment by NuGetHub** [comment]
> Danke an @NuGetHub für den Nachtrag.
> 
> Des Weiteren im Auftrag von @NLDev folgender Nachtrag:
> 
> ![grafik](https://user-images.githubusercontent.com/46271553/57298839-6a93eb00-70d3-11e9-8e1b-54af2b19a087.png)

Die RegEx dafür habe ich auch mal verlinkt.

**Comment by mopsalarm** [comment]
Nutzernamen dürfen keine Sonderzeichen enthalten, das ist richtig. Die oben genannten User sind eigentlich kaputt, die Namen wurden vergeben, bevor die Namen im Backend korrekt überprüft wurden. (ange_ hat user id 14). Den regulären Ausdruck werde ich deshalb auch nicht ändern, eigentlich müssten die User umbenannt werden.

**Comment by NLDev** [comment]
Naja aber die User existieren dennoch. Im Frontend werden sie ja auch korrekt angezeigt. Demnach ist es so gesehen also schon ein Fehler in der App, da API und Frontend kein Problem beim Anzeigen haben. Die User werden mit Sicherheit auch nicht umbenannt. Folglich wird es dann in der App fortlaufend Probleme bei solchen "speziellen" Usern geben, weshalb ich finde, dass das ein berechtigter Issue ist

**Comment by mopsalarm** [comment]
Wir werden die User wohl umbennen. Ist besser als ein Workaround in der App.
