### ISSUE TITLE
Kein zurück Button im Vollbildmodus

### ISSUE THREAD

**Issue by p47-6** [mopsalarm/Pr0#195]
Auf meinem OnePlus 7 pro wird die Navigationsleiste im Vollbildmodus ausgeblendet und man kommt nicht mehr zurück.

**Comment by mopsalarm** [comment]
Dann hast du den Vollbildmodus aktiviert in der App. Man kommt sehr wohl zurück, indem man von unten oder oben in den Bildschirm hinein wischt, das ist eine Standard Geste da auf Android.
