### ISSUE TITLE
Navigationsleiste bleibt transparent wenn Tastatur ausgefahren ist

### ISSUE THREAD

**Issue by RundesBalli** [mopsalarm/Pr0#197]
Wenn man die App öffnet und dann direkt oben die Suche öffnet, dann erscheint ja sofort die Tastatur. Die Navigationsleiste bleibt aber durchsichtig. Ich weiß nicht ob das bewusst so ist. Ist mMn auch nur ein kleiner Schönheitsfehler, wollte es aber mal erwähnt haben.

Verwendetes Handy: Huawei P8 lite 2017 (PRA-LX1)
OS: Android 8.0.0
Tastatur: SwiftKey
![Screenshot_20190708-155345](https://user-images.githubusercontent.com/46271553/60827498-a2411100-a1b0-11e9-9a81-6bbc6c5b07dc.jpg)

**Comment by mopsalarm** [comment]
Hmm, passiert auf meinem one plus auf Android 9 mit swiftkey nicht, im Android Emulator auch nicht. Kann es demnächst nochmal mit Android 8 probieren.

**Comment by mopsalarm** [comment]
Passiert auch auf dem Android 8 Emulator nicht. Wüsste jetzt nicht, was ich da machen sollte.

**Comment by RundesBalli** [comment]
Ok, ist auch nicht so schlimm. Danke fürs prüfen!
