### ISSUE TITLE
Tag kopieren

### ISSUE THREAD

**Issue by ckanitz** [mopsalarm/Pr0#201]
Gerade einen Ausschnitt eines Musikvideos gesehen. Da Soße nicht gegeben, wollte ich den Text eines Tags durch "gedrückt halten" kopieren (intuitiv). Leider gabs es kein Kontextmenü zum Text kopieren.

Wäre töfte, wenn das möglich wäre. Vll sogar mit google/youtube suchoption

**Comment by mopsalarm** [comment]
Das stimmt, lange drücken blendet die Vote Buttons ein, falls diese in den Einstellungen versteckt sind. Du hast aber recht, dass es intuitiv wäre, wenn sie dann kopiert werden würden.
