### ISSUE TITLE
Spiegeln der Post Up/Downvote Buttons

### ISSUE THREAD

**Issue by manuel2258** [mopsalarm/Pr0#202]
Es könnte eine Einstellung geben welche es erlaubt die Up/Downvote Buttons auf die rechte Seite zu bringen, wenn man einen Post anschaut. Das würde das Up/Downvoten für Leute die die App nur mit der rechten Hand bedienen um einiges vereinfachen, da diese dann nicht bei größeren Bildschirmen den Daumen über den ganzen Bildschirm strecken müssen.

**Comment by mopsalarm** [comment]
Das wird es vermutlich nicht geben.
