### ISSUE TITLE
Pop-up "Die Version der App ist ziemlich alt..." beim Appstart

### ISSUE THREAD

**Issue by ohsnap27** [mopsalarm/Pr0#207]
Environment:
Xiaomi 9T Pro
Android 10
MIUI 11.0.3

Description:
Bei jedem Appstart erscheint ein Pop-up mit dem Text "Die Version der App ist ziemlich alt. Bitte führe unbedingt ein Update durch, da die Version bald nicht mehr unterstützt wird! <Link-Pr0gramm>".
Verwendet wird der letzte Release "1.174.3"

**Comment by MrSteelMiner** [comment]
Kann ich so bestätigen. Huawei P30 Pro, Android 9
EMUI 9.1.0

**Comment by mopsalarm** [comment]
Ist das noch aktuell?

**Comment by MrSteelMiner** [comment]
Aktuell sehe ich die Meldung nicht mehr.
