### ISSUE TITLE
Menüpunkt "Credits" 

### ISSUE THREAD

**Issue by ChipsUndCola** [mopsalarm/Pr0#208]
Hey mopsi,
Erst mal danke für die Zeit die du hier reingesteckt hast. Respekt 👍

Genau um dir eben mal Danke zu sagen, hab ich vorhin in der App nach dem User gesucht, der für die App verantwortlich ist. Ich fänds gut, wenn im Menü im unteren Bereich oder irgendwo in den Einstellungen auch dein Username oder zumindest der Link zum Github in einem "Credits" Abschnitt enthalten ist.

**Comment by mopsalarm** [comment]
Na ja, dafür gibt es das Feedback-Formular. Da kannst du auch deinen dank reinschreiben, dann bekomme ich das auch.
