### ISSUE TITLE
Überspringen von mehreren Posts

### ISSUE THREAD

**Issue by hum6ug** [mopsalarm/Pr0#209]
Version: 1.175

Jedes mal beim exakt 51ten Swipe von links nach rechts werden mehrere Posts ganz schnell hintereinander übersprungen.

**Comment by mopsalarm** [comment]
Moin, ja, der Fehler ist mir bekannt, ich werde schauen, dass ich ihn heute gefixt bekomme.

**Comment by mopsalarm** [comment]
Sollte in der aktuellen Beta gefixt sein. Kannst du das bestätigen?

**Comment by hum6ug** [comment]
Ja. In der aktuellen Version ist der Fehler nicht mehr vorhanden.
