### ISSUE TITLE
Scrollverhalten in Hochlad-Detailansicht seltsam

### ISSUE THREAD

**Issue by Blenderpics** [mopsalarm/Pr0#210]
Seit einer Weile (kann es nicht an einer Version festmachen) ist das Scrollverhalten in der Detailansicht sehr seltsam.

Beim schnellen Swipen nach unten/oben, um innerhalb eines Hochlads hoch/runter zu scrollen, wird nun oft die rechts/links Geste ausgeführt und somit zum nächsten/vorherigen Hochlad navigiert.

Dabei swipe ich fast vertikal, vielleicht 15° Neigung.

**Comment by Blenderpics** [comment]
Möglicherweise relatiert zu https://github.com/mopsalarm/Pr0/commit/f8cdc01701770874e224f4a84a5e50ccd49e3f3b

**Comment by mopsalarm** [comment]
Der Commit musste es eigentlich besser gemacht haben. Vorher konnte man die Tags nicht ordentlich scrollen. Alternativ könntest du ja ein revert machen und gucken, ob das hilft. Wenn ich Zeit finde, schaue ich da mal weiter rein, kann mir vorstellen, dass das auch mehr mit dem ViewPager2 zu tun hat.

**Comment by mopsalarm** [comment]
Wir sind zurück zu ViewPager, sollte nun wieder besser sein.
