### ISSUE TITLE
Herunterladen funktioniert nicht 

### ISSUE THREAD

**Issue by Maroko** [mopsalarm/Pr0#212]
Wenn ich auf den download button drücke kommt zwar eine Benachrichtigung, dass das Bild/Video heruntergeladen wird, jedoch ohne Fortschritt. Das popup für den Datei Zugriff wurde bestätigt, sowie ein download Ordner in den Einstellungen gesetzt. 

Gerät: Xiaomi Mi 9T Pro
Android 10
MIUI 11.0.3
Pr0gramm 1.176.3

**Comment by mopsalarm** [comment]
Frisch auf Android 10 upgedatet?

**Comment by Maroko** [comment]
Ja.

**Comment by mopsalarm** [comment]
Ja, dann scheint es anscheinend Probleme zu geben, ich weiß allerdings nicht warum. Versuche einfach neuen Download Ordner auszuwählen.

**Comment by Maroko** [comment]
Zufällig den Kommentar gesehen, unbekannte Quellen zulassen und es funktioniert.
https://pr0gramm.com/new/3655263:comment35842886

**Comment by mopsalarm** [comment]
Das dürfte damit nicht zu tun haben, sondern daran liegen dass ich das in der aktuellen Beta neu umgebaut habe. Wenn doch, dann hat Xiaomi das noch mehr verkackt als normalerweise.
