### ISSUE TITLE
V1.178 Automatisches Hochscrollen bei Favoriten

### ISSUE THREAD

**Issue by stanbos0815** [mopsalarm/Pr0#213]
Servus,

in der neusten Version ist mir etwas aufgefallen. Falls man einen Favoriten aufruft und anschließend zurück antippt, landet man nicht wie vorher an die Stelle des gerade ausgewählten Favoriten, sondern wieder ganz oben in seinen Favoriten. Selbiges passiert z.B. bei der Wochenstatistik beim durchgehen der einzelnen Kategorien. Ansonsten kann ich nur sagen sehr gute Arbeit weiter so :)!

Beste Grüße
Stanbo0815

**Comment by mopsalarm** [comment]
Ist gefixt.
