### ISSUE TITLE
Android backward compatibility

### ISSUE THREAD

**Issue by Hero9909** [mopsalarm/Pr0#215]
Es besteht ja auch die möglichkeit statt den support komplett einzustellen den sourcecode für android 6 einzufrieren und die distribution von updates auf aab oder xapk (apkpure) oder ähliche umzustellen. Wobei die jeweilige app per intent mit einer datasource app zu versorgen. Dies trifft hier natürlich auf die bestehende struktur.

dies würde die jeweiligen android versionen länger am leben erhalten. Hingegen aber eine augenscheinlich große änderung bestehender strukturen bewirken.

**Comment by mopsalarm** [comment]
Das funktioniert aber nur so lange bis wir die nächsten API Änderungen machen. Die neuen Nachrichten zb sind bereits eingebaut, nachdem die Probleme mit Android 6 angefangen haben.

**Comment by Hero9909** [comment]
Dagegen könnte man in einem api src set arbeiten. Bei diesem fall währen änderungen und neuerungen jeh ab dem angegebenen api lvl erreichbar. Dadurch wüsste man mit welcher api man jeh api lvl arbeitet. Leider habe ich zuerst diesen vorschlag geschrieben bevor ich die app komplett lesen konnte. Ich würde versuchen gegen mittwoch einen weiter entwickelten vorschlag zu unterbreiten.

**Comment by Hero9909** [comment]
erstmal : wer rechtschreibfehler findet möge sie an den meist beietenden verkaufen. ich werde mich bemühen die rarität auf ein mir mögliches maximum zu erhalten.

tja es ist viel zeit ins land gegangen und ich hab mir viele gedanken dazu gemacht. leider hat mein letztes android 6 gerät die füße gestreckt. das würde zwar das testen erschweren aber nicht das denken, daher hier die struktur die dadurch entstanden ist:

Bei der der implementierung der nachrichten wäre zusätzlich nötig diese in api versionierte abschnitte zu unterteilen. z.b. von android 6-9 hat sich das post format 3 x so grundlegend geändert das von der 1. auf die 2. version kein anzeigen mehr möglich wäre da z.b. ein bildformat eingeführt wurde das bei android 6 nicht anzuzeigen währe. das heißt es würden posts geben die vom poll service durch ihre angaben an features von der anzeige ausgeschlossen werden könnten und ein dummy content anzeigen könnten. dadurch würden zwar die posts die für die nutzer der unteren api level sichbar währen mit der zeit weniger werden aber die bereitschaft der app währe weiter gewährleistet. das heißt die posts ( gillt natürlich auch für kommentare oder beliebige andere einträge die angezeit werden) und deren ersteller der objekte müssten über src-sets von android geregelt werden. dann würde der beispielsweise post als v21 , v26, v28 existieren und sich an der basisklasse orientieren.

doch es gibt überall und also auch hier nachteile. code mit api versionierung bedeutet deutlich mehr code in diesem projekt der zwar nicht dauerhaft gepflegt aber überblickt werden muss.

 als fazit kann ich hier leider nur ziehen das mehr als 6 api level kompatibilität den aufwand so leid es mir tut nicht rechtfertigt, zumindest für diese lösung.

was trotzdem möglich wäre ist eine ausgiebige api endpoint definition.
dies hilft bei dem fortführen dieser app und nebenläufigen tools für das pr0.

womit wir bei meinem letzten punkt währen den dynamic modules. diese biete in höheren android versionen angenehm die möglichkeit code zu installieren und dynamisch zu updaten. die dadurch entstehende modularität hilft bei wartbarkeit kompatibilität und übersicht. aber zu schön um gleich war zu sein. die dynamischen module sind ein part von google. aber die idee dahinter lässt sich verwenden. mit etwas aufwand den code in abgeschlossene module aufteilen und diese dann per maven oder ähnlicher tools einzubinden ist bei einer weit gewachsenen anwendung wie hier noch realistisch.

daher führt leider kein weg daran vorbei hier die entscheidung zu beginnen, wo es hin gehen soll. daher die frage, wie seht ihr / du das?

**Comment by mopsalarm** [comment]
Tut mir leid, was du da schreibst ist großteils wirres Gerede ohne echten Bezug zur Realität. Sicher, man kann viel machen, man kann gucken, dass man versucht kompatibel mit alten App Versionen zu bleiben, aber warum? Am Ende nutzen vielleicht ein paar dutzend User eine uralte Version der App, weil sie keine 100 Euro für ein neues Telefon ausgeben wollen? Ist mir egal. Der Aufwand, den ich darein stecken müsste, steht dazu leider überhaupt nicht im Verhältnis. Vergiss nicht, dass ich das ganze in meiner ohnehin rah gesähten Freizeit mache.
