### ISSUE TITLE
Lizenz?

### ISSUE THREAD

**Issue by ReneHollander** [mopsalarm/Pr0#22]
Unter welcher Lizenz steht der Source Code?

**Comment by mopsalarm** [comment]
Gute Frage. Kenne mich da nicht so richtig aus. Falls du da mehr Ahnung hast. spricht was gegen die Apache 2.0?

**Comment by ReneHollander** [comment]
Was die Apache 2.0 genau kann weis ich nicht. Am einfachsten wäre wahrscheinlich eine Simplified BSD oder MIT (Kann jeder verändern, machen was er will, auch verkaufen und änderungen unter andere Lizenz stellen, glaube ich). Oder eine GPL mit Copyleft (Lizenz muss beibehalten werden, alle änderungen müssen Open Source sein)

Ich verwende meist die MIT da sie kurz und einfach ist.

**Comment by Graphicscore** [comment]
Also ich wäre für Creative Commons Attribution NonCommercial (CC-BY-NC)

https://tldrlegal.com/license/creative-commons-attribution-noncommercial-(cc-nc)

**Comment by mopsalarm** [comment]
Die CC Lizenzen sind glaube ich nicht für Software, oder? Habe jetzt MIT genommen.
