### ISSUE TITLE
Neuladen nach Suche (Fehler 404)

### ISSUE THREAD

**Issue by TheMasterMaind** [mopsalarm/Pr0#220]
Hallo!

Sucht man in der Pr0gramm-App nach einem Suchbegriff (z.B. "Crackfurt") und aktualisiert die Suche (Finger nach unten wischen) erhält man die Fehlermeldung:

Die angefragte Resource konnte nicht gefunden werden (Fehler 404).

Der Fehler scheint bei anderen getesteten Suchbegriffen nicht aufzutauchen. Vermutlich müsste dazu in den Suchergebnissen ein gelöschter Post enthalten sein um den Fehler zu provozieren.

**Comment by mopsalarm** [comment]
Das Problem ist bekannt. Ich werde mir das demnächst mal genauer angucken.

**Comment by mopsalarm** [comment]
Ist inzwischen gefixt. Update kommt auch bald.
