### ISSUE TITLE
Kein automatisches Scrollen in privaten Nachrichten nach Absenden einer Nachricht

### ISSUE THREAD

**Issue by RundesBalli** [mopsalarm/Pr0#221]
Wenn man eine PN abgeschickt hat, dann wird nicht mehr zu der PN gescrollt, sondern es bleibt beim letzten Scrollzustand stehen.

Hier habe ich es getestet auf einem `Huawei P8 Lite 2017`.

**Ursprungszustand nach Klicken auf das Briefsymbol auf einem Profil:**
![grafik](https://user-images.githubusercontent.com/46271553/84830519-ca282e00-b029-11ea-9d79-a617c6e49c7b.png)

**Tastatur geöffnet:**
![grafik](https://user-images.githubusercontent.com/46271553/84830540-d44a2c80-b029-11ea-9c6f-9f33baabe2ba.png)

**Text geschrieben:**
![grafik](https://user-images.githubusercontent.com/46271553/84830564-dca26780-b029-11ea-9ba9-7c5e0115c936.png)

**Text gesendet. Tastatur schließt sich. Textfeld scrollt nicht nach:**
![grafik](https://user-images.githubusercontent.com/46271553/84830587-edeb7400-b029-11ea-8460-9267970501fb.png)

**So würde es nachgescrollt aussehen:**
![grafik](https://user-images.githubusercontent.com/46271553/84830601-f774dc00-b029-11ea-89ee-4d48f234745d.png)

**Comment by KAR0TTENP0WER** [comment]
Wäre auch schöner, wenn es die Scroll Funktion wie auf Youtube gibt. Bild/Video ist zu jeder Zeit sichtbar, man kann allerdings durch die Kommentare lesen

**Comment by mopsalarm** [comment]
@KAR0TTENP0WER nein, macht keinen Sinn. Bei Youtube sind fast alle Videos 16/9, bei uns sind viele Videos auch einfach hochkant, oder gar noch extremer. Dann siehst du nichts mehr von deinen Kommentaren.

**Comment by DryZ9077** [comment]
@RundesBalli Welche Android Version verwendest du denn?

**Comment by RundesBalli** [comment]
@DryZ9077 weiß ich jetzt nicht mehr welche das war. Habe inzwischen ein neues Handy.

Aber das Problem wurde auch gefixt.
