### ISSUE TITLE
Schwarze Seite

### ISSUE THREAD

**Issue by hanswurstgmbh** [mopsalarm/Pr0#227]
Ich bin auf top, klicke ein Bild an, klicke danach auf einen Benutzer, gehe einen Schritt zurück und der vorherige Post ist nur noch schwarz. Die Überschrift ist weiterhin der erste Tag, aber der restliche Inhalt fehlt. Gehe ich nun einen Schritt weiter zurück bin ich wieder in der top Übersicht. Danach kann ich den Post wieder normal aufrufen. 
Android 10, OP 7 pro. 

Ich kann auch ein Video davon machen.
Ich hoffe man kann verstehen wie der Fehler reproduzierbar ist.

**Comment by mopsalarm** [comment]
Bitte updaten.
