### ISSUE TITLE
Kommentare wieder ausklappen

### ISSUE THREAD

**Issue by knurtz** [mopsalarm/Pr0#228]
Vielen Dank für das Feature, Kommentarketten einklappen zu können! Das hab ich mir lange gewünscht.
In der aktuellen Version fehlt noch eine entsprechende Option, um eingeklappte Kommentare auch wieder auszuklappen.

**Comment by mopsalarm** [comment]
Hast du gefunden, ja?

**Comment by knurtz** [comment]
Jap, upps :|
Damit das hier nicht zum "Habs selbst rausgefunden, danke"-Thread ohne Lösung wird: Einfach auf das Icon "+x" tippen.
