### ISSUE TITLE
Moderatoren Farbe ändern

### ISSUE THREAD

**Issue by Graphicscore** [mopsalarm/Pr0#23]
Moderatoren haben eine seltsame Farbe.

/src/main/res/drawable/user_type_moderator_small.xml

Aktuelle Farbe : 

#6c832b
![6c832b](https://cloud.githubusercontent.com/assets/5658012/6766797/e6b84636-d014-11e4-813e-7a69a9801c6a.png)

Gewünschte Farbe :

#008FFF
![008fff](https://cloud.githubusercontent.com/assets/5658012/6766799/ea7f882e-d014-11e4-8276-2d9823dd9870.png)

![screenshot_2015-03-21-21-47-43](https://cloud.githubusercontent.com/assets/5658012/6766772/5c9b7932-d014-11e4-9e55-518e4f8d7588.png)

**Comment by mopsalarm** [comment]
Danke, gefixt!
