### ISSUE TITLE
Login im Querformat nicht möglich

### ISSUE THREAD

**Issue by huellif** [mopsalarm/Pr0#231]
Hallo,

mein Android-Autoradio ist im Querformat und leider ist die Login-Seite in der App zu "Hoch" und bietet keine Scrollmöglichkeit an.
Daher kann ich mich in der App nicht anmelden.
Wäre es möglich die Seite scrollbar zu machen?

Beste Grüße,
huellif

**Comment by mopsalarm** [comment]
Es gab mal ein extra Layout für Querformat. Muss ich mir angucken, bist aber der erste, der sich seit fünf Jahren deswegen meldet. Dreh bitte einfach solange dein Telefon.

**Comment by huellif** [comment]
Es ist ein Autoradio mit Android 6, welches fest im Querformat ist, drehen wird da schwer :)
Wäre cool wenn die Seite einfach scrollbar wäre,

**Comment by huellif** [comment]
> Würde das ganze Auto drehen. Wär interessant, ob der Hersteller einen Sensor dafür eingebaut hat.

Hab die Karre heute extra in den Graben geschmissen, leider ohne Erfolg.
