### ISSUE TITLE
Einige Videos rebooten das Smartphone

### ISSUE THREAD

**Issue by ChickenMcFriend** [mopsalarm/Pr0#232]
Bug ist reproduzierbar und habe mit meinem Handy(Galaxy A41) keinerlei ähnliche Probleme in anderen Apps.
Beispiel eines videos(mp4), welches zum reboot führt:
https://pr0gramm.com/new/4376277

**Comment by mrmaffen** [comment]
Wenn das Smartphone rebootet, versagt das OS, nicht die App.
