### ISSUE TITLE
App Crasht beim öffnen. Fehlerloop sichtbar in anderen Apps

### ISSUE THREAD

**Issue by SteffTek** [mopsalarm/Pr0#233]
Seit heute Morgen (23.03) crasht die App beim öffnen. Während der Nutzung anderer Apps (Bsp. YouTube) ist mir dann aufgefallen, dass ich permanent Fehlermeldungen für eine nicht reagierende App bekomme, die aber sofort wieder verschwinden.

Cache leeren, Beenden erzwingen und Neustart helfen nicht.

Endgerät
- OnePlus 8 Pro
- Android 11
- Latest Sec Update

Wenn ich die möglichkeit habe, versuche ich heut Abend mal das Handy an die ADB anzuhängen und nen Fehlerlog rauszufiltern.

**Was ein scheiß morgen ohne das >_ (in der App)**

**Comment by SteffTek** [comment]
Eine neue Entwicklung:

Nach löschen des Speichers lässt es sich wieder öffnen und sogar anmelden. Aber sobald man die App einmal schließt hat's sich wieder und es crasht weiterhin. Mindestens eine Person ist noch betroffen.

**Comment by SteffTek** [comment]
Problem gefunden: https://stadt-bremerhaven.de/android-webview-fehler-laesst-apps-abstuerzen/

Google Android WebView der Hurensohn.
![index](https://user-images.githubusercontent.com/5563452/112103451-0fc1ea80-8baa-11eb-9906-0c387de3506d.jpeg)

**Comment by SteffTek** [comment]
pr0 Post zu meiner Lösung: https://pr0gramm.com/top/4460914

Ich close dann mal, war nett hier, aber waren sie schonmal in Baden Württemberg?

**Comment by mopsalarm** [comment]
Good job!
