### ISSUE TITLE
Scrollen öffnet random posts

### ISSUE THREAD

**Issue by Goreaction** [mopsalarm/Pr0#234]
Moin,

hab auf meinem Smartphone ein Problem mit dem scrollen. 
Zur Veranschaulichung mal ein video.

https://im3.ezgif.com/tmp/ezgif-3-7f317671aca2.mp4

Infos:
Pixel 5
Android 11
aktuellste pr0 Version

**Comment by mopsalarm** [comment]
Das ist ein Problem mit pixel Telefonen. Google hat vor nem Jahr oder so fake force Touch eingebaut. Das Feature mit der Vorschau kannst du in der App deaktivieren.
