### ISSUE TITLE
Pr0gramm Logo und leiste brennt sich im Display ein

### ISSUE THREAD

**Issue by MrMicrob88** [mopsalarm/Pr0#235]
Hallo,
Bei meinem alten Handy (Galaxy S8) hat sich durch eine "Vielnutzung" die obere Leiste der App in mein OLED Display eingebrannt. Gibt es eine Möglichkeit diese Ausblenden zu lassen?

Sonst ist die App super.

**Comment by CrytectX** [comment]
Nunja, ich kenne das von meinem S4, S6 und S2. Eigentlich gibt es Apps die flashen dann so farben hin und her, musst halt anschliessen und über die Nacht laufen lassen, es hilft allerdings nicht viel. Ich würde ein neues Display kaufen und selber einbauen, die kosten nicht mehr so viel.
________________________________
Von: MrMicrob88 ***@***.***>
Gesendet: Freitag, 21. Mai 2021 15:13
An: mopsalarm/Pr0 ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [mopsalarm/Pr0] Pr0gramm Logo und leiste brennt sich im Display ein (#235)


Hallo,
Bei meinem alten Handy (Galaxy S8) hat sich durch eine "Vielnutzung" die obere Leiste der App in mein OLED Display eingebrannt. Gibt es eine Möglichkeit diese Ausblenden zu lassen?

Sonst ist die App super.
