### ISSUE TITLE
Farben mancher Bilder werden negativ dargestellt

### ISSUE THREAD

**Issue by arndttob** [mopsalarm/Pr0#239]
Beim Öffnen mancher Bilder wird nur kurzfristig (ca. 0,5 Sekunden) das Bild korrekt dargestellt. Danach werden alle Farben ins Negativ geändert. Es lässt sich weder durch das Aktualisieren, noch durch das Zurückgehen in die Übersicht und erneut Öffnen beheben. Das Problem bleibt persistent. Bisher habe ich das Verhalten nur bei Schwarz/Weiss-Bildern bemerkt.

App-Version: 1.192

Falsche Darstellung in der App:
<img src="https://user-images.githubusercontent.com/6782989/129204971-440695f5-aadd-4679-84b8-9d2da31da63e.jpg" width="500">
Richtige Darstellung im Browser:
<img src="https://user-images.githubusercontent.com/6782989/129205025-f5e94309-a059-4462-a40f-6d130ca7acac.jpg" width="500">

**Comment by fstanzk** [comment]
Liegt am Dark-Mode deaktivieren Mal den Darkmode für Pr0, dann sollte es gehen.

**Comment by arndttob** [comment]
Leider ist das Verhalten seit Kurzem wieder aufgetaucht.
