### ISSUE TITLE
App startet nichtmehr

### ISSUE THREAD

**Issue by Cursedradiance** [mopsalarm/Pr0#240]
App will nicht mehr starten. Geht auf und schließt sich wieder.

Gerät : Huawei p40 pro
Emui 11. 0.0
Build 11.0.0.196

**Comment by mopsalarm** [comment]
Bisschen mehr Info. Welche Version?

**Comment by Cursedradiance** [comment]
Hab die app gelöscht und komplett neu installiert. Neueste app version von hier.

**Comment by mopsalarm** [comment]
Dann brauche ich ein logcat

**Comment by Cursedradiance** [comment]
wie geb ich dir diesen logcat?

**Comment by mopsalarm** [comment]
Am besten am PC erstellen und dann als gist hochladen.

**Comment by Cursedradiance** [comment]
sorry hab davon keine ahnung. weiß nicht was das ist und wie ich sowas erstelle :/
