### ISSUE TITLE
Herunterladen ohne Google Files schlägt fehl

### ISSUE THREAD

**Issue by paddelb** [mopsalarm/Pr0#242]
Hallo,

Ich benutze ein entgoogletes Android 11. Wenn ich nun versuche ein Bild herunterzuladen kommt die Error Message: "No file manager available to select a directory".
Ich habe es sowohl mit der App "[Material Files](https://github.com/zhanghai/MaterialFiles)" sowie "[Simple File Manager](https://github.com/SimpleMobileTools/Simple-File-Manager)" probiert. Beide werden scheinbar von der App nicht unterstützt. 

Bei Infinity for reddit ist ein Download Manager schon in die App miteingebaut. Hier funktionieren die Downloads scheinbar ohne die Abhängigkeit eines Datei Managers. 

- Smartphone: Xiaomi Redmi 9
- OS: Android 11 mit MIUI
- Latest pr0gramm release

**Comment by mopsalarm** [comment]
Welche Version der App nutzt du?

**Comment by paddelb** [comment]
Version 1.191.5 

Check for updates sagt ich bin auf latest. Soll ich die Beta probieren?

**Comment by mopsalarm** [comment]
Ja.

**Comment by paddelb** [comment]
Bin jetzt auf 1.191.8 und habe das Schlaufon rebooted zur Sicherheit.

Immer noch derselbe Fehler.

**Comment by mopsalarm** [comment]
Habe gerade den Code geprüft. Ich stelle da keine besondere Anforderung an eine spezielle App. Ich frage nur danach, dass ich einen Pfad im Filesystem auswählen kann. Sieht so aus als würde das von den oben genannten Apps nicht unterstützt werden. Ich kann da leider nichts machen, das liegt nun an deinem Telefon.
