### ISSUE TITLE
Feature Request: Mehrere Download-Ordner

### ISSUE THREAD

**Issue by MaxMatti** [mopsalarm/Pr0#244]
Hi, ich würde gerne 4 Download-Ordner einstellen können: Für SFW, NSFP, NSFW und NSFL separat. Oder auch einfach nur diese 4 Unterordner im Haupt-Download-Ordner, das wäre auch super.

**Comment by mopsalarm** [comment]
Sorry, abgelehnt.

**Comment by mopsalarm** [comment]
Wenn das jemand einbauen möchte, gerne.
