### ISSUE TITLE
Android 11 macht alles Groß

### ISSUE THREAD

**Issue by tedzards509** [mopsalarm/Pr0#246]
Punkte und noch nicht gezeigter Benis sind plötzlich mit meinem Android 11 Update fett geworden

![Screenshot_20211010-185534](https://user-images.githubusercontent.com/37296713/136705848-65db453b-488c-4104-a5a0-40836a261d97.jpg)

Es tut mir ausdrücklich Leid wenn das so soll oder man nichts dagegen tun kann

**Comment by mopsalarm** [comment]
Das ist abhängig von der verwendet Schriftart.
