### ISSUE TITLE
SSL Handler

### ISSUE THREAD

**Issue by UserTotheMoon2** [mopsalarm/Pr0#249]
Fehlermeldung SSL Handschlag konnte nicht durchgeführt werden, tritt auf im Hotel WLAN, trotz aktiviertem vpn "nach Hause".

**Comment by mopsalarm** [comment]
Vermutlich verwendest du nicht den dns über VPN, sondern weiterhin vom Hotel. Oder die pr0gramm App geht nicht wirklich über dein VPN. Sonst würde es gehen.
