### ISSUE TITLE
In-App Links

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#25]
In-App Links zu anderen pr0gramm-Seiten sollen auch innerhalb der App aufgelöst werden.

**Comment by schr3j** [comment]
Über Intent-Filter können doch bestimmte URLs an Apps weitergeleitet werden. Würden wir das impelemtieren würden nicht nur interne Links in der App aufgelöst sondern auch pr0 links in anderen Apps an die pr0 App weitergeleitet werden...

Github sagt:
```xml
<intent-filter>
  <action android:name="android.intent.action.VIEW"></action>
  <category android:name="android.intent.category.DEFAULT"></category>
  <category android:name="android.intent.category.BROWSABLE"></category>
  <data android:host="pr0gramm.com" android:scheme="http"></data>
</intent-filter>
```

**Comment by schr3j** [comment]
Ich hab das mal ausprobiert.
Links werden geparst jedoch bekomme ich das Anzeigen nicht hin.
schr3j/Pr0@1841b32dd9f6ee93264ccd20426ab4936fa6fa46

**Comment by mopsalarm** [comment]
Sehr gut. Zieh das doch mal in eine Funktion raus, die eine Instanz der Query-Klasse erzeugt und an ihr "start" und "feedType" setzt. Damit kannst du dann gotoFeed aufrufen, dann sollte immerhin schon mal ein Feed geöffnet werden, der die entsprechenden Elemente enthält. 
Zum parsen würde ich sonst auch einen oder mehrere l reguläre Ausdrücke verwenden.

**Comment by schr3j** [comment]
Ich seh in der Query-Klasse nur feedType, tags, likes und content typ.

Warum würdest du hier RegEx verwenden wo doch die uri Funktion die Möglichkeit bietet den Pfad in seine Einzelteile aufzudröseln? (Ich hab RegEx eigentlich noch nie richtig verwendendet)

**Comment by mopsalarm** [comment]
Ich hatte nur kurz drauf geguckt, aber es sah so aus als könnte die id an unterschiedlichen stellen stehen.

Zu dem Start: das stimmt. Dann muss es noch ne Möglichkeit geben das Feed Fragment mit einem optionalen start-parameter zu öffnen. Und wenn der gesetzt ist, kann es das entsprechende PostPagerFragment danach direkt initialisieren. 

Traust du dir das zu in die Richtung einfach mal was auszuprobieren?

**Comment by schr3j** [comment]
Probieren werde ich es auf jeden Fall...

**Comment by mopsalarm** [comment]
Kannst mal gucken, ich habe ein paar Änderungen gemacht und Query aufgeräumt und in FeedFilter umgenannt.

**Comment by mopsalarm** [comment]
Wie schauts aus? Sonst würde ich heute abend mal selbst gucken?
