### ISSUE TITLE
version 1.194 - Gifs broken on Samsung

### ISSUE THREAD

**Issue by shrekk** [mopsalarm/Pr0#250]
seit der aktuellen beta sind bei mir die Gifs kaputt. Es wird für ne 10tel Sekunde das Thumbnail angezeigt, danach nur noch schwarz.

mfg shrekk

**Comment by shrekk** [comment]
Samsung S21, Android 12

**Comment by mopsalarm** [comment]
Hast du das Problem noch? Würde das auf allen Samsung Geräten nicht gehen, wäre der Aufschrei vermutlich größer. Ich schließe das Issue hiermit erstmal.

**Comment by shrekk** [comment]
noe alles gut seit einigen updates
