### ISSUE TITLE
Crashes beim Verwenden des Ausweichservers

### ISSUE THREAD

**Issue by HayateLaTech** [mopsalarm/Pr0#253]
Gerät : Pixel 4a (5G) Android 12

Die App crashed random wenn ich den Ausweichserver aktiviere und darüber durch Post-Ansichten swipe und gleichzeitig parralel downloade.

Ich versuche mal irgendwie ein Logcat zu erstellen ^^

Wenn ich den normalen Server verwende crashed es bei gleicher Verwendung nicht.

**Comment by mopsalarm** [comment]
Alternativ nach einem crash mal die Feedback Funktion verwenden, mit Glück bekomme ich dann ein log.

**Comment by HayateLaTech** [comment]
Okay, ich habs endlich geschafft über `adb logcat` mal was hoffentlich brauchbares herauszufinden xD

> 05-25 02:16:04.078  2653  2653 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|com.pr0gramm.app|10016|com.pr0gramm.app.DOWNLOAD|10330
05-25 02:16:04.078  2653  2653 D InterruptionStateProvider: No heads up: unimportant notification: 0|com.pr0gramm.app|10016|com.pr0gramm.app.DOWNLOAD|10330
05-25 02:16:04.079  2653  2731 D PeopleSpaceWidgetMgr: Sbn doesn't contain valid PeopleTileKey: null/0/com.pr0gramm.app

> 05-25 02:16:05.164   656   656 I lowmemorykiller: Kill 'com.pr0gramm.app' (15886), uid 10330, oom_score_adj 0 to free 2253700kB rss, 1358228kB swap; reason: device is low on swap (0kB < 209712kB) and thrashing (206%)

> 05-25 02:16:05.829  1906  2271 W WindowManager: Failed to deliver inset state change to w=Window{21062ab u0 com.pr0gramm.app/com.pr0gramm.app.ui.MainActivity}
05-25 02:16:05.829  1906  2271 W WindowManager: android.os.DeadObjectException
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.os.BinderProxy.transactNative(Native Method)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.os.BinderProxy.transact(BinderProxy.java:571)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:687)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4037)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$6$InsetsStateController(InsetsStateController.java:552)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda1.run(Unknown Source:2)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(WindowAnimator.java:106)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda0.doFrame(Unknown Source:2)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.view.Choreographer.doCallbacks(Choreographer.java:845)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.view.Choreographer.doFrame(Choreographer.java:775)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.os.Handler.handleCallback(Handler.java:938)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:99)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.os.Looper.loopOnce(Looper.java:201)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.os.Looper.loop(Looper.java:288)
05-25 02:16:05.829  1906  2271 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:67)
05-25 02:16:05.829  1906  2271 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:44)

**Comment by mopsalarm** [comment]
Der Speicher deines Gerätes ist voll und das Telefon killt Apps, um wieder etwas RAM frei zu machen.

**Comment by HayateLaTech** [comment]
ah oki x3
