### ISSUE TITLE
Feature-Request: "Nutzer kann keine PNs empfangen"

### ISSUE THREAD

**Issue by holzmaster** [mopsalarm/Pr0#256]
Seit kurzem gibt's (primär bei Bots) die Einstellung, dass ein Nutzer keine PNs empfangen kann.

Beispiel:
https://pr0gramm.com/inbox/messages/kellertreff

Der Text ist hier abhängig davon, ob es sich um einen Bot handelt. Es wird angezeigt:
```
XXX ist ein Bot, der keine Nachrichten empfangen kann.
```
Bei normalen Usern:
```
XXX kann keine Nachrichten empfangen.
```

Außerdem wird im Frontend bei den entsprechenden Profilen der PN-Button ausgeblendet.

**Comment by twobiers** [comment]
Ich würde mir das mal anschauen.
