### ISSUE TITLE
Feature-Request: Improved benis filter for the search

### ISSUE THREAD

**Issue by ngoedde** [mopsalarm/Pr0#260]
**Background:**
It is currently impossible to filter posts > 0 and < 100.  The filter starts with "egal" and continues with "100". 
That means that it's impossible to see every post with positive benis, because 0-100 is missing.

**Possible fix:**
Add the option "Minimaler Benis: > 0" and "Minimaler Benis: < 0" (for those who like shitty posts) or simply replace the slider with a number input

**Comment by mopsalarm** [comment]
Du kannst nach `! s:0`  für größer null und `! -s:0` für kleiner null suchen.

**Comment by ngoedde** [comment]
@mopsalarm 
Es geht hierbei eher um das entsprechende UI-Element, das ja schon vorhanden ist. Die Filter sind etwas "unbequem". Ich wollte es hier nur mal einkippen, kann verstehen, dass es nicht so wichtig ist, wenn es einen workaround gibt.
