### ISSUE TITLE
Verifizierungslinks werden von der App geöffnet und diese kann damit nichts anfangen

### ISSUE THREAD

**Issue by G4m813R** [mopsalarm/Pr0#261]
Link:
https://pr0gramm.com/user/%user%/validate/%token%

Der Link zur Verifizierung der E-Mail Adresse wird beim Klick auf einem Android Gerät von der App geöffnet und dann offenbar nicht ausgeführt.

**Comment by mopsalarm** [comment]
Jo. Um was für links handelt es sich da bzw was sollte passieren?

**Comment by G4m813R** [comment]
Entweder den Request dazu von der App ausführen lassen, so dass die Verifizierung funktioniert. Oder die App ignoriert solche URLs und lässt es den Browser öffnen. Was halt einfacher ist.

**Comment by mopsalarm** [comment]
Ich dachte eher an "welcher request. Welche URL, welche payload. Dann bau ich das nachher schnell ein.

**Comment by G4m813R** [comment]
Ich ginge von aus das du über den Link oben das direkt selbst in der API siehst.
user->validate und als einziger Parameter $_POST['token']

**Comment by mopsalarm** [comment]
Ich schau nachher mal

**Comment by mopsalarm** [comment]
Lieber spät als nie.
