### ISSUE TITLE
Bilder und Videos anpassen auf Display

### ISSUE THREAD

**Issue by novus84** [mopsalarm/Pr0#263]
Hallo! erstmal ein Lob zu dieser tollen App. 

Gibt es eine Möglichkeit in dieser App die Videos und Bilder an die Bildschirmgröße anzupassen?
Auf dem außeren Display des Galaxy Folds 4 passt alles. Innen muss ich bei vielen Videos (hochcunt) und Bildern leider scrollen. Dies macht die Sache etwas unübersichtlich. 

Oder kann ich dies sogar jetzt schon einstellen? 
Wäre über eure Hilfe sehr dankbar.

**Comment by mopsalarm** [comment]
Das gab es damals mal als "Tablet Modus", wurde aber so gut wie nicht genutzt, ist deswegen irgendwann rausgeflogen.
