### ISSUE TITLE
in top/neu öffnen Menü auch ohne Suche 

### ISSUE THREAD

**Issue by capitano799** [mopsalarm/Pr0#266]
Moin, ich habe einen kleinen Verbesserungsvorschlag.
Wenn man etwas sucht ist es möglich oben links im Menü zwischen Top und Neu zu wechseln, ohne Suche befindet sich an der Stelle jedoch der Vorladen Knopf, auf den ich so häufiger ausversehen drücke.
Wäre es möglich auch ohne Suche diesen Top/Neu Wechsel in dem Menü zu haben?

**Comment by mopsalarm** [comment]
Nein. Wenn du ohne Suche wechseln möchtest, kannst du links das Menü aufziehen und einfach wechseln.
