### ISSUE TITLE
Feature Request: Neues Suchverhalten auf Nutzerprofilen konfigurierbar machen

### ISSUE THREAD

**Issue by JohnnyKarate2** [mopsalarm/Pr0#271]
Hi, seit dem letzten Update sucht man automatisch in den Hochlads der Nutzer wenn man sich auf seinem Profil befindet.
Ich sag nicht dass dieses Feature nicht gut ist und kein Sinn macht, aber ich würde es gerne deaktivieren können und das alte Verhalten wieder herstellen.
Seit dem Update kommt es immer wieder vor, dass ich global etwas suchen will, aber gerade auf einem Nutzerprofil bin und dann erstmal zurück navigieren muss, ist ein bisschen nervig so.

Können wir dafür eine Konfiguration in den Einstellungen bekommen?

Danke und Grüße

**Comment by RundesBalli** [comment]
Alternativ einfach das Seitenmenü öffnen und Neu öffnen.

**Comment by JohnnyKarate2** [comment]
Hey, das geht natürlich auch, bzw. ich kann von einem Profil zurück navigieren. Sollte ich das Seitenmenü per Swipe öffnen können? Wenn ja dann funktioniert das bei mir schonmal nicht weil das die Zurück-Geste ist.
Ja im Idealfall ist es dann nur ein extra Klick, aber wenn ich z.B. mir Hochlads eines Nutzers anschaue und dort in Kommentaren wiederum auf andere Nutzer navigieren, dann muss ich plötzlich durch den ganzen Navigationstack zurück um wieder auf neu zu kommen, bzw. das Seitenmenü öffnen zu können.
Vorher konnte ich wenigstens von überall direkt neu durchsuchen.

Verstehe aber auch wenn das jetzt nicht unbedingt was ist wo ihr Zeit rein stecken könnt, weil es wahrscheinlich auch nicht viele Nutzer betrifft.

Nehmt ihr denn PRs an? Dann könnte ich nämlich einen stellen wenn ich mal Zeit habe demnächst.

**Comment by RundesBalli** [comment]
Also ich kann das Menü aufswipen. Deshalb dachte ich, dass das problemlos so gehen würde.

**Comment by JohnnyKarate2** [comment]
Ja an sich geht das natürlich, aber auf meinem Gerät ist das swipen vom Bildschirmrand die Zurück-Geste, deshalb funktioniert es nicht.
Und ich nutze die App gerne so dass ich über Profile der Leute gehe und zwischendurch auch was suche.
Seit dem Update ist die Benutzung halt so nicht mehr möglich, selbst wenn ich das Menü öffnen und auf neu gehen könnte habe ich damit auch wahrscheinlich meinen NavigationStack verloren oder? Vorher konnte ich nach einer Suche wieder zurück navigieren und weiter machen wo ich aufgehört hatte.

**Comment by RundesBalli** [comment]
Wenn du die Möglichkeit hast eine PR zu erstellen, dann mach das doch darüber. Ich denke Mopsalarm wird sich das ansehen.

**Comment by JohnnyKarate2** [comment]
Jup, wenn ihr nichts dagegen habt, dann kann ich das machen, sobald ich mal dazu komme.

Habt ihr irgendwo eine readme/guidelines für contributors? Finde dazu nichts in der Repo.

**Comment by mopsalarm** [comment]
1. Du kannst die Navigation an der Seite öffnen. Wenn wischen die Zurück Geste ist, dann kannst du für einen kurzen Moment an der Bildschirmkante drücken, bis das Menü etwa heraus springt, und danach das Menü wie gewohnt herausziehen.
2. Bevor du einen pull request machst: Was ist denn dein Lösungsvorschlag?

**Comment by JohnnyKarate2** [comment]
Hi mopsalarm, danke für die Antwort
1. stimmt, habe es gerade mal getestet und das funktioniert, aber nicht besonders "gut", manchmal kommt dann doch die Zurück-Geste und ist einfach nicht schön zu benutzen. Außerdem löst das nicht das Problem dass ich dann den NavigationStack verliere.
2. Mein Lösungsvorschlag wäre unter Einstellungen -> Verhalten eine neue Option hinzuzufügen, mit der man das alte Verhalten wiederherstellen kann. Also dass man beim Suchen auf einem Benutzerprofil "ganz normal" sucht und nicht nach dem Nutzer gefiltert.

**Comment by mopsalarm** [comment]
Abgelehnt, das ist dann eine extra Option die vermutlich nur du nutzen wirst, und sonst niemand. Wir müssen die dann aber immer Mit pflegen. Solche "ich mag keine Änderungen"-Optionen mag ich nicht. 

Außerdem ist mir das zu in flexibel. Vielleicht möchte ich ja mal im Profil eines Nutzers suchen, dann möchte ich das aber nicht erst in den Einstellungen umstellen müssen.
Eine Lösung müsste flexibel und sichtbar genug sein, dass sie vom Durchschnittsnutzer entdeckt und aktiv genutzt wird, aber gleichzeitig darf sie nicht im Weg stehen.

**Comment by JohnnyKarate2** [comment]
Ich persönlich suche immer mit !u:user wenn ich ein Profil durchsuchen will, aber ja das kennen wahrscheinlich nicht alle.

Andere Idee:
Wie wäre es wenn das Such-Icon weiterhin immer die "normale" Suchfunktion öffnet und wir dafür oben rechts in dem Menü mit den 3 Punkten eine "Benutzer durchsuchen" Option hinzufügen? Würde da ja auch eigentlich ganz gut reinpassen, weil dort auch andere benutzerspezifische Funktionen sind.

**Comment by oliverbestmann** [comment]
Finde ich auch nicht schön. Der Standard sollte dort schon sein, die Uploads des Benutzers zu durchsuchen. Überall anders bezieht sich die Suche ja auch auf "den aktuellen Kontext". Wenn du durch Top, Neu, Best of gehst, es wird immer im aktuellen Kontext gesucht. Und hier ist Kontext halt die Uploads des Nutzers. 

Was ich mir vorstellen könnte: wenn du auf die Lupe drückst, könnte der Nutzer als anwählbare Option in der Suchmaske, die dann aufgeht, erscheinen.
Aber je mehr ich darüber nachdenke, desto mehr finde ich, dass das alles nicht nötig ist, und man wirklich einfach übers Menü auf neu/top/etc gehen kann.

Sonst kommt morgen der nächste Punkt: "Ich würde jetzt aber auch gerne von dort aus nur in best of suchen" oder "wenn ich in den Favoriten eines Benutzers bin will ich aber dessen Uploads durchsuchen" oder so.

**Comment by mopsalarm** [comment]
Finde ich auch nicht schön. Der Standard sollte dort schon sein, die Uploads des Benutzers zu durchsuchen. Überall anders bezieht sich die Suche ja auch auf "den aktuellen Kontext". Wenn du durch Top, Neu, Best of gehst, es wird immer im aktuellen Kontext gesucht. Und hier ist Kontext halt die Uploads des Nutzers. 

Was ich mir vorstellen könnte: wenn du auf die Lupe drückst, könnte der Nutzer als anwählbare Option in der Suchmaske, die dann aufgeht, erscheinen.

Aber je mehr ich darüber nachdenke, desto mehr finde ich, dass das alles nicht nötig ist, und man wirklich einfach übers Menü auf neu/top/etc gehen kann.
Sonst kommt morgen der nächste Punkt: "Ich würde jetzt aber auch gerne von dort aus nur in best of suchen" oder "wenn ich in den Favoriten eines Benutzers bin will ich aber dessen Uploads durchsuchen" oder so.

**Comment by JohnnyKarate2** [comment]
Mmh ja, valider Punkt, wenn man das Nutzerprofil als Kontext wie Top, Neu, Best of sieht. Trotzdem ist es ja auch irgendwie etwas eigenständiges, weil Top, Neu, etc. immer die Root-Ansichten sind.  

"Nötig" ist es definitiv nicht, hast schon recht. Dachte nur ich frag mal nach ob man da was machen kann weil mich das neue Verhalten echt nervt.

Das mit dem Nutzer als anwählbare Option in der Suchmaske ist glaub ich auch nicht besonders optimal, weil wir dann anfangen eine Kontext-Option in diese Suchmaske zu bringen, die bisher ja auch nur dazu dient in dem jeweiligen Kontext (neu, top, etc.) weitere Filtermöglichkeiten zu bieten.
Dann kommt wieder die Frage warum dort nicht auch noch direkt anbieten wenn ich in neu bin bekomme ich noch die optionen stattdessen in top zu suchen usw. 
Aber wenn das etwas ist womit ihr zufrieden wärt, könnte ich auch dafür ein PR stellen bei Gelegenheit.

**Comment by mopsalarm** [comment]
*abwählbare Option

Stimmt schon. Ich denke wir lassen es nach. Das Argument mit dem Stack finde ich auch ehrlichgesagt nicht sehr stark. Und das man früher an der Stelle in Neu gesucht hat, war ursprünglich auch nur ein Bug, das was nie das gewünschte Verhalten. 

Du kannst natürlich gerne einen pullrequest machen, aber wenn der nicht mit ner generischen Lösung kommt, die den Anforderungen entspricht, dann merge ich das  wahrscheinlich nicht.

**Comment by JohnnyKarate2** [comment]
Also wäre z.b. eine Checkbox mit "Suche in Hochlads von..." über dem "Minimaler Benis" Slider, die man dann abwählen kann eine Lösung die du annehmen würdest?
Weil dann könnte ich das machen, falls ich keine bessere Idee habe bis ich dazu komme (dieses Jahr wahrscheinlich keine Zeit mehr).

**Comment by mopsalarm** [comment]
Denke ja

**Comment by JohnnyKarate2** [comment]
Hey, ich glaube ihr könnt das issue mal zu machen wenn es sonst keiner machen will. Ich bin bisher nicht dazu gekommen und ich werd auch in absehbarer Zeit auch nicht solche Langeweile haben dass ich mich da dran setzen will. Vor allem weil mir die Lösung die ihr annehmen würdet auch nicht so wirklich gefällt. Dann versuche ich mich lieber an das neue Verhalten zu gewöhnen, oder mach mir einfach ein Fork in dem ich es ganz raus hole.
