### ISSUE TITLE
Keine Wiedergabe bei WebM's

### ISSUE THREAD

**Issue by 2wayne** [mopsalarm/Pr0#28]
Bei vielen WebM's erscheint die Meldung: "Das Video kann nicht wiedergegeben werden."

**Comment by mopsalarm** [comment]
Relatiert zu #17 - besserer Player wäre gut!

**Comment by Graphicscore** [comment]
Das ist meistens Geräte abhängig, nutzen wir in dem Projekt ne ganz normale Video View ? Wenn ja kann es schon ausreichen, alles mit nem Mediaplayer auf ne TextureSurfaceView zu zeichnen.

**Comment by mopsalarm** [comment]
Ja, normale VideoView. Die benutzt intern auch den MediaPlayer. Ich hatte gehofft um das selbst schreiben herum zu kommen. Bei dem Handling der ganzen States kommt es sonst so schnell zu Problemen. Aber du kannst sonst probehalber MediaViewer in der App Subclasses und das probieren :)

**Comment by mopsalarm** [comment]
Ich werde dazu heute einen quickfix machen. Habe eine Idee, wie man das in das vorhandene VideoView "hinein" bekommen sollte.

**Comment by Graphicscore** [comment]
Theoretisch kannst du die VideoView ja einfach mal durch ne custom SurfaceTextureView austauschen die nen Mediaplayer besitzt, sonst musste auf andere Mediaplayer ausweichen , wie zb VLC

**Comment by mopsalarm** [comment]
Ich habe jetzt den Code des VideoViews genommen und alles, was um MediaController und Subtitles ging, rausgelöscht. Das läuft im Prinzip auf deinen Vorschlag mit SurfaceView hinaus.

**Comment by mopsalarm** [comment]
Erstmal closed. Bei den meisten läuft es, denke ich. Wenn Sie s irgendwie reproduzierbar ist, können wir weiter gucken
