### ISSUE TITLE
Anzeigebug mit dem Fullscreen Button

### ISSUE THREAD

**Issue by krabat693** [mopsalarm/Pr0#280]
![Screenshot_20230727-154636](https://github.com/mopsalarm/Pr0/assets/140731271/ea552aa4-29d0-47f6-87d5-5b50e7ba0941)

Irgendwas hat wohl ausgelöst dass der Button sich gehovert fühlt. Dadurch wurde seine Position auf dem Screen Absolut.

Antippen um in Fullscreen zu gelangen und anschließende rückkehr hat diesen Zustand gelöst.

Appversion ist die 1.201

**Comment by mopsalarm** [comment]
Das scheint mir ein Issue mit deinem Android System zu sein. Kann ich weder reproduzieren noch höre ich as von anderen Nutzern. Sorry!
