### ISSUE TITLE
Symbol für Ton wieder Rot färben

### ISSUE THREAD

**Issue by Angl0r** [mopsalarm/Pr0#287]
Moin, 

Seit dem letzten Update hat sich das Icon für Ton bei Videos geändert und ist nun nur noch weiß. Häufig fällt es dadurch schwer zu erkennen ob der Ton nun eingeschaltet ist oder nicht. Ich fand es übersichtlicher als das Icon im eingeschalteten Zustand rot war. Gibt es eine Möglichkeit das Icon wieder herzustellen?

**Comment by FloFaber** [comment]
Generell fehlt der Kontrast beim Play/Pause und dem Mute Button. Auf einem Video mit weißem Rand z.B. sieht man sie kaum bis gar nicht und muss daher nach Gefühl tippen.

**Comment by mopsalarm** [comment]
Zufrieden?

**Comment by Angl0r** [comment]
Ja sehr! Vielen Dank :)
