### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#29]
Wir brauchen unbedingt UI Tests. Irgendwas, was die App auf verschiedenen Android-Versionen installiert und simple Tests (Einloggen, Favoriten öffnen, Bilder und Videos angucken, Gif2Webm aktivieren/deaktivieren, etc) durchführt.

**Comment by do9xe** [comment]
Werde mal auf HTC Desite X mit Android 4.0.4, Kernel 3.0.21 testen.

**Comment by mopsalarm** [comment]
Danke, hier waren allerdings eher automatische Tests gemeint. Allerdings freue ich mich natürlich auch über manuelle Tester!

**Comment by mopsalarm** [comment]
https://developer.android.com/tools/testing-support-library/index.html
Mit espresso wäre gut. Na, hat jemand Lust?

**Comment by PDDStudio** [comment]
Noch aktuell?

**Comment by mopsalarm** [comment]
Immer!

**Comment by PDDStudio** [comment]
@mopsalarm Gibt es irgendwelche vorgeschriebenen Tests? Ein spezielles Framework o.ä? Oder nur manuelle tests

**Comment by mopsalarm** [comment]
Aktuell gibt's leider gar nichts (shame on me). Ich bin da ganz offen.  Irgendwas automatisiertes wäre super, irgendwas was testet, dass die App auf einem Emulator läuft und so grundsätzliche Sachen richtig macht und nicht beim anzeigen der Kommentare abstürzt oder so. Das wäre ein schöner Anfang.

**Comment by mopsalarm** [comment]
Am besten auch verschiedene Einstellungen durchprüft.

**Comment by PDDStudio** [comment]
@mopsalarm Ich habe jetzt selber auch noch nicht viel mit Espresso gemacht, ich schau da mal rein, zur Not müsste ich halt auf manuelle Tests zurückgreifen (Phone/Tablet)

**Comment by MetalMatze** [comment]
Vielleicht hilft ja auch [caster.io](https://caster.io/episode-list/). Ich meine damit explizit die Episoden 26 - 29. Hab es selbst nicht angeguckt, aber die anderen Sachen waren ganz hilfreich.

**Comment by mopsalarm** [comment]
Ja, Espresso ist glaube ich aktuell defacto Standard auf Android. Möglicherweise gibts noch UIAutomator oder gar den ui-monkey.

Manuelle Tests sind allerdings quatsch. Ich möchte die ja schnell laufen lassen können, bevor ich ein Release mache um auch seltenere Kombinationen zu validieren. Nicht auf jemanden anderes Warten, das der vllt am nächsten Tag Zeit hat, ein paar Sachen durchzutesten.

**Comment by PDDStudio** [comment]
@mopsalarm alles klar, du müsstest dann aber die Tests schreiben und mit rein mergen damit sie jeder direkt hat und testen kann

**Comment by mopsalarm** [comment]
Ne, es geht nicht darum, dass jemand die Tests ausführt, sondern dass jemand, bzw mehrere Leute, ich inklusive, diese Tests schreiben. Ausführen kann ich sie selbst im Zuge eines releases oder der Entwicklung.

**Comment by PDDStudio** [comment]
@mopsalarm achso okay dann habe ich das falsch verstanden 😛 aber beides wäre auch eine gute alternative (denke nicht das du so viele Geräte zum testen hast, oder?)

**Comment by mopsalarm** [comment]
Ja. Allerdings geht es bei den Tests auch weniger um die Eigenheiten der Geräte. Solche Tests sind dafür gedacht Programmierfehler oder Abstürze zu entdecken. Dafür reichen dann Emulatoren für verschiedene Systeme, also Android 4, 5, 6 und ein paar Tablets. Auf denen werden dann vordefinierte Aktionen ausgeführt, verschiedene Einstellungen aktiviert und andere Sachen validiert. Das mache ich aktuell per Hand, aber das ist natürlich viel zu aufwendig. 

Um Probleme auf unterschiedlichen Geräten zu finden ist dann das Beta Programm da. Da geht's dann an etwa 5 Prozent der Nutzer, und wenn dort Fehler auftreten, bekomme ich die normalerweise über crashlytics oder Feedback mit.

**Comment by Fusl** [comment]
Wie wär's mit https://aws.amazon.com/device-farm/ ? Benutzen wir auch für unsere Android und iOS App.

**Comment by mopsalarm** [comment]
Dafür müsste ich/jemand aber erstmal Tests schreiben ;)

**Comment by koriwi** [comment]
Teilzeit QA'ler hier. Beruflich Developer. Wenns Thema noch aktuell ist würde ich mal ein paar Tests basteln.

**Comment by mopsalarm** [comment]
Ja natürlich. Tu die kein Zwang an. Mit dem neuen Espresso Test Recorder in Android Studio 2.2 kriegt man vllt auch schnell einiges fertig.
