### ISSUE TITLE
Pol-Filter ist nach dem Neustart der App wieder aktiviert.

### ISSUE THREAD

**Issue by MartJo** [mopsalarm/Pr0#290]
Deaktiviert man den Pol-Filter und startet anschließend die App neu, ist der Filter wieder aktiviert.

Realme GT 2 - Android 13

**Comment by mopsalarm** [comment]
Works as intended. Kannst du in den Einstellungen der App umstellen.

**Comment by MartJo** [comment]
Alles klar. Danke für den Hinweis und die App.
