### ISSUE TITLE
App usage heats up phone and crashes

### ISSUE THREAD

**Issue by Miislaa** [mopsalarm/Pr0#291]
So I dont know why this is happening. Im using a Samsung S23 Ultra and after using the app and scrolling through it for a few minutes it starts to heat up the phone and then just crashes, this happened on my Google Pixel 6 Pro aswell but not on my Huawei Mate 10 Pro before it.
Any solutions to this?

**Comment by mopsalarm** [comment]
Nope, this could be anything, probably phone related. We don't see any other support requests with the same issue.
