### ISSUE TITLE
Owncloud für alle beteiligten erstellt

### ISSUE THREAD

**Issue by kratostav** [mopsalarm/Pr0#3]
server: kratostav.at/owncloud
user: gleich wie auf Pr0
pw: changeme123

![image](https://cloud.githubusercontent.com/assets/5694929/6202938/c90f0d92-b505-11e4-9d64-4356c07f927d.png)

**Comment by mopsalarm** [comment]
Hey Jungs, ist das Projekt für euch tot, oder habt ihr mich nur ausgeschlossen. Ich vermute letzeres, da ich keinen Account für OwnCloud abbekommen habe. Aber dann hätte man mir das auch direkt sagen dürfen.

**Comment by kratostav** [comment]
sry kann sein dass ich dich überlesen habe

**Comment by kratostav** [comment]
hab dich erstellt
![image](https://cloud.githubusercontent.com/assets/5694929/6377780/09e09286-bd27-11e4-9e3a-7eb1f29f37f8.png)

**Comment by mopsalarm** [comment]
Haha, okay und da ist alles leer - dann habe ich wohl nicht viel verpasst.

**Comment by kratostav** [comment]
ne irgendwie is nie was passiert

**Comment by mopsalarm** [comment]
Ich habe heute früh und heute Abend ein wenig Arbeit hinein gesteckt. Pushe das, sobald es soweit ist.

**Comment by kratostav** [comment]
ok

**Comment by Graphicscore** [comment]
Ehm..... Ich hab da die ganze Zeit mit einem anderen in einem anderen Repository dran gebaut, weil sich ja keiner mehr von euch gemeldet hat, Ich hab das inkl. Design(Orientiert am Konzept) gebaut. Bin da die ganze Zeit dran am wörken. Nur bevor ihr hier jetzt unnötig Arbeit rein steckt

**Comment by mopsalarm** [comment]
Na, dann würde ich sagen: Konkurrenz belebt den Keller (oder so ähnlich).

**Comment by Graphicscore** [comment]
Ich weiß nicht ob das so gut ist wenn wir da unter einander konkurrieren

**Comment by mopsalarm** [comment]
Naja, reddit beispielsweise hat auch mehrere konkurrierende Apps und jeder kann sich aussuchen, was ihm am besten gefällt. Spricht doch nichts gegen?: https://play.google.com/store/search?q=reddit&c=apps&docType=1&sp=CAFiCAoGcmVkZGl0egIYAIoBAggB:S:ANO1ljL9yKU

**Comment by Graphicscore** [comment]
Natürlich nicht, wie gesagt unser Design orientiert sich am Konzept Art, nur damit ihr wisst. Nicht das wir am Ende 2 verschiedene beinahe identische Apps haben.

**Comment by mopsalarm** [comment]
Gucken wir mal :)

**Comment by mopsalarm** [comment]
Entwickelt ihr eure App auch OpenSource?

**Comment by mopsalarm** [comment]
Ich habe gerade eine halbe Stunde lang geschaut, wie man aus der API bekommt, ob und wie man einen Post gevoted hat. Ergebnis: gar nicht, das speichert cha0s gekonnt lokal zwischen. Wenn man sich mal im private-mode einloggt sieht man, dass das nicht vom Server kommt - tricky!
