### ISSUE TITLE
Feature Request: Nutzer blockieren

### ISSUE THREAD

**Issue by G4m813R** [mopsalarm/Pr0#300]
Sehr häufig gewünscht und in der Web Version mittlerweile implementiert: Geblockte Nutzer werden nun auch im Stream ausgeblendet. Blockier Möglichkeit in der App fehlt generell noch.

**Comment by mopsalarm** [comment]
Passiert da alles serverseitig, oder muss irgendwas im Frontend gefiltert werden? Was bekomme ich, wenn ich auf einen Link zu einem Post/Kommentar geklickt wird, dessen Ersteller geblockt ist?

**Comment by RundesBalli** [comment]
> Passiert da alles serverseitig, oder muss irgendwas im Frontend gefiltert werden? Was bekomme ich, wenn ich auf einen Link zu einem Post/Kommentar geklickt wird, dessen Ersteller geblockt ist?

Ich habs grad mal probiert.
1. Wenn man auf das geblockte Userprofil geht und sich die Kommentare / Uploads anguckt ist alles beim alten.
2. Wenn man auf neu unterwegs ist, und da normalerweise ein Post von jemandem ist der blockiert ist, wird der einfach nicht angezeigt, was daran liegt, dass der Endpunkt `/api/items/get?id=yyyyyyy&flags=xx` genau diesen Post einfach nicht ausliefert. (in diesem Fall ist yyyyyyy ein Post daneben gewesen)
3. Wenn man einen Direktlink aufruft zum Post/Kommentar des geblockten Users, wird der trotzdem angezeigt.

**Comment by mopsalarm** [comment]
Dann fehlt also wirklich nur der call um einen Nutzer zu blockieren bzw den Block aufzuheben.

**Comment by holzmaster** [comment]
Je nachdem wie wichtig das is, fehlt ggf noch eine Liste an blockierten Nutzern irgendwo, damit man die Blocks auch aufheben kann. Weiß nicht, ob die App sowas aktuell hat, glaube nicht.
