### ISSUE TITLE
Problem mit Videos vorladen

### ISSUE THREAD

**Issue by G4m813R** [mopsalarm/Pr0#307]
"Seid einiger Zeit ist mir aufgefallen, dass vorgeladene Videos nicht mehr 100% funktionieren, wenn man schlechtes oder gar kein Internet hat. Vor dem abspielen wird versucht noch irgendetwas aus dem Internet zu laden. Vorher ging das mal."

"Ich habe seit einigen Wochen ein problem mit vorgeladenen Videos in der App. Ich habe oft auf der Arbeit weder Mobiles Netz noch Wlan und lade mir deshalb morgens immer content vor. Dies hat früher ohne Probleme geklappt diese Posts anzuschauen. Seit ein par Wochen kann ich zwar durch die vorgeladenen Posts blättern aber Videos spielen teils erst nach mehrere n Sekunden oder auch garnicht ab."

**Comment by mopsalarm** [comment]
Gleiche Antwort wie immer: Vorladen ist kein offline Modus. Es werden nur die Mediendaten schonmal _vor_geladen, damit im Mobilfunk nur ein paar kB fürs JSON verwendet werden muss.
