### ISSUE TITLE
v1.198.1 parsing error

### ISSUE THREAD

**Issue by zer0fl0w** [mopsalarm/Pr0#309]
die aktuellste unter releases verfuegbare version
(https://github.com/mopsalarm/Pr0/releases/download/1.198.1/app-release.apk) laesst sich nicht installieren. irgendwas ging wohl beim build schief.
die dateigroesse der apk differiert zur vorgaengerversion auch zu stark.

**Comment by zer0fl0w** [comment]
same for v1.198.2.

**Comment by zer0fl0w** [comment]
same for v1.198.3

a14 pixel 7

**Comment by mopsalarm** [comment]
Jo, danke, ich guck gleich mal. Am besten immer nur über die Updates in der App installieren.

**Comment by zer0fl0w** [comment]
gefixt mit v1.198.4. 
ist wieder ok. 
danke.
