### ISSUE TITLE
Custom Website für einfacheres herunterladen der App ?

### ISSUE THREAD

**Issue by Graphicscore** [mopsalarm/Pr0#31]
Wie siehts eigentlich mit einer "eigenen" selbstgebauten Website aus, über die neue Nutzer einfacherer die App installieren können, ich habe zb. Immer massive Probleme die App aus dem Repositiory herunter zu laden. Wenn da interesse dran besteht würde ich mich vielleicht da mal dran setzten.

**Comment by Toilettenpapier** [comment]
Find ich gut, mein Interesse hast Du.

**Comment by Lokzmir** [comment]
Wenn du Hilfe brauchst sag bescheid, bin dabei

**Comment by mopsalarm** [comment]
Kann man nicht einfach immer die aktuelle Version in der README.md direkt als APK verlinken? Okay, Github schreckt vielleicht viele ab. Also meintwegen auch: Go for it!

**Comment by mopsalarm** [comment]
Na, wie schauts aus?

**Comment by skuzzle** [comment]
Kann man cha0s nicht gewinnen die App als offizielle pr0 App auf dem pr0gramm anzubieten? Das derzeitige Problem ist ja, dass nicht allzuviele Leute überhaupt von der App wissen, weil die Posts dazu schon lange her sind und sie viele nicht mitbekommen haben. Das Problem würde durch eine weitere Webseite nicht gelöst werden, solange sie nicht vom pr0gramm verlinkt wird.

**Comment by Toilettenpapier** [comment]
Wenn Du das schaffst, da bist Du der Meister im Social Engineering. Er selber hat TheGraphicscore und mir gesagt, dass er es falsch finde, pr0gramm in 5 Zoll zu pressen. Also würde eher dazu tendieren, dass man ihn nicht dazu gewinnen kann. Versuchen kannst du es trotzdem.

**Comment by mopsalarm** [comment]
Es sind immerhin schon gut 500 bis 600 tägliche User, die die App nutzen.

**Comment by Toilettenpapier** [comment]
Wie ermittelst du diese Werte?

**Comment by mopsalarm** [comment]
Ich benutze crashlytics um über abstürze informiert zu werden. Das bietet grobe Statistiken zur Anzahl der User, Systeme, etc.  Etwa so: https://g.twimg.com/blog/blog/image/FLight_1-_Cannonball.png

**Comment by Toilettenpapier** [comment]
Danke der Antwort.

**Comment by X39** [comment]
Eine eigene seite ist recht easy sobald man sich auf das design "geeinigt" hat
und bzgl. pr0gramm integration
nun
ich bezweifle jedoch stark das cha0s und gamb sich von einer weiteren person ins handwerk pfuschen lassen würden weswegen es unwahrscheinlich ist jemals eine kooperation jenseits einer offenen pr0gramm API zu bekommen

**Comment by mopsalarm** [comment]
Möchte sich jemand um ne Seite kümmern? Sonst schließe ich das hier am Montag.

**Comment by MetalMatze** [comment]
Ich könnte am Wochenende das ganz simples mit Bootstrap zusammen bauen. Eine HTML landing page reicht doch, oder?

**Comment by MetalMatze** [comment]
Hat jemand eine Idee im Kopf oder eine Seite die so ähnlich als Vorlage dienen könnte?

**Comment by mopsalarm** [comment]
Ja, reicht eigetnlich. Weiß nicht, irgendwas einfaches, schlichtes, professionelles, und vielleicht sollten sich die pr0gramm-Farben wieder finden, wenigstens das rot aus der App und vllt das pr0gramm-Grau in der Schrift? Man könnte github pages verwenden, dann lässt sich das über pull requests ja recht schön handhaben.

**Comment by SnipeLike** [comment]
Steh beim erstellen der Seite gerne zur hilfe... Server um die Seite online zu stellen stehen zur Verfügung?

**Comment by Toilettenpapier** [comment]
Ich könnte einen zu Verfügung stellen, wenn es gebraucht wird.

**Comment by X39** [comment]
http://x39.unitedtacticalforces.de/
"schlicht und einfach"

**Comment by mopsalarm** [comment]
Wie gesagt, ich würde github pages verwenden wollen. Dann ist man auf niemanden angewiesen, der einen Server oder Webspace bereit stellt und updaten der Seite ist durch einen einfachen PR erledigt. Man schaue hier:  https://pages.github.com/#vanilla-step-1
Einfach alles in einem extra branch in dieses repository packen, fertig. 

@X39 Ein MediaWiki ist für mich nicht "schlicht und einach"

**Comment by SnipeLike** [comment]
Achso, hab nicht gewusst das das so alles über Git möglich ist. Kan man mal machen.

**Comment by X39** [comment]
@mopsalarm ich sprach von der front page
http://x39.unitedtacticalforces.de/
nicht den backlinkgs (also wiki & cloud)

**Comment by mopsalarm** [comment]
Achso okay. Ja und worauf ich noch wert legen würde ist, dass es responsive ist, bzw auf Handies gut umsieht. Aber das würde Bootstrap ja mitbringen.

**Comment by Graphicscore** [comment]
Ich hv dieses Wochenende auch Zeit und kann da nochmal Zeit rein investieren. Bin halt leider kein Profi in dem Gebiet :o

**Comment by MetalMatze** [comment]
Ich bin dran und werde gleich beginnen einen `gh-pages` Branch zu machen und dort eine kleine Seite bauen. Erstmal als Grundlage, dann können wir damit weiterbauen.

**Comment by Graphicscore** [comment]
Mit Bootstrap oder so ?
Am 02.05.2015 11:33 schrieb "Matthias Loibl" <notifications@github.com>:

**Comment by mopsalarm** [comment]
@MetalMatze  Noch ein Tipp zum erstellen eines leeren branch in einem repository http://bitflop.com/tutorials/how-to-create-a-new-and-empty-branch-in-git.html

**Comment by MetalMatze** [comment]
Danke für den Tipp. `--orphan` sieht gut aus, kannte ich nicht.
@Graphicscore Ja mit Bootstrap. Aber ich werde bootstrap wahrscheinlich fast nicht brauchen.

**Comment by MetalMatze** [comment]
So. Ich habe gerade mal in 45min das zusammen gebastelt.
http://metalmatze.github.io/Pr0/
Was sagt ihr?

Die Farben sind von pr0gramm kopiert und es ist responsive.

Ich habe mich ein wenig hier inspirieren lassen: https://www.circle.com/en
Ich weiß gerade noch nicht genau, was ich sonst für Inhalt rein schreiben soll.
@mopsalarm du weißt sicherlich mehr. Kannst gerne einen Pull-Request auf meinen Branch machen :)

**Comment by mopsalarm** [comment]
@MetalMatze Sehr schön, finde ich tendenziel schonmal super. Ich hätte das Video allerdings eingeloggt gemacht, dann kann man auch die Nachrichten und das Voten/etc schöner zeigen. 

Den pull-request musst glaube ich du machen, weil du requestest ja, dass ich das übernehme :)

Eine Sache, die ich ganz gerne hätte, wäre ein kleines JavaScript, das immer die update.json ausließt und immer die aktuelle Version verlinkt. Das wird allerdings vermutlich gar nicht so einfach wegen dem Allow-Control-Allow-Origin Header, oder? Ideen?

**Comment by Graphicscore** [comment]
Sieht schonmal ganz gut aus, soll da ein Video drin sein ? Bei ist das nur ein Standbild, ich werde gelich auch mal ein bischen zusammen basteln ;)

**Comment by mopsalarm** [comment]
Dann vielleicht das video noch zusätzlich als webm mit einbinden. :)

**Comment by SnipeLike** [comment]
Damit immer die neuste Version verlinkt wird, kann ich mir sonst mal anschauen ob ich das hin bekommen. Wird leider jedoch nicht dieses Wochenende... 
@MetalMatze gefällt mir. Würde irgend wo noch schreiben, dasa das nicht eine "offizielle" pr0 App ist...

**Comment by X39** [comment]
bzgl. der neusten version
wie funktioniert das aktuelle system?
im grunde sollte es nämlich möglich sein da irgend wo mithilfe von JavaScript immer die aktuellste an zu bieten insofern alles auf einem web server liegt

**Comment by mopsalarm** [comment]
Ja genau, wo es tricky wird ist, dass es in einem anderen github repository liegt und nicht unbedingt unter der selben domain erreichbar ist. Und eine zusätzliche Schwierigkeit ist, dass github selbst die Dateien mit einem falschen Content-Type Header ausliefert

**Comment by X39** [comment]
meh
selber schreiben ^^

http://x39.unitedtacticalforces.de/api.php?action=projects&project=pr0notify

**Comment by mopsalarm** [comment]
Ja, ich hab genau so eine Datei habe ich ja auch unter https://github.com/mopsalarm/pr0gramm-updates/blob/master/update.json   ... aber ein JavaScript auf github.io kann keine Anfragen nach github.com stellen, und ein auf github.com gehostete .js-Datei kannst du nicht einfach wo anders einbinden, wegen dem Content-Type Header. Bin jetzt über gitraw gegangen. Ich stell dir mal nen pull-request, @MetalMatze 

@Graphicscore Ich bin übrigens gespannt! Kannst das Skript vielleicht auch gleich mit einbinden

**Comment by schr3j** [comment]
Das skript muss ja eh nicht viel tun.
Dieses ersetzt den link von a#download-link mit der aktuellen Version und setzt den inhalt von #version auf die aktuelle Versionsnummer aus der update.json
Weil ich zu faul für PR bin:

```javascript
$(document).ready(function() {
	var url = "https://rawgit.com/mopsalarm/pr0gramm-updates/master/update.json";
	
	jQuery.getJSON(url).done(function(json) {
		$("#version").html(json.version);
		$("#download-link").attr("href", json.apk);
	});
});
```

**Comment by mopsalarm** [comment]
@schr3j Jepp, den Pull-Request mit nahezu dem gleichen Skript habe ich bereits gestellt. Das Problem war halt nur, dass du das Skript ausschließlich von rawgit.com ausführen kannst, wegen Cross-Origin-Stuff

**Comment by Graphicscore** [comment]
Hier mal das was ich gerade so gebastelte habe : http://graphicscore.github.io/

Bilder werden noch ausgetauscht etc......

Bitte um Feedback !

**Comment by mopsalarm** [comment]
Mir gefällt, dass dort wenigstens ein wenig an beschreibungs Texten ist! Was mir nicht so gefällt ist der graue Hintergrund und dass ich den Download button nicht "immer" da habe. Auch @MetalMatze Idee mit dem Video fand ich gut. Was sagt der Rest von euch? Vielleicht können wir das nun irgendwie klug kombinieren!?

On a side note: "Sie" oder "Ihnen" schreibst du als Anrede soweit ich weiß groß. Aber wichtiger: Ich würde meine mit-pr0grammer lieber dutzen wollen.

**Comment by X39** [comment]
> meine mit-pr0grammer

Werte Kellergemeinde

**Comment by mopsalarm** [comment]
Klingt schon eher richtig

**Comment by Graphicscore** [comment]
Ich werde nochmal ein wenig reininvestieren ;)

**Comment by Graphicscore** [comment]
So hab den text jetzt noch ein wenig angepasst, alle Bilder in der Finalen Auflösung mit passendem Render hochgeladen, Auf dem Smartphone sieht die seite auch noch gut aus, müsste nur noch der Download Button verlinkt werden und wir wären Ready 2 Go, bin natürlich für verbesserungs-Vorschläge offen :)

**Comment by mopsalarm** [comment]
Ich bin immer noch für Videos in den Bildern. Kurze loops oder so.

**Comment by Graphicscore** [comment]
Wenn das da jemand in das Render reindübeln kann gerne, ich wollte es halt bloß nicht als GIF machen wegen schlechter qualität und ich bin zu unfähig Videos in die Bilder zu packen -.-'

**Comment by mopsalarm** [comment]
Quark, mach das direkt im Browser - Positionier das Video einfach korrekt über nem statischen Screenshot mit dem Handy-Bild drumrum.

**Comment by SnipeLike** [comment]
Den Download Button würde ich noch eher am Anfang platzieren. Nicht jeder will zuerst nach ganz unten scrollen um die app zu laden.

**Comment by Graphicscore** [comment]
@SnipeLike , Es gibt doch einen Download button ganz oben ^^

**Comment by X39** [comment]
"Native" Android App?
soweit ich weis wird hier kein C verwendet ...

wäre also super wenn das wort raus geworfen wird ( http://stackoverflow.com/questions/557574/what-is-native-implementation-in-java )

**Comment by mopsalarm** [comment]
@Graphicscore Ja aber der fällt kaum auf und ist weg, sobald du nur ein ganz kleines bisschen gescrollt hast. Habe keine Videos da.

@X39 Doch, im Mobile App Kontext ist "Native App" tatsächlich gleich "nicht Web" - bzw nativ für das entsprechende System entwickelt. Damit hat C nichts zu tun [Klugscheißer Kommentar von mir: warum überhaupt C, was macht das denn mehr nativ als andere Sprachen, die in Maschienencode kompiliert werden? ;) ]. Aber was du da gepostet hast bezieht sich auf das native Schlüsselwort in Java.

**Comment by mopsalarm** [comment]
Ach und eigentlich gehört das nicht hier her, aber trotzdem: Falls ihr noch Ideen für die App habt, ob ihr sie selbst implementieren möchtet oder nicht, könntet ihr vllt noch ein paar Issues öffnen?

**Comment by Graphicscore** [comment]
Checkt mal die website
http://graphicscore.github.io/

Das Problem mit dem Downloadbutton sollte nun gelöst sein ;)

PS:
Ist eigentlich inzwischen das "Keep Display On" Feature drin ?

**Comment by mopsalarm** [comment]
Der Download-Button ist bei mir unter den Bildern.
Und eigentlich ist das Feature drin, ja.

**Comment by Graphicscore** [comment]
^fixed,

Mein Display geht aber trotzdem noch aus ....

**Comment by Toilettenpapier** [comment]
Ich würde, einfach damit es seriöser ankommt, alle persöhnlichen Anreden groß schreiben. 
Wirkt einfach besser.

**Comment by Graphicscore** [comment]
Alle "du" anreden auf "Du" ändern ?

**Comment by mopsalarm** [comment]
Duden sagt klein.

http://www.duden.de/sprachwissen/sprachratgeber/gross-oder-kleinschreibung-von--em-du-du--em--und--em-ihr-ihr--em--1

Nicht großgeschrieben wird auch in Werbeanzeigen bzw. -plakaten, Editorials von Jugendzeitschriften oder in Fragebogen (z. B. bei schriftlich fixierten Prüfungsfragen), da es sich hier jeweils nicht um eine persönliche Anrede handelt.

**Comment by Graphicscore** [comment]
Hat jetzt eigentlich einer ein Skript was auf ner Statischen URL die aktuelle App Version zurückliefert (als Datei), dann kann ich das nämlich verlinken und die Website ist benutzbar ^^

**Comment by mopsalarm** [comment]
"fertig" würde ich noch nicht sagen. Mir Fehlen immer noch Videos.
Siehe den Pullrequest für ne Art und weise, wie man an die Daten kommt https://github.com/mopsalarm/Pr0/pull/43

**Comment by Toilettenpapier** [comment]
Wenn das so ist, dann will ich mal nichts gesagt haben.

**Comment by Graphicscore** [comment]
@mopsalarm  Ich hab jetzt mal ein Video eingefügt, so in ordnung ?

**Comment by Graphicscore** [comment]
So Video sollte nun Funktionieren, Feedback ?

**Comment by mopsalarm** [comment]
Video ist jetzt etwas groß. Das würde ich noch kleiner machen. Ich wäre ja auch eher für kurze - kleine Loops neben den Stichpunkten zur Funktionalität. Und dafür, das Video eingeloggt aufzunehmen - dann funktioniert wenigstens alles.

Sorry, dass ich so anstrengend bin, aber ansonsten auf dem richtigen Weg ;)

**Comment by Graphicscore** [comment]
:| ^^, Alles gut, ich  kann dich da ja durchaus verstehen, Ich werde morgen nochmal das Video neu Aufnehmen und in kleine loops schneiden, der Download Button muss auch noch mit dem Richtigen Script verlinkt werden. Von den Bildern und der Aufmachen ist doch sonst alles klar oder ?

**Comment by mopsalarm** [comment]
Hab mir das gerade noch mal auf dem Handy angeguckt.
* man sollte nicht zoomen können 
* die Videos gehen nicht. webm wäre vllt noch gut 
* die Bilder sind nicht zentriert
* mir gefällt die erste Seite mit dem unscharfen grau immer noch nicht. Da sehe ich eher den Entwurf von @MetalMatze (metalmatze.github.io/Pr0) und wenn man herunter scrollt kommen dann die Seiten von @Graphicscore

**Comment by Graphicscore** [comment]
@mopsalarm also den geblurrten Hintergrund mit dem Hintergrund von MetalMatze swappen ?

**Comment by schr3j** [comment]
In den <head>
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
```

**Comment by Graphicscore** [comment]
@schr3j ist drin, sieht gut aus :+1:

**Comment by mopsalarm** [comment]
@Graphicscore Und die Bilder/Videos zentrieren

**Comment by Graphicscore** [comment]
@mopsalarm -.- Ich versuchs ja aber die wollen nicht :/

**Comment by X39** [comment]
Den Download button oben rechts am besten nicht mit JavaScript hinterher ziehen sondern per "position: fixed;" und entsprechenden angaben positionieren

**Comment by mopsalarm** [comment]
Und wir reden hier von einer Marketing Website, oder nicht?

**Comment by X39** [comment]
Fehler die Marketing Deppen machen muss man ja nicht übernehmen ...

**Comment by mopsalarm** [comment]
Schließe ich  mal, da die Einführung in den PlayStore die Geschichte ohnehin überflüssig macht.
