### ISSUE TITLE
Feature request: Tags "Mehr"-Button

### ISSUE THREAD

**Issue by jgoedde** [mopsalarm/Pr0#315]
Wenn es viele tags für einen post gibt, und man nicht genau in die scrollable Zeile mit den tags trifft aber dennoch versucht zu swipen, gelangt man oft durch die swipe-Geste zum nächsten post anstatt wie erwartet in der tag-liste zu horizontal zu scrollen.

Ich finde man könnte hier besser einen "Mehr" button anzeigen, der dann einfach die tags vertikal auflistet, anstatt, dass alle tags in einer horizontal scrollabaren Liste sind. Fände ich für die usability tatsächlich besser und wie hier vorgeschlagen ist es ja auch auf der web page.

**Comment by RundesBalli** [comment]
# Beispiel
Am Beispiel [dieses](https://pr0gramm.com/new/6287527) Posts:

## Eingeklappt:
![image](https://github.com/user-attachments/assets/eb0b4f1d-f87b-46bd-bfca-f20114b1436c)

## Aufgeklappt:
![image](https://github.com/user-attachments/assets/087b6de9-a75e-47f9-92e3-bdf7f8a26783)

---

# Einstellung:

## Im Seitenmenü:
![image](https://github.com/user-attachments/assets/609e1480-32f4-4787-8346-d5f83b211d85)

## "Visuell":
![image](https://github.com/user-attachments/assets/2422015a-5599-497f-bad1-ef2b039f09ec)

## "Mehr Tags anzeigen":
![image](https://github.com/user-attachments/assets/ed2b0394-3367-4454-84ed-4156754b3a2e)

**Comment by jgoedde** [comment]
Ahja, mein Fehler, das feature gibt es ja schon 🤦.
Dennoch, danke, dass du dir die Zeit für die Erklärung genommen hast.
