### ISSUE TITLE
Bildschirm nicht ausschalten

### ISSUE THREAD

**Issue by BenjaminBrossi** [mopsalarm/Pr0#35]
Es waere schoen, wenn man eine Option haette um zu verhindern, dass der Bildschirm ausschaltet.

**Comment by Graphicscore** [comment]
https://developer.android.com/training/scheduling/wakelock.html

Sieht net all zu schwierig aus. Kann sich da jemand drum kümmern ? ^^

**Comment by X39** [comment]
schwierig für den eigentlichen entwickler?
nein
für irgend jemand "externen"?
ja
da hier im grunde nichts dokumentiert ist (code ist die dokumentation ... oder besser: es gibt keine dokumentation) ist es recht kompliziert überhaupt den korrekten anfang zu finden (aufgrund der großen dateizahl jedoch notwendig)

**Comment by mopsalarm** [comment]
Ich würde das ins PostFragment einbauen, in onResume den wake lock holen und in onPause freigeben.

**Comment by schr3j** [comment]
Wozu denn Wake Lock?
Ein keep screen on Flag reicht ja wohl?

```Java
getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
```

das wird automatisch gemanaged. Müsste nur bei onCreate gesetzt und beim deaktivieren der Option gelöscht werden...

**Comment by mopsalarm** [comment]
Da hast du recht, an das flag habe ich nicht gedacht.

**Comment by mopsalarm** [comment]
Habe es jetzt mit View.setKeepScreenOn(true) gelöst.

**Comment by X39** [comment]
nicht einstellbar könnte jedoch dazu führen das einige user sich über einen leeren akku beschweren
sollte optimalerweise optional sein

**Comment by mopsalarm** [comment]
1. ist natürlich einstellbar
2. Ich denke tatächlich nicht. Das Feature hält das Gerät ja nur wach, wenn der Bildschirm ohnehin aktiviert ist. Wenn der Bildschirm aus ist oder du in einer anderen App bist, ist ja alles wie vorher.

**Comment by X39** [comment]
1. du hast den commit nicht referenziert (nur ```View.setKeepScreenOn(true)``` ist nicht sonderlich aussagekräftig diesbzgl.) macht man übrigens mithilfe von der nutzung eines spezial wortes wie fixed und anschließend der ticket nummer (foobar fixed #N)
2. Scenario: Jemand öffnet die app und legt das handy weg ohne es aus zu schalten. Resultat: Handy würde an bleiben.
es gibt solche leute nunmal und da es ohnehin nicht sonderlich komplex ist diesen teil einstellbar zu machen bietet es sich an

**Comment by mopsalarm** [comment]
Ach doch, es zeigt dir den Lösungsansatz den ich benutze habe, indem ich die entsprechende Methode erwähnt habe. Natürlich kommt da noch ein wenig drum herum aber das kannst du bei Interesse ja im commit sehen.den hätte ich natürlich dem issue zuordnen können, das stimmt. Aber du hättest ihn sonst auch in der commit Historie finden können, bevor du postest.
