### ISSUE TITLE
Einstellungen überarbeiten

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#36]
Die Einstellungen müssen überarbeitet werden. Es sind inzwischen richtig viele und sie sind entsprechend unübersichtlich.

Hat da jemand Lust, ein "Konzept" auszuarbeiten? Welche Einstellung wo hin kommt, eventuell neu gruppieren und mit Unterseiten, wenn nötig?

**Comment by schr3j** [comment]
Ich würde erstmal das mit den Filtern so lösen wie auf der Website: Also oben in der Actionbar ein Icon mit dropdown.

Der rest dann wie folgt:
- Verhalten
  - Doppelklick für Upvote
  - Bilder als gelesen markieren
  - Benisgraph aktivieren
  - Vollbild Zoomfunktion
  - Benachrichtigungen
  - Lesezeichen-Button
  - aktualisieren Button
- Visuell
  - Voten animieren
  - kleinere Vote-Buttons
- Datenverbrauch
  - Bildgröße
  - Gifs zu Webms (spart das daten?)
- Kompatibilität
  - Video kompatibilitätsmodus
- Updates
  - Auf Update prüfen
  - automatisch nach Updates suchen
  - Betas
- Sonstiges
  - Feedback
  - Changelog
  - Anonyme Bugreports
  - Logcat

ich würde das evtl. so sortieren und alles bis auf "Sonstiges" auf Unterseiten packen...

**Comment by mopsalarm** [comment]
Super. Danke! Wenn ich heute abend zeit habe, sortiere ich das einmal um.

**Comment by mopsalarm** [comment]
GIF zu Webm spart tatsächlich Daten. Die erzeugten webms sind ziemlich klein im Vergleich zu den gifs. Nur so 10 bis 20 Prozent der original große

**Comment by mopsalarm** [comment]
Habe es jetzt so ungefär umgebaut. War komplizierter als gedacht, da die SupportLibrary scheinbar keine ActionBar zusammen mit Unterseiten in den Preferences unterstützt.
