### ISSUE TITLE
Navigation-Drawer besser implementieren

### ISSUE THREAD

**Issue by androideo** [mopsalarm/Pr0#4]
Ich würde empfehlen eine Super-Activity mit einer DrawerLayout (aus dem Support-Package) zu implementieren. In den einzelnen Activities kann man dann das jeweilige Layout der View hinzufügen.
Kann gerne Code hinzufügen, wenn gewünscht.

**Comment by mopsalarm** [comment]
Ich habe bereits ein DrawerLayout in meiner Activity und zeige je nachdem welchen Eintrag man angeklickt hat, ein unterschiedliches Fragment an. Ich würde jedoch die Anzeige der Fragments und die Markierung der Einträge im Drawer automatisch synchronisieren lassen.
