### ISSUE TITLE
Dialoge überarbeiten

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#40]
Ich würde gerne die Dialoge fürs Kommentieren und Nachrichten Schreiben hübscher machen (oder drauf Verzichten)... Hat da vielleicht jemand eine hübsche Idee?

**Comment by schr3j** [comment]
Die Dialoge an sich sind ja nicht schlecht.. Aber es wäre total super wenn diese unglaublich unnötige Redundanz rausgenommen würde. Also 
```
*Einen neuen Kommentar schreiben* (Überschrift)
Bitte Kommentar unten eingeben
[Hier einen Kommentar eingeben] (im Textfeld)
```
könnte vlt zu
```
*Antwort an XYZ*
[Kommentar...]
```
geändert werden.
Und für die Tags wäre vllt
```
*Tag hinzfügen*
Mehrere Tags können mit Kommata separiert werden.
[würde, Kreiselficker]
```
nicht schlecht.

**Comment by mopsalarm** [comment]
Wenn du magst, stell doch nen pull request ein. Ich guck sonst heute abend, aber ich bin nicht so gut im Texte schreiben. ;)

**Comment by mopsalarm** [comment]
Habe gestern ein wenig in die Richtung gearbeitet und deine Vorschläge umgesetzt.
