### ISSUE TITLE
Möglichkeit Tags hoch- und runterzuvoten

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#45]
Wäre cool wenn man eine Funktion zum Voten der Tags hinzufügen könnte.

Bei der API geht das so:
1. Wenn man sich einen Post holt bekommt man auch alle zugehörigen Tags mit ihren IDs. (z.B. http://pr0gramm.com/api/items/info?itemId=777537)
2. Um einen Tag hoch/runterzuvoten muss dann ein **POST /api/tags/vote** aufgerufen werden mit den Parametern id={IDdesTags}&vote={1/-1}&_nonce={nonce}.
Die ID des Tags kriegt man aus Schritt 1, bei einem Upvote ist vote=1 bei einem Downvote -1

Implementieren könnte man das dann z.B. indem ein Kontextmenü angezeigt wird wenn man auf einen Tag klickt, das die Funktionen "Suche", "Lesezeichen anlegen", "Upvote", "Downvote" beinhaltet (oder evtl auch einmal kurz antippen = Upvote, zweimal kurz antippen = Downvote, einmal lang antippen = Suche)

**Comment by Graphicscore** [comment]
Man kann die Tags doch voten oder nicht?(Durch langes gedrückt halten)

**Comment by mYnDstrEAm** [comment]
Tatsächlich...hatte anscheinend noch ne alte Version. Hatte es außerdem nicht in der Featuresliste gesehen. Hab jetzt die neue Version und es klappt super!
