### ISSUE TITLE
Bildschirm geht immer aus

### ISSUE THREAD

**Issue by Graphicscore** [mopsalarm/Pr0#46]
Der Bildschirm geht bei mir immer aus, egal ob die Option an oder aus ist.

Getestet auf : OnePlus One mit Cyanogenmod 12 (Android 5.0.1)

**Edit** : Ich kann dem ding hier irgend wie kein Bug label geben ....

**Comment by mopsalarm** [comment]
Habe ich jetzt hoffentlich gefixt. Ich schiebe gleich ne Beta raus, kannst ja mal sagen ob da alles funktioniert.

**Comment by Graphicscore** [comment]
Beim Anschauen eines Posts bleibt der Bildschirm an :+1: in der Übersicht (top/neu) gehts immernoch aus ist das gewollt ?

**Comment by mopsalarm** [comment]
Ja, das ist gewollt.
