### ISSUE TITLE
Qualität bei grossen Bildern

### ISSUE THREAD

**Issue by BenjaminBrossi** [mopsalarm/Pr0#47]
Hier ein Beispiel das weder in der normalen, noch in der Fullscreen-View lesbar ist:

http://img.pr0gramm.com/2015/05/04/68f52694c8fa97fb.png

**Comment by mopsalarm** [comment]
Ja, aber das ist schwierig hinzugekommen. Zur Info: das Bild ist etwa 16k Pixel hoch. 
Da Android das UI hardwarebeschleunigt darstellt, müssen für die einzelnen Komponenten Texturen angelegt werden. Für Texturen gibt es aber eine maximalgröße, die von Gerät zu Gerät unterschiedlich ist. Bei mir sind es glaube ich 4k oder 8k Pixel zum Quadrat. Heißt also, dass das Bild zur Hälfte oder auf ein Viertel herunter skaliert werden muss.
Möchte man das umgehen, muss man das entweder ohne Hardwarebeschleunigung darstellen oder in kleinere Kacheln aufteilen und die beim darstellen aber korrekt zusammenfügen. Beides etwas, was mir aktuell zu viel Aufwand ist.
