### ISSUE TITLE
Gewünschte Features/Anregungen

### ISSUE THREAD

**Issue by Marc3lX** [mopsalarm/Pr0#5]
Gewünschte Features/Anregungen: 

Ich hab dir hier mal ein paar Dinge aufgeschrieben die mir aufgefallen sind/ die ich mir wünschen würde. Ich habe die Punkte mal nach Wichtigkeit sortiert. Falls dir was davon gefällt, kannst du es ja implementieren.

- Downloadbutton zum Herunterladen von Inhalten
- Bei einem Doppelklick das Bild im Vollbildmodus anzeigen (zoomen möglich)
- WebM bei anderer Display Orientation nicht neu laden
- Möglichkeit den Link des Posts zu markieren/teilen
- Beim dis/liken auf den Zähler des dis/likes +/- setzen.
- Möglichkeit Posts zu favorisieren 
- beim angemeldetem User nebem dem Namen den Benis anzeigen
- Tags voten können
- Ladebalken für WebM
- Profile anderer Nutzer aufrufbar
- Refreshanimation (Kreis gleichgroß bleibend, jetzt wird er ja größer beim runterziehen das ist etwas verwirrend da es sonst anders ist.)
- Drei Balken vom Menü müssen sich nicht drehen, da der Pfeil eh nicht sichtbar ist.

**Comment by mopsalarm** [comment]
Danke! Einzelne Issues wären zwar schöner, aber so ist erstmal okay. Kurz zu ein paar Punkten:

> Drei Balken vom Menü müssen sich nicht drehen, da der Pfeil eh nicht sichtbar ist.
Schwieriger zu entfernen als drin zu lassen. Das kommt so von alleine.

> Refreshanimation
Oh eigentlich dachte ich nicht, dass ich das verändert hab. Muss ich nochmal anschauen, habe da vielleicht was falsch gemacht.

> Ladebalken für WebM
Done

> WebM bei anderer Display Orientation nicht neu laden
Aktuell schwierig, habe ich aber auf dem Plan.

**Comment by kratostav** [comment]
>WebM bei anderer Display Orientation nicht neu laden
Ist nicht so schwer kann ich machen

**Comment by mopsalarm** [comment]
Okay, dann los. Änderst du das direkt im Repository oder schickst du mir dann einen pull request?

**Comment by mopsalarm** [comment]
Refresh animation habe ich ebenfalls erledigt.

**Comment by mopsalarm** [comment]
Das meiste erledigt
