### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#53]
Ich möchte Uploads machen können.
Dafür wäre es gut, wenn jemand schonmal bei seinem nächsten Upload den HTTP Verkehr (z.b mit wireshark oder auch einfach im Browser) aufzeichnet und mir irgendwie zukommen lässt. Ich werde auch noch einen Test machen, aber das könnte helfen!

**Comment by mopsalarm** [comment]
Erster Teil ist erledigt. Habe es noch noch live getestet, das mache ich dann morgen abend! Aber dann kann die Funktionalität wohl morgen schon in die Beta!

**Comment by mopsalarm** [comment]
Ist in der beta drin. Muss jetzt ausprobiert werden.

**Comment by mopsalarm** [comment]
Upload über url fehlt noch. Videos und gifs baue ich wahrscheinlich nicht ein.

**Comment by hmenke** [comment]
Hast du Lust und Zeit den URL-Hochlad auch noch zu implementieren?

**Comment by mopsalarm** [comment]
Aktuell nicht geplant. Kurz herunterladen und neu hochladen ist ja relativ schnell gemacht
