### ISSUE TITLE
Punkte beim Voten eines Kommentars updaten

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#54]
Die Punkte sollten beim Voten eines Kommentars upgedated werden.

**Comment by mopsalarm** [comment]
In dem Zusammenhang könnte das auch interessant sein: https://developer.android.com/tools/data-binding/guide.html#data_binding_layout_files

**Comment by X39** [comment]
vllt sollte ich die app anfangen zu nutzen ... dann würden sich solche fragen erübrigen:

wird momentan nicht + bzw. - 1 auf den punkte "zähler" gewählt?

**Comment by mopsalarm** [comment]
Nein, dort wird die Anzeige nicht upgedated. Das passiert aktuell nur bei den Punkten eines Posts.
