### ISSUE TITLE
Möglichkeit zur Anzeige des gesamten Benisgraphen (nicht nur die letzten 7 Tage)

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#55]
Find den Graph echt klasse. Nur wieso beschränkt man ihn auf 7 Tage? Wenn man die Daten hat Statistiken für mehr Tage anzuzeigen dann wüsste ich nicht wieso man das nicht auch tut.
Also ich denke mal der Grund wieso das bis jetzt nicht angezeigt wird ist, dass auf dem kleinen Platz dann nichts relevantes mehr zu erkennen wäre.
Ich würde daher vorschlagen über einen Klick auf den Graphen (anstatt diesem Popup) eine Vollbildansicht bzw. neue Seite zu öffnen in dem dann der gesamte Graph angezeigt wird in dem man dann auch rumzoomen kann.

**Comment by mopsalarm** [comment]
Moin,
ja das ist etwas, was eigentlich geplant ist, aber aufgrund von wichtigeren Features (Upload, User-Infos) von mir noch etwas zurück gestellt ist. Ich nehme aber natürlich gerne Pull-Requests an!

**Comment by mopsalarm** [comment]
Mit dieser Library kann man da bestimmt viel machen: https://github.com/PhilJay/MPAndroidChart

**Comment by mopsalarm** [comment]
Ich merge #159 jetzt und baue das noch etwas um.
