### ISSUE TITLE
Tags kleiner machen, mehr Platz für den Tagbereich und eine einstellbare MaxAnzahl an Tags

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#56]
Ich denke das Kernstück bzw. *die* Charakteristik des pr0gramms sind die Tags. In einem kürzlichen Update wurde da auch drangeschraubt. Ich hätte dazu mal einen Verbesserungsvorschlag:

* **Kleinere Tags** - also die Schriftgröße könnte beibehalten werden; nur dieses graue Rechteck in dem sich die Tags befinden könnte kleiner gemacht werden -> zB auf 1px Padding in jede Richtung (dient ohnehin eigentlich bloß der besseren optischen Separierung der einzelnen tags)
* **Mehr Platz für die Tags machen** - bis jetzt ist links eine große (je nachdem wie groß der Handybildschirm eben ist) ungenutzte Fläche unter dem "Hinzufügen"-Button. Ich würde vorschlagen den ganzen Bereich zu nutzen und den "Hinzufügen"-Button sozusagen als Eintrag in dem WrapPanel (oder was das ist) zu halten. Eventuell mit etwas mehr Abstand nach rechts. Falls das etwas unverständlich erklärt sein sollte kann ich auch gerne mal ein Screenshot hochladen bei dem ich das einzeichne.
* **Einstellbare Maximalanzahl angezeigter Tags** - einfach nur eine weitere Einstellung in der man einstellen kann wieviele Tags maximal angezeigt werden sollen. Das kann man dann mit den anderen neuen Optionen aus dem Update kombinieren. Beispielsweise wenn man viele Tags - wenn möglich alle - Tags sehen möchte aber eben auch eine Beschränkung für Tagexzesse setzen möchte.

Außerdem habe ich bei mir einen kleinen Bug (mehr oder weniger) gefunden - habe die Votebuttons bei den Tags ausgeblendet, wenn ich sie einblende passen die Votebuttons häufig nicht mehr in dieselbe Zeile und sind dann abgeschnitten (so dass ich den + Button zu etwa 1/4 sehe und den - Button gar nicht mehr). Da wäre es also eigentlich nötig für Umbrüche den Platz der Votebuttons miteinzuberechnen. Auch für dieses Problem wäre es gut die Tags kleiner zu machen und mehr Platz für diese zur Verfügung zu stellen: ich glaube einige Tags würden derzeit selbst wenn sie in einer eigenen Zeile stehen würden nicht rein passen...

**Comment by mopsalarm** [comment]
Ich denke das Kernstück bzw. die Charakteristik des pr0gramms sind die Tags.

Interessant, ich finde die Tags nur so mäßig interessant, die Kommentare sind mir persönlich wichtiger. Aber um auf deine Vorschläge einzugehen: "Kleinere Tags" klingt zwar erstmal ganz gut, aber das Problem ist, dass wir hier eine für Touchscreens optimierte App entwickeln. Je kleiner die Tags und je weniger Padding, desto schwieriger ist es, sie mit dem fetten Daumen anzuklicken.

"Mehr Platz für die Tags machen" Den Vorschlag finde ich schon umsetzbarer. Ich hab die App selbst auf Englisch, bei mir steht da nur "Add", was sehr viel kürzer ist. Das ist leider kein Wrap-Panel oder ähnliches, sondern eine RecyclerView. Dort ist es sehr einfach, homogene Daten hineinzufüllen, verschiedene Dinge (Button + Tags) jedoch schwieriger (natürlich nicht unmöglich, nur Aufwand!). Die Option werde ich aber denke ich weiter verfolgen!

"Einstellbare Maximalzahl..." Ich habe heute die maximale Anzahl an Zeilen von Tags auf drei reduziert. Man kann mehr Tags sehen, indem man zur Seite scrollt. Das finde ich auch einen guten Kompromiss.

Ich habe jetzt "Hinzufügen" schonmal durch "Neu" ersetzt, wodurch viel mehr Platz da sein sollte. Und sobald ich wieder Zeit habe, kümmere ich mich darum, den Button mit in die RecyclerView hineinzupacken. MergeAdapter lässt grüßen.

Neue Beta kommt heute Abend noch, kannst mir dann ja mal Feedback geben!

**Comment by mopsalarm** [comment]
So wie es geht ist, ist es okay, oder?

**Comment by mYnDstrEAm** [comment]
Ja - echt klasse: danke!
