### ISSUE TITLE
Benisgraph wird bei jedem Logout zurückgesetzt

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#57]
Mehr oder weniger ein Bug. Weiß jetzt nicht ob das auch (#55) schon bekannt ist, stells aber einfach mal als Issue rein.
Falls die Daten mit Name & Passwort zusammen gespeichert werden müssten die separat gespeichert werden und nur den Nutzername (oder einen Hash des Namens oder verschlüsselt falls die Daten bisher aus Datenschutzgründen verworfen wurden) als Zuordnung haben.

Auch das Laden der bisherigen Votes könnte wegfallen (obwohl das jetzt nicht *so* viel Zeit benötigt)....wäre sowieso mal daran interessiert was man da eigentlich bekommt (theoretisch könnte man dadurch ja als quasi extra Statistikpunkt die Anzahl eigener Up/Downvotes [und das Verhältnis] anzeigen - und die Anzahl der Votes über Nutzernamen anzeigen [also +4 wenn man Beiträge eines Nutzers 5x hoch und 1x runter gevotet hat; wenn das mit den Daten möglich ist wäre das echt ne feine Sache, die es übrigens auch in der [RES](http://redditenhancementsuite.com/) gibt]).

**Comment by mopsalarm** [comment]
Eigentlich war das ein Feature, kein Bug. Ich lösche den Benis Graph aktiv beim ausloggen. 
Du bekommst nur die ids von den posts bzw Kommentaren, damit kann man aktuell so eine Statistik, wie du sie gerne hättest, nicht umsetzen. 

Ich werde drüber nachdenken die Daten zusammen mit einer Identifikation zu speichern, damit sie  wiederherstellbar sind

**Comment by mYnDstrEAm** [comment]
Wurde im neuesten Update geändert (danke!).
Eine kleine Sache müsste aber noch geändert werden: wenn man auf *Logout* klickt steht in dem Pop-up Fenster "Deine Benis-Historie geht dabei unwiderruflich verloren" drinnen...

**Comment by mopsalarm** [comment]
Da hast du recht, das werde ich noch rausnehmen. Habe momentan aber leider wenig Zeit, an der App zu arbeiten.
