### ISSUE TITLE
Möglichkeit zur Anzeige von Kommentaren auf Nutzerseiten

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#58]
Bis jetzt sieht man da nur die Anzahl der Kommentare etc. und die Uploads.

**Comment by mopsalarm** [comment]
Ja, kommt denke ich noch

**Comment by mopsalarm** [comment]
Erste Version Ist in der aktuellen Beta. Nicht hübsch, aber läuft. Muss ich morgen überarbeiten!

**Comment by mopsalarm** [comment]
Ist ja schon lange überarbeitet. Aber es müsste noch ne Möglichkeit geben, alle Kommentare eines Benutzers anzuzeigen.

**Comment by X39** [comment]
wie wärs mit einem tab system?
in etwa:
|Bilder|Favos|Kommentare|

default wäre bilder ausgewählt und anschließend könnte man den "fokus" ändern mithilfe der jeweiligen auswahl

durch die tabisierung hätte man die scrollDown sache noch frei und könnte somit auch autonom kommentare etc. nachladen

**Comment by schr3j** [comment]
Ein Tab System fände ich auch besser als die aktuelle Lösung. Eventuell könnte man auch in Lollipop manier die komplette User Info mit dem Hintergrund der Actionbar versehen und unten die Tabs anfügen. Wenn man hochscrollt verschwindet dann die User Info und nur die Tab Bar bleibt. So ähnlich wie es mal in der Telefon App war.
Dazu müsste man allerdings die Userinfo in eine eigene Activity bzw. ein eigenes Fragment auslagern denke ich, und nicht nur beim FeedFragment oben noch die Userinfo einfügen...

**Comment by mopsalarm** [comment]
Mag vielleicht jemand mal Mockups basteln? Kann mir noch nicht so richtig vorstellen, wo dann alles wäre.

**Comment by schr3j** [comment]
Sowas in die Richtung hätte ich mir vorgestellt ;)
Das Kamerasymbol passt nicht, stellt euch statt dessen einen Briefumschlag vor :grin: 
![new-user-info-mock](https://cloud.githubusercontent.com/assets/1710904/9294033/becd58aa-4440-11e5-8052-7bcc17698728.png)

**Comment by mopsalarm** [comment]
Interessant. Das wird kompliziert, aber könnte man vllt machen...

**Comment by schr3j** [comment]
Der Benisgraph muss natürlich auch nicht durch die Tabs durchgehen, dann wird das vielleicht einfacher. Die Tabs müssen halt nur die Farbe des Graphen als Hintergrund haben.

Außerdem war die Idee dass der Username beim Hochscrollen in die ActionBar wandert und alles außer den Tabs eingeklappt wird.

**Comment by X39** [comment]
Warum sollte es schwieriger sein den benisgraphen "durch" die tabs laufen zu lassen als ihn das nicht tun zu lassen?
transparenter hintergrund wird ja wohl im UI framework von android vorgesehen sein (bin hier mit meinen UI künnsten eher ... nennen wir es mal anfänger https://github.com/X39/Pr0Notify/tree/master/pr0notify da das ganze UI gedöns für mich sich nicht transparent erschließt)

**Comment by mopsalarm** [comment]
Komplettes umdesignen lasse ich erstmal weg. Es werden jedoch inzwischen mehr Kommentare angezeigt.
