### ISSUE TITLE
Play store

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/Pr0#59]
Die App ist wirklich bedeutend besser als *pr0gramm super* - die *Masse* der (Android) Nutzer wird aber nicht das benutzen was am besten ist, sondern eben das was man über den Play store bekommt.
Falls das bisher nicht gemacht wurde...

* ...weil man dazu einen Play store Account braucht (und/oder wegen dem Eintrittsgeld) wird sich dazu auf pr0 sicher jemand finden der bereit ist seinen eigenen Account dazu zur Verfügung zu stellen (hab selbst leider noch keinen).
* ...weil es bei der hohen Updatefrequenz zu umständlich wäre könnte man das ja später machen. [So langwierig scheint es aber nicht zu sein](https://support.google.com/googleplay/android-developer/answer/113476?hl=en).
* ...weil der Play store "pornography or sexually explicit content" etc. [verbietet](https://support.google.com/googleplay/android-developer/answer/113474?hl=en) [2](https://play.google.com/about/developer-content-policy.html) (ich vermute mal dass das der Grund ist...zumindest hatte ich glaub mal gelesen dass es deswegen in *pr0gramm super* nicht möglich ist den NSFW & NSFL Bereich einzublenden) dann ist das glaub ich auf den Inhalt *der App selbst* - und nicht auf jeglichen mit der App darstellbaren Inhalt bezogen. Ich bin mir da ziemlich sicher, da zB auch *reddit is fun* (oder auch jede 4chan App) erlaubt ist mit der man genauso nicht-jugendfreie Inhalte abrufen kann. Hab jetzt eben dazu nochmal bisschen recherchiert und [das hier gefunden](https://www.reddit.com/r/Android/comments/r3dhg/reddit_is_fun_banned_fo...) - falls es also *doch* Probleme geben sollte (was ich jetzt nicht glaube) ist das ja kein Beinbruch - ich würde das dann eben genauso klären wie es im Top-Kommentar des verlinkten Threads beschrieben ist (und den NSFW & NSFL Bereich per default natürlich weiterhin deaktiviert lassen).

**Comment by Graphicscore** [comment]
Da kommen wir nicht rein , ich hatte es ja damals mit "meiner" APP probiert , die wurde direkt gesperrt weil ich angeblich Identitätsdiebstahl betreiben würde lächerlich. Der Google Support lässt da auch nicht mit sich reden hatee auf mein Support Ticket nie eine Antwort bekommen.

**Comment by mYnDstrEAm** [comment]
@Graphicscore Stand da noch irgendwas dabei? Und gibt es nicht noch eine andere Möglichkeit mit denen Kontakt aufzunehmen abgesehen von diesen Tickets?   Habe jetzt aber grade nochmal nachgeschaut: in den ganzen 4chan Apps muss man die NSFW Boards anscheinend manuell hinzufügen. Wobei man bei *reddit is fun* (und wahrscheinlich auch bei den anderen Apps obwohl ich da jetzt nicht nachgeschaut hab) einen NSFW-Filter in den Settings hat - also ganz ähnlich zu pr0. Eventuell haben die das aber bloß auf Druck der Masse an Redditnutzern erlaubt...
Wobei dann immer noch offen ist wieso die das aufgrund von "Identitätsdiebstahl" anstatt der anderen Regelverletzungen gesperrt haben.

**Comment by mopsalarm** [comment]
Aber habe ihr damals nicht gesagt, ihr hättet eure App in den store bekommen? 
Account anlegen wäre nicht das Problem für mich. Ich glaube, die Updatefunktion, die ich jetzt drin habe, müsste dann raus - die wäre aber dann natürlich auch überflüssig.

**Comment by mopsalarm** [comment]
@Graphicscore?

**Comment by schr3j** [comment]
Ich hätte auch einen Account. Wenn du möchtest kann ich dich da als Administrator für die Pr0 App hinzufügen und wir probieren das mal aus.. :grin:

**Comment by mopsalarm** [comment]
Ausprobieren könnten wir das mal.

**Comment by Graphicscore** [comment]
Wenn die die App sperren, ist direkt der ganze package name gesperrt, dh. dass man dann schonmal den package namen ändern muss. Wenn die das sperren, kann man bei den Devs einen appeal request machen, also ein ticket eröffnen und die prüfen dass dann noch mal. Hatte ich damals gemacht, aber nach 3 Wochen immer noch keine Antwort von dem Dev Team erhalten.

**Comment by schr3j** [comment]
Der Package name ist dann komplett gesperrt? Oder nur für den Play Store?

**Comment by mopsalarm** [comment]
Es gibt noch ein paar Sachen zu tun.

* update Feature innerhalb der App deaktivieren bzw raus nehmen, wenn es sich um dir PlayStore Variante handelt. Bzw mit Verspätung, falls die App aus dem  PlayStore gelöscht wird. 
* der Paketname ist aktuell com.pr0gramm.app. Vllt sollte der auf geändert werden? io.github.mopsalarm.pr0gramm zb... Aber dafür gibt es eine Einstellung in dem gradle plugin, soweit ich weiß. Weiß aber nicht ob das nötig ist. 
* Bilder fehlen noch, sagt die Seite. Ich muss gucken, weiß nicht ob ich heute Zeit finde, bin noch verabredet.

**Comment by schr3j** [comment]
Wenn du es schaffst ein SVG des App-Icons hochzuladen füge ich die Bilder ein. Screenshots sind schon drin.

**Comment by mopsalarm** [comment]
SVG habe ich jetzt drin im repo. Ein Icon habe ich auch schon online gestellt. Fehlt noch das "Feature Graphics"

**Comment by schr3j** [comment]
Gut. Der Store Eintrag ist jetzt vollständig. Jetzt fehlt halt noch die APK damit der Inhalt eingestuft und die App veröffentlicht werden kann.

**Comment by mopsalarm** [comment]
Jo, muss ich aber noch anpassen  und mit einem korrekten key signieren...

**Comment by schr3j** [comment]
Ja. Apropos. Die ganzen Librarys die du verwendest. Sind die alle noch nötig? Ich würde nämlich was einbauen um die auch irgendwo vorbildlich anzuzeigen...

**Comment by mopsalarm** [comment]
Klar sind die nötig, sonst würde ich sie ja nicht verwenden ;) kannst in
den preferences eine weitere preference Untergruppe/screen einbauen, wie
die anderen, und dort links zu den libraries über view intents setzen.
Müsste ohne eine Zeile Code gehen.

**Comment by schr3j** [comment]
Hmm ich hätte jetzt ne Activity gebaut die alle Libraries mit Autor und Lizenz untereinander anzeigt. Befüllt mit nem JSON. Je nachdem wie es dir lieber ist.

Hätte ja sein können dass du eine der Libraries nicht mehr verwendest und vergessen hast sie zu löschen ;) bevor ich dazu unnötigerweise die Lizenz raussuche

**Comment by mopsalarm** [comment]
Naja mach wie du möchtest, solange es ma Ende schön ist ;)  hier noch ein
Tipp: https://github.com/PSDev/LicensesDialog/blob/master/README.md

**Comment by mopsalarm** [comment]
Und dann müsste ich am Ende mal gucken ob die Lizenzen alle zueinander
kompatibel sind! *hust*

**Comment by schr3j** [comment]
Ah, man kann die Lizenzen da ja über XML füttern. Ausgezeichnet. Das werd ich dann mal verwenden ;)

**Comment by mopsalarm** [comment]
Und die Bibliothek scheint schon viele Lizenzen direkt mitzubringen.

**Comment by schr3j** [comment]
Falls aber eine Lizenz nicht dabei ist ist die Library ganz schön scheiße. Man müsste für jede zusätzliche Lizenz ne eigene Klasse und diverse Ressourcen hinzufügen und die dann vorm Dialog öffnen extra hinzufügen.

**Comment by mopsalarm** [comment]
Das finde ich aber nicht so schlimm. Immerhin ist sie erweiterbar. Habe schon so manche library gehabt, die an kritischen stellen dann final war oder private oder package private Konstruktoren oder Methoden hatte.

**Comment by mopsalarm** [comment]
Ich denke, morgen kann ich mich da weiter drum kümmern. Möchte vor Release im PlayStore noch folgende Punkte erledingen: #73  und #74 sowie #60

**Comment by mopsalarm** [comment]
Erste Version ist unter "pr0gramm navigator" online.

**Comment by schr3j** [comment]
https://play.google.com/store/apps/details?id=io.github.mopsalarm.pr0gramm.gp

**Comment by NoxNebula** [comment]
Gleich mal ge-fünf-sternt.
Soll sie dann noch in pr0gramm o.ä. umbenannt werden?

**Comment by mopsalarm** [comment]
Wahrscheinlich erstmal nicht. Das soll abgrenzen, dass es sich nicht um eine "offizielle" App handelt - auch auf cha0s Wunsch hin. Aber in deinem Appdrawer im Handy müsste sie als pr0gramm angezeigt werden.

**Comment by Graphicscore** [comment]
Kriegste eh net hin  , dann wird sie gesperrt weil die "zu ähnlich" zu der
anderen APP ist ^^

Patrick Kleinschmidt <notifications@github.com> schrieb am Do., 11. Juni
2015 11:13:

**Comment by Graphicscore** [comment]
@mopsalarm Ist die PS Version die gleiche wie die Offline version ?

-Send from mobile

**Comment by schr3j** [comment]
Oh yeah wir farmen die 5 Sterne. Haben schon 2 stück :grin: 
Falls ihr alternative Namensideen habt, nur her damit.

die PS hat den Updater standardmäßig deaktiviert...

**Comment by Graphicscore** [comment]
@schr3j Das heißt ihr müsst die updates alle manuell im Playstore hochladen :) :+1:  , Aber vom Funktionsumfang (Updater mal abgesehen) sind die Versionen identisch oder ?

**Comment by schr3j** [comment]
@Graphiscore Wie müssen sie sowieso manuell in den Store laden. Es gibt halt nur 2 verschiedene Versionen die auch unterschiedlich signiert sind. Wenn es mit dem Store klappt wird aber die manuelle Version an die Store Version angeglichen.
Ja, der einzige Unterschied ist der Updater, sonst sind sie identisch bzw. werden identisch (ich glaub das @m0psalarm die aktuelle Version noch nicht in pr0gramm-updates eingefügt hat).

**Comment by mopsalarm** [comment]
Die Apps sind fast identisch, der Funktionsumfang ist der gleiche. Ich hab nur mit der Versionnummer verkackt, die App ist die gleiche wie die aktuelle Beta Version.
Die Updatefunktion ist in der Playstore Variante weiterhin aktiv, jedoch will ich die Updates über den Playstore ausrollen. Die Funktion ist als Backup gedacht, falls die App aus dem Playstore entfernt wird, damit man dann weiter Updates machen kann.

Für das Hochladen in den PlayStore will ich noch soetwas einbauen: https://github.com/Triple-T/gradle-play-publisher damit ich das nicht per Hand machen muss ;)

**Comment by mopsalarm** [comment]
Schon 25 Benutzer!

**Comment by schr3j** [comment]
Mittlerweile 125 Benutzer! Und wir sind das 3. Ergebnis im Playstore und haben damit pr0gramm super überholt :grin: 
![PlayStore](https://cloud.githubusercontent.com/assets/1710904/8227161/0c4ed402-15a5-11e5-919c-cb823a3ad5f9.png)

**Comment by mopsalarm** [comment]
Kommt zwar noch nicht an die Benutzer der anderen Version ran, aber die PlayStore Variante ist ja auch noch nicht beworben

**Comment by mopsalarm** [comment]
Ich bekomme einen error 505 beim update auf die aktuelle beta. Geht euch das auch so?

**Comment by mopsalarm** [comment]
Hat sich erledigt. Der ShareProvider hatte die gleiche authority in beiden App versionen. Habe das jetzt geändert, und sobald die Installation der Beta aus dem PlayStore funktioniert, publishe ich die neue Version als neues Release!

**Comment by schr3j** [comment]
Wir sind mittlerweile Platz 2 im PlayStore, haben 366 installs und 5 Sterne bei 10 Bewertungen. Und das ganze immer noch ohne die App zu bewerben :+1:

**Comment by mopsalarm** [comment]
Von den 366 Installs haben aber nur etwa 250 die App gestern benutzt, laut Crashlytics.  Zum Vergleich: die andere Version hat laut Crashlytics gestern 2900 Benutzer gehabt. Die Zahl ist auch  nicht wirklich heruntergegangen seit die Version im PlayStore ist, was schön ist. Eigentlich könnte man die PlayStore Version langsam bewerben. Ich überlege, ob ein übertragen der Lesezeichen und Einstellungen notwendig ist. Wäre aber eine Idee,die ich vorher noch ausprobieren wollen würde.

**Comment by Jaglag** [comment]
Hmm warum wurde die app ausm store entfernt?

**Comment by schr3j** [comment]
@Jaglag Entweder hat Google die NSFW Einstellungen in den Settings gefunden, ein Google Mitarbeiter hat einen Account und uns verraten, jemand hat die App gemeldet und bewiesen dass nudity in der App vorkommt oder ich bin schuld, da ich in nem neuen Rating Formular angegeben habe dass es auch möglich sein kann das Nudity vorkommt.

@mopsalarm und ich müssen jetzt entscheiden wie wir vorgehen, eventuell müssen wir die NSFW/NSFL Einstellungen in ein Plugin verpacken damit es mit der PS Version alleine nicht mehr möglich ist diese Inhalte zu konsumieren, allerdings werden wir dann natürlich nicht den Breezle machen sonder das geschickter anstellen. Ansonsten können wir nochmal versuchen direkt Revision einzulegen da ja prinzipiell keine Nacktheit vorkommt wenn man nicht eingeloggt ist und es dann vllt auch so geht. Mal sehen.

**Comment by mopsalarm** [comment]
Ich habe schon überlegt, vllt ist es klüger, einfach eine pr0gramm
navigator installer App zu veröffentlichen, die einfach nur die normale
github Version installiert. Das müsste ja eigentlich sich möglich sein,
oder?

**Comment by Jaglag** [comment]
Lustigerweise is die app ziemlich direkt nach dem Blog Beitrag auf cashys Blog down gegangen. 
Ich wäre für einen Einspruch und entfernen des nudity Tags da ohne Login nsfw ja eh gesperrt ist und aktuell ein sign up nicht möglich ist

**Comment by Jaglag** [comment]
btw hier der link zum Beitrag:

http://stadt-bremerhaven.de/pr0gramm-navigator-open-source-app-fuer-pr0gramm/

schätze mal das wurd direkt danach reported....
Wie gesagt würd da Einspruch erheben da es keine Nudity in der App so wie sie ist gibt.

**Comment by mopsalarm** [comment]
Oh gott, das habe ich gar nicht gesehen. Dann hat uns sicher jemand darüber reported. Deppen!

**Comment by mopsalarm** [comment]
Habe mal ein appeal gestellt, aber es wurde nur ein "Wir melden uns, wenn wir mehr Daten benötigen, oder es etwas zu berichten gibt" bekommen. Ichd enke nicht, dass ich da wieder was von hören werde. Nun gibts zwei Möglichkeiten:
* Nochmal die App in den Playstore unter einam anderen Paketnamen. Das heißt, dass es wirklich eine "neue" App ist, und sie könnte jederzeit wieder gesperrt werden.
* Eine Installer-App, die hoffentlich drin bleibt, und einfach nur die Github Version der App herunterlädt und installiert. Ähnlich zu https://play.google.com/store/apps/details?id=com.maartendekkers.cmapp&hl=en
* Plugin System für nsfw/nsfl

Ich persönlich bin für nummer Zwei, wie seht ihr das?

**Comment by Jaglag** [comment]
ich vote für 3 
keine ahnung warum aber ich mag das über gplaystore gemanaged haben.
Wenns mehr stimmen für 2 gibt nehm ich auch 2

**Comment by NoxNebula** [comment]
Verstehe ich nicht, mit jedem Webbrowser im play store kann man auch einfach porn oder Gore angucken und da wird nix gesperrt.

**Comment by schr3j** [comment]
Also: ich glaube dass ich schuld bin, da ich im neuen Rating Formular Nudity ausgewählt habe und das ist prinzipiell verboten. Weder Caschy noch Breezle hat was damit zu tun. Ca. 3min nachdem ich das Formular ausgefüllt habe kam der ban, vermutlich also automatisch...

**Comment by mopsalarm** [comment]
Hm, Mist. Naja nicht zu schlimm. Wie ihr vllt gesehen habt, has das update gestern auch ohne PlayStore funktioniert. Das einzige Problem ohne PlayStore ist die User Akquise. Aber aktuell waren es gestern etwa 4k User über beide Apps summiert. Ich gehe hier in Feedback Mails unter... ;)  
Ich setze mich, Wenn ich wieder Zeit habe, dran, Funktionalität the den Wechsel von einer packageId auf ne andere zu vereinfachen.

**Comment by schr3j** [comment]
Es wäre mir btw. recht wenn wir nicht zu viele Strikes sammeln :grin:
Nochmal neu ist natürlich kein Problem, aber dann bitte richtig. Und wenn sie zum 2. mal gebannt wird würde ichs lassen, da sie dann vllt auf die Idee kommen den Account zu sperren...

**Comment by mopsalarm** [comment]
Ja klar

**Comment by mopsalarm** [comment]
Wie @schr3j gestern sehr schön zusammengefasst hat: we are back, bitches!
