### ISSUE TITLE
Nachricht an sich selbst

### ISSUE THREAD

**Issue by xxFxDx** [mopsalarm/Pr0#60]
Wenn man versucht, eine Nachricht an sich selbst zu schreiben, kommt die Nachricht, dass man offensichtlich gebannt sei. Wenn man in seinen Kommentaren zu einem Bild geht, wird das bild normal geladen, evtl sollte zum Kommentar gesprungen werden/ der Kommentar hervorgehoben werden.

**Comment by mopsalarm** [comment]
Das sind zwei Sachen, die auf jedenfall noch getan werden müssten ;)

**Comment by mopsalarm** [comment]
Habe es gesplittet. Siehe #61
