### ISSUE TITLE
Fancy animations

### ISSUE THREAD

**Issue by schr3j** [mopsalarm/Pr0#63]
Nachdem ja in Material die Animationen so furchtbar wichtig sind, wäre es doch ganz nice, wenn auch in der App hier Animationen eingebaut wären. Insbesondere wenn man Bilder antippt wäre es doch super wenn das Bild dann einfach hochskaliert würde anstatt dem abgehackten Übergang.
Ich wollte mir das ganze eh mal anschauen, vllt bekomm ich ja was auf die Reihe.

https://developer.android.com/training/material/animations.html
http://stackoverflow.com/questions/26688374/android-activity-transitions-using-support-v4-up-to-date-with-android-l

**Comment by mopsalarm** [comment]
Habe ich auch schon mal dran gedacht. Problem ist, dass das Vorschaubild beschnitten und quadratisch kommt, und das große Bild dann ein anderes Seitenverhältnis hat. Habe schon an nen Service gedacht, der einem diese Zusatzinfos bereit stellen könnte

**Comment by schr3j** [comment]
Wenn das klappt wäre das natürlich ideal. Ansonsten könnte man es ja einfach vorerst auf ca. 16:9 croppen und dann sobald das eigentliche Bild geladen ist animiert auf die richtige Größe aufziehen lassen.
Ich weiß allerdings nicht genau wie schwierig es wird die Transitions einzubauen da ja der größte teil des Layouts dynamisch geladen wird...

**Comment by mopsalarm** [comment]
Auf https://developer.android.com/training/material/animations.html steht: "For shared dynamic views that you generate in your code, use the View.setTransitionName() method to specify a common element name in both activities." Also es geht wohl auch dynamisch.

16:9 ist nicht so gut, dann eher 1:1, das ist ja auch das Seitenverhältnis des Vorschaubildchen.

Habe cha0s mal gefragt, ob er die Größen in den Feed hineni nehmen kann, ist aber aufgrund der Architektur nicht so einfach möglich. Aber ein MetaData Service wäre echt gar nicht so schlecht. Dann könnte man z.B. auch Bilder, die als "repost" oder ähnlich getaggt sind, bereits im Feed hervorheben.

**Comment by schr3j** [comment]
Ja ich hätte nur 16:9 genommen damit das Bild/Video dann nicht auf eine kleinere Größe animiert wird sondern wenn dann größer. Ich denke das sieht besser aus ;)

Prinzipiell wäre es doch ganz nett so kleine Badges im Feed zu haben mit Repost, OC etc.

**Comment by mopsalarm** [comment]
Könntest du recht haben. Probierst du das mal aus?

**Comment by schr3j** [comment]
Ich werde es auf jeden Fall mal versuchen wenn ich Zeit hab ;)

**Comment by mopsalarm** [comment]
Je nachdem, wie viel Zeit ich morgen Abend habe, habe ich dann einen Service, der die Bildgröße zu einer Liste von Posts zurück gibt.

**Comment by mopsalarm** [comment]
Soo, Hier ist ein Beispiel, aber die Datenbank Updated sich aktuell nicht: http://46.101.134.19:5003/items/824809/824939

Man bekommt die Größen aller Bilder/Videos mit IDs zwischen den angegebenen IDs und weitere Informationen. Aktuell bekommt man weiterhin eine Liste mit den IDs aller Reposts in dem Bereich (sprich, aller Posts mit einem Tag "repost").

Der Code ist bereits online: https://github.com/mopsalarm/pr0gramm-meta

**Comment by mopsalarm** [comment]
Es gibt nun einen MetaService in der App, der die Information liefert. Jetzt fehlt nur noch vernünftiges weiterverarbeiten.

**Comment by mopsalarm** [comment]
btw die URL ist jetzt: http://46.101.134.19:5003/items?ids=824809,824810,824811

**Comment by mopsalarm** [comment]
Die Daten sind heute in den FeedAdapter gewandert. Man kann sie mit Optional<ItemSize> getItemSize(FeedItem item) abfragen.

**Comment by mopsalarm** [comment]
Habe da mal was gemacht, allerdings ohen die korrekte Zielgröße. Es funktioniert, stottert aber auf meinem Telefon. Vielleicht kann das mal jemand von euch ausprobieren? Hier eine aktuelle Version, die das enthält: https://www.dropbox.com/s/ql42uplh58k8vlb/app-open-release.apk?dl=0

**Comment by schr3j** [comment]
Ruckelt ganz schön auf meinem Nexus 5 mit Android M...

**Comment by mopsalarm** [comment]
Ich arbeite dran...

**Comment by mopsalarm** [comment]
Was ich gestern noch gemacht habe, was auch richtig geil aussieht: https://www.dropbox.com/s/v7wz9tm45zjuv5z/2015_06_14_17_14_01.mp4?dl=0

Geht aber leider nur, wenn das Bild kein "musste scrollen"-Bild ist

**Comment by mopsalarm** [comment]
Okay, neue Version. Habe ziemlich gekämpft mit dem System, und hübsch ist es noch nicht, aber müsste eigentlich funktionieren. Animationen sind ganz smooth bei mir und parallax-scrolling sollte auch da sein für "kleinere" Bilder. Kleinere Bildfehler sind zu erwarten. Etwas Feedback wäre super, bevor ich das der Masse zugängig mache:

https://www.dropbox.com/s/t12chb5owju9kju/app-open-release-2.apk?dl=0

**Comment by schr3j** [comment]
Bei mir laufen die Animationen auch sehr sehr flüssig (bis auf seltene Ruckler bei WEBMs). Noch cooler wäre es wenn auch beim zurück navigieren die Animation umgekehrt stattfinden würde ;)

**Comment by mopsalarm** [comment]
Für alle ohne Android 5+   https://www.dropbox.com/s/x0k5npr3seiuroc/2015_06_16_06_32_53.mp4?dl=0

**Comment by mopsalarm** [comment]
Beta mit eventuellem speicherleck ist raus!

**Comment by schr3j** [comment]
Endlich mit Profis :joy:

**Comment by mopsalarm** [comment]
Falls jemand Lust hat zu prüfen, wo bzw ob da ein Leck ist, immer ran an den Speck. Ich weiß nicht wie viel Zeit ich heute Abend habe. Werde mich sonst dann der Sache annehmen und gucken, dass ich die letzten Bugs da auch noch raus bekomme.

**Comment by mopsalarm** [comment]
Okay, sieht nicht so aus als hätten wir einen Speicherleck. Alles soweit okay nach ersten Untersuchungen! :+1:

**Comment by mopsalarm** [comment]
Gestern noch mehrere overdraw Probleme behoben. Nun fehlt nur noch ein Layout Problem auf pre 5.0 Geräten.

**Comment by mopsalarm** [comment]
So, ich würde sagen, erstmal abgeschlossen. Jedenfalls bis die ersten Fehlerberichte eintrudeln.
