### ISSUE TITLE
Kommentarlinien

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#64]
Wie auf der Webseite

**Comment by schr3j** [comment]
Ich hab das mal ausprobiert, funktioniert soweit ganz gut. Allerdings hauts das komplett auseinander sobald ich das scrollen anfange.. irgendwie setzt er dann komplett zufällig die Tiefe...

**Comment by mopsalarm** [comment]
Hast du das in deinem repository? Wenn ich Zuhause bin, würde ich das mal
ausprobieren!

**Comment by schr3j** [comment]
Ich habs jetzt. Ich hab nicht geschnallt dass er die Listenelemente wiederverwendet und ich meine Spacer entsprechend wieder entfernen muss. Das funktioniert jetzt. Das einzige was noch nicht klappt ist das nötige Margin aber das bekomm ich noch auf die Reihe und mach dann einen PR dann kannst du das mal anschauen.

**Comment by mopsalarm** [comment]
Habe es jetzt gemerged und auf das LinearLayout verzichtet. Danke!
