### ISSUE TITLE
Fab

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#65]
Material Design Floating Action Button für Upload und Kommentar schreiben. Beide in den Settings einstellbar.

**Comment by X39** [comment]
kleiner beitrag hierzu:
https://medium.com/tech-in-asia/material-design-why-the-floating-action-button-is-bad-ux-design-acd5b32c5ef

ist es wirklich sinnvoll nen FAB zu nutzen?

**Comment by schr3j** [comment]
@X39 Das ist nur eine Meinung. Ich z.B. finde die FABs gar nicht so schlecht. Finde ihn aber zumindest für Bilder Upload absolut unpassend da man diese Funktionalität mit abstand am seltensten nutzt. Auf einen FAB zum Kommentieren könnte man sich einigen, finde ich aber auch nicht so gut, da ist das inline schon besser.

**Comment by mopsalarm** [comment]
Vielleicht zum Nachrichten schreiben? Aber okay, sonst lasse ich den FAB einfach raus, ist ja nur ne Idee gewesen.

**Comment by X39** [comment]
>Vielleicht zum Nachrichten schreiben?

wäre tatsächlich eine gute idee da sich hier ein FAB anbieten würde

beim profil eines nutzers ist ja schließlich der nutzer selbst im vordergrund und da der nutzer "kaum" informationen bereithält würde ein FAB nicht stören
