### ISSUE TITLE
Falsche Benachrichtigung bei Filtereinstellung

### ISSUE THREAD

**Issue by xxFxDx** [mopsalarm/Pr0#66]
Wenn man einen pr0-internen link öffnet, der aus ein Bild führt, das nicht innerhalb der Filtereinstellungen liegt, wird man nicht darüber benachrichtigt (das Bild ist NSFW/NSFL) sondern bekommt nur die allgemeine Nachricht, dass der Feed nicht geladen werden konnte.

**Comment by mopsalarm** [comment]
Stelle gleich noch eine Beta online. Wenn du verifizieren könntest, dass es jetzt besser funktioniert, wäre das super.

**Comment by xxFxDx** [comment]
Jop, Hinweis auf Filtereinstellungen ist jetzt sichtbar.

**Comment by mopsalarm** [comment]
Danke
