### ISSUE TITLE
Probleme beim anzeigen übergroßer gifs

### ISSUE THREAD

**Issue by xxFxDx** [mopsalarm/Pr0#69]
Der Post http://pr0gramm.com/top/Dickbutt/827950, der eine große gif ist, wird nicht geladen.  (HTC One M7) Funktioniert nicht, unabhängig davon wie die Option gif zu webm konvertieren gewählt ist.

**Comment by mopsalarm** [comment]
Hm, das stimmt wohl. Aber ich denke, damit müssen wir leben. Der Aufwand ist es denke ich nicht wert. Das kommt ja auch nicht so oft vor.
