### ISSUE TITLE
NSFW/NSFL nur für angemeldete Nutzer

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#70]
Habe nochmal bei cha0s nachgefragt.

**Comment by schr3j** [comment]
Evtl. sollten wir es im Hinblick auf den PlayStore auch die Einstellungsoptionen verstecken wenn man nicht angemeldet ist...

**Comment by mopsalarm** [comment]
Ja, Könnte man noch so machen, das stimmt.
