### ISSUE TITLE
Erweiterung rep0st-check

### ISSUE THREAD

**Issue by xxFxDx** [mopsalarm/Pr0#71]
Nachdem die Bilder nun schon als reposts erkannt werden, wäre es doch möglich, einen Button einzubauen, der einen zum Original führt? Wäre praktisch um tags zu ergänzen, da man über diese nicht immer zum Original kommt.

**Comment by mopsalarm** [comment]
Die Daten habe ich nicht. Als Repost markiert wird nur, was sich als Repost
getaggt ist.
