### ISSUE TITLE
SFW+ Button in die Actionbar

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#74]
Eines der meist gewünschten Features - Schnelles umschalten zwischen sfw, nsfw und nsfl in der Actionbar im Feed. Mit mit nem kleinen Icon und ner checkliste-Popupmenu beim antipppen.

**Comment by schr3j** [comment]
Ich bastel da grad dran rum. Bin grade dabei den refresh nach dem Auswählen zu implementieren. Dabei bin ich auf was gestoßen:

Aktuell wird der ContentType ja im FeedFilter gespeichert. Ist das so sinnvoll? Sollten nicht jederzeit immer die aktuellen Einstellungen verwendet werden? Falls dem so ist wäre die Implementierung des Refresh etwas leichter und ich fände das Verhalten dann auch logischer...

**Comment by mopsalarm** [comment]
Was wäre denn dein Vorschlag? Direkt im Feed Service auf Settings zu gehen?
Die refresh Implementierung sollte doch eigentlich einfach fallen, da die
schon existieren müsste? Siehe onResume in dem FeedFragment

**Comment by schr3j** [comment]
Tatsache. Trotzdem könnte man eigentlich auch auf die Settings gehen, das wäre logischer (finde ich zumindest).

**Comment by mopsalarm** [comment]
Ich sehe deinen Punkt, möchte das jedoch nicht wirklich über dir Settings
lösen. Das fühlt sich irgendwie dreckig an. Was mach allerdings machen
könnte, ist den Feed Service über einen Provider zu bauen und dann den
aktuellen ContentType an der FeedService Instanz aus diesem Provider heraus
zu setzen. Dabei kann dann auch ein listener für Config changes angemeldet
werden. Außerdem möchte ich den Feed Service eh umbauen und den Feed Proxy
so gut wie raus kriegen. Das würde da gut rein passen und man könnte dann
beim anderen der Einstellungen ganz automatisch ein reload des Feeds über
den beschriebenen Mechanismus triggern.

**Comment by mopsalarm** [comment]
Hm ne wobei das ist auch nicht richtig schön. Ich möchte den ContentType
schon als Parameter mitgeben, aber vllt muss man den Feed Filter
überarbeitet. Ich werde mir da noch Gedanken machen.

**Comment by mopsalarm** [comment]
Habe dein edit oben nicht gesehen, sorry :/. Habe das eben fertig gemacht.

**Comment by mopsalarm** [comment]
Wir sind aber relativ ähnlich ran gegangen, wie es scheint.

**Comment by mopsalarm** [comment]
Ich plane heute Abend den FeedProxy zu eleminieren bzw. umzubauen. Habe gestern bereits die ContentTypes aus dem FeedFilter entfernt.
