### ISSUE TITLE
Accounts Typ Punkt im Navigation drawer

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#75]
Der aktuelle Account Typ sollte im navdrawer angezeigt werden, wenn man eingeloggt ist.

**Comment by schr3j** [comment]
Ich fände einen ausgeschriebenen uppercase text unter dem Usernamen in der richtigen Farbe cool :D

**Comment by mopsalarm** [comment]
Kannst du ja mal ausprobieren. Bin allerdings noch nicht so ganz überzeugt
;)
