### ISSUE TITLE
Repost check problem

### ISSUE THREAD

**Issue by xxFxDx** [mopsalarm/Pr0#78]
Ein bild wird nicht als repost erkannt, wenn der Tag groß geschrieben  wurde ("Repost" statt "repost")

**Comment by xxFxDx** [comment]
Hat sich erledigt, es hat nur ein paar minuten gedauert, bis es auch im Feed angezeigt wurde.

**Comment by mopsalarm** [comment]
Ja, die Datenbank wird alle paar Minuten aktualisiert. Habe nen guten Kompromiss zischen Last bei cha0s und update Zeit gesucht.

**Comment by mopsalarm** [comment]
Vergleiche auch  https://github.com/mopsalarm/pr0gramm-meta/blob/master/update/main.py#L276 dazu. Alle 10 minuten werden die aktuellen Tasks der letzten sechs Stunden geladen.
