### ISSUE TITLE
Bilder als Repost markieren 

### ISSUE THREAD

**Issue by skuzzle** [mopsalarm/Pr0#79]
Im Moment ist es schwierig andere posts aus der app heraus zu verlinken. Eine einfache Lösung wäre die Möglichkeit den pr0gramm link zu einem post kopieren zu können. Man könnte das ganze aber noch beliebig ausbauen, z. B. ein repost Knopf der einen Dialog öffnet in dem man nach dem Original suchen kann

**Comment by mopsalarm** [comment]
Die Lösung mit dem kopieren gefällt mir definitiv besser. Aus zwei Gründen: 1. einfacher, 2. man kann die kopierten Links auch noch weiter verwenden

**Comment by mopsalarm** [comment]
Man kann beim Teilen des Postlinks einfach "in die zwischenablage" auswählen, und den Link dann verwenden. Reicht mir ;)

**Comment by skuzzle** [comment]
Bei mir gibt es diese Option beim Teilen nicht. Nutze Cyanogen Mod 11, basierend auf Android 4.4.4

**Comment by mopsalarm** [comment]
Noch nicht die Beta installiert? Einfach bei nem Bild oben auf das Teilen-Symbol drücken.

**Comment by skuzzle** [comment]
Bin noch auf dem GitHub Beta Channel unterwegs und hab die neueste Version die es da gibt. Wenn ich den Teilen Button drücke kann ich zwischen Bild und Post auswählen, dann öffnet sich wie erwartet der "Aktion durchführen mit" Dialog. Dort wird aber keine Option zum Kopieren in die Zwischenablage angezeigt.

**Comment by mopsalarm** [comment]
Achso, habe dein Problem zuerst falsch verstanden. Dann muss das eine andere App auf meinem System anbieten.
Als workaround kann ich dir erstmal eine App wie z.B. https://play.google.com/store/apps/details?id=com.silentlexx.sharetoclipboard&hl=en (erstes Ergebnis bei Google, nicht getestet) an Herz legen. Muss mal gucken ob ich das sonst doch noch selbst einbauen muss.

**Comment by mopsalarm** [comment]
https://play.google.com/store/apps/details?id=com.tengu.sharetoclipboard sieht noch bessera us.
