### ISSUE TITLE
Beim Voten eines Posts soll das Rating angepasst werden.

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#8]
Wenn ich einen Post hoch oder runter Vote, soll das Rating angepasst werden.
Das ganze passiert clientseitig und nur in der aktuellen Anzeige, ohne jegliche Datenspeicherung oder Netzwerkkommunikation.

**Comment by kratostav** [comment]
wo wird das rating gesetzt?
welche methode wir aufgerufen beim up/down voten?

**Comment by mopsalarm** [comment]
InfoLineView irgendwo.

**Comment by kratostav** [comment]
Fertig

**Comment by mopsalarm** [comment]
1. Die InfoLineView an die vote view zu übergeben ist nicht gut. Stell dir vor wir voten Kommentare, da gibt es sowas nicht. Außerdem führt das einen üblen Zyklus ein. Da muss ne andere Lösung her. 

2. Code conventions. Methoden Namen in klein mit CamelCase bitte :)

**Comment by mopsalarm** [comment]
Vielleicht kannst du das repository forken und mir nächstes mal einen Pull-Request senden, oder in einem Branch arbeiten, dann kann ich das mergen, wenn ich zufrieden bin ;)

**Comment by mopsalarm** [comment]
Vorschlag: Meine Idee wäre es, dass die LineInfoView nicht mehr die VoteView über getVoteView heraus gibt, sondern selbst einen eigenen OnVoteListener an der VoteView anmeldet. Weiterhin kann man dann einen OnVoteListener an de LineInfoView anmelden (mit setOnVoteListener). 
Der an der VoteView angemeldete OnVoteListener kann dann in seiner onVote Methode prüfen, ob ein OnVoteListener an der LineInfoView angemeldet ist, und wenn ja, diesen aufrufen. Abhängig von dem Ergebnis des Votes kann dann intern das Voting verändert werden.

**Comment by mopsalarm** [comment]
Ist nun mit erledigt.
