### ISSUE TITLE
Reposts aus dem Feed herausfiltern

### ISSUE THREAD

**Issue by knusprigeswuerstchen** [mopsalarm/Pr0#80]
Wie bereits beschrieben, könnte man eine Funktion einbauen, die Reposts aus dem Feed filtert und somit nicht anzeigt, in dem man alle Posts die über /api/items/get?tags=repost gefunden werden, entfernt.

**Comment by X39** [comment]
würde jedoch pr0gramm mehr belasten weswegen es unratsam ist (zudem erhöht es den traffic für ein doch eher marginales feature)

**Comment by mopsalarm** [comment]
@X39 Die Info, welcher post ein repost ist, habe ich für die repost Hinweise im Feed allerdings schon. Allerdings auf eine andere Artundweise als @knusprigeswuerstchen es vorgeschlagen hat.

**Comment by knusprigeswuerstchen** [comment]
@X39 die API würde, wenn der Filter aktiv ist, nur Request pro 120 Reposts bearbeiten müssen. Das ist nicht viel.

**Comment by schr3j** [comment]
@knusprigeswuerstchen Wie @mopsalarm schon geschrieben hat, hat er bereits einen Weg heraus zu finden welche Posts reposts sind. Darüber werden die Posts auch als Repost markiert. Diese dann komplett raus zu filtern wäre (vermutlich) kein all zu großer Aufwand...

**Comment by mopsalarm** [comment]
Stimmt leider so auch nicht ganz. Ich verlasse mich bei der Markierung der Reposts zwar auf einen externen Service, sehe den jedoch als optional an. Wenn der nicht da ist oder langsam antwortet, funktioniert die App ganz normal weiter. Wenn ich jetzt reposts verstecken möchte, müsste ich mit dem Anzeigen des feeds warten, bis die Repost Informationen empfangen wurden, was ich nicht schön finde. :/ es schön zu lösen ist glaube ich nicht so richtig einfach. Die Geschichte mit der extra "repost" Anfrage ist tatsächlich noch die für die App und den User beste, da das pr0gramm kein "zusätzlicher" Service ist.
