### ISSUE TITLE
Benis vor einer Woche

### ISSUE THREAD

**Issue by skuzzle** [mopsalarm/Pr0#81]
Der Benisgraph geht ja afaik über die letzten 7 Tage. Es wäre cool wenn man (irgendwie kleiner) den Wert des Benis von vor 7 Tagen mit darstellen könnte, da man die Steigungen des Graphen sonst eigentlich gar nicht interpretieren kann

**Comment by mopsalarm** [comment]
Eledigt.

**Comment by skuzzle** [comment]
Top. Gefällt mir gut.
