### ISSUE TITLE
Reposts bzw. Gelesen-Status dezenter und im Post selber darstellen

### ISSUE THREAD

**Issue by skuzzle** [mopsalarm/Pr0#82]
Zwei Anmerkungen:
1. Ich fände es gut, wenn in der Postansicht selber nochmal angezeigt würde, dass das Bild schon gesehen wurde. Vielleicht nicht unbedingt als Overlay, aber irgendwo in einer Ecke oder als eine Art Badge.
2. Durch die dunklen Overlays und den relativ dicken "repost" Schriftzug kann man die Bilder in der Übersicht nicht mehr so gut erkennen finde ich. Das macht es schwierig manche Posts durch überfliegen der Übersicht zu finden. Evtl. könnte man hier auch was mit einer Badge Darstellung am Rand des Bildes lösen

**Comment by mopsalarm** [comment]
1. Mockup
2. Naja reposts braucht man ja auch nicht sehen ;) kannst du auch hier mal nen Mockup machen?

**Comment by skuzzle** [comment]
zu 1.):
Entweder so im Badge style (schwarzer Kreis) oder da unten rechts zu den Meta Infos. Wobei weiter oben vermutlich besser ist, da man es dann sofort erkennt wenn man den post öffnet.

![in_post](https://cloud.githubusercontent.com/assets/317179/8182944/8e8dee16-1434-11e5-898a-22bf6bd51d13.png)

zu 2.) 
Nur weil etwas als repost getagged ist, heisst es ja nicht dass man das Bild noch nicht kennt. Kann ja trotzdem für einen selber interessant sein. Ich hab es hier mit verschiedenen Badges in verschiedenen Ecken des Bildes gelöst. So kann man mehrere Infos gleichzeitig darstellen. Das einzelne "R" für Repost ist nicht gerade intuitiv, daher könnte man das auch mit dem vollständigen Schriftzug lösen.

![overview](https://cloud.githubusercontent.com/assets/317179/8183077/b1f34e04-1435-11e5-86d8-db83d41f1c61.png)

Insgesamt könnte man den Style ja einstellbar machen. Hat vielleicht jeder andere Vorlieben

**Comment by mopsalarm** [comment]
Das Ding ist: ich persönlich mag es sich gerne, alles selbst zu
konfigurieren, aber beim entwickeln ist es die Hölle. Eigentlich musst du
ja da kreuzprodukt aller Einstellungen testen. Habe schon öfter Abstürze
gehabt, dass irgendwas in irgendeiner Kombination nicht ging, aber allen
anderen schon. Das ist ätzend!;)

**Comment by skuzzle** [comment]
Das stimmt natürlich. Man sollte wohl noch ein paar andere Meinungen einholen um rauszufinden was die Nutzer sich wünschen. Vielleicht kann man dafür ja auch relativ einfach einen Prototypen bauen und über den Beta Channel mit der Bitte um Rückmeldung ausrollen

**Comment by mopsalarm** [comment]
Da kommt nur leider immer relativ wenig Rückmeldung. So ungefähr bin 1 bis
2 Prozent der betauser.

Vllt wäre tacking gut, damit man das selbst mal einfach auswerten kann.

**Comment by mopsalarm** [comment]
Das schräge repost label finde ich ganz gut. Mal gucken. Heute komme ich aber wohl zu nichts und ich muss vorher noch die Animationen fertig machen.

**Comment by schr3j** [comment]
Wenn wir die Store Version posten können wir ja den Link zur Betacommunity dazu posten. Dann bekommen wir evtl. auch mehr Betauser und dann (vielleicht) auch mehr Rückmeldungen.
Falls jetzt schon jemand die PlayStore Beta möchte: https://plus.google.com/communities/110437493632062622082

**Comment by mopsalarm** [comment]
Auf die Beta-Community wird man bereits verwiesen, wenn man in der App in den Einstellungen unter Update auf "Beta" klickt.

**Comment by mopsalarm** [comment]
Habe die repost badge ins Bild eingefühgt. Ich belasse es dabei erstmal.
