### ISSUE TITLE
Share as Image

### ISSUE THREAD

**Issue by schr3j** [mopsalarm/Pr0#83]
Featurerequest aus einer Bewertung aus dem Store.

Aktuell werden die Bilder wohl als Link geteilt?

**Comment by mopsalarm** [comment]
Jepp werden sie. Ja, das sollte noch implementiert werden, hab ich bisher aber immer aufgeschoben. Habe das aber noch nie gemacht, dafür muss aber das Bild glaube ich erstmal lokal gespeichert werden, oder? Oder reicht es, nen ContentProvider mit openFile zu implementieren, und openFile lädt es dann direkt über den lokalen proxy/vom pr0gramm?

**Comment by Jaglag** [comment]
ich hab keine ahnung inwieweit man sich sachen von anderen Programmieren abschauen kann aber pr0gramm super hat das bereits implementiert:
https://play.google.com/store/apps/details?id=org.felikz.proviewer.s

**Comment by mopsalarm** [comment]
Leider kann man da nicht viel angucken.

**Comment by schr3j** [comment]
Pr0gramm super ist aber garnicht mal so geil. Da guckt man besser nicht ab. So schwierig kann das ja nicht sein, ich denke aber dass das Bild zumindest kurz lokal gespeichert werden muss...

**Comment by mopsalarm** [comment]
Tatsächlich glaube ich wirklich nicht, dass das nötig ist. Aber was anders: vllt ist ein speicherleck in der neuen beta: kann mal jemand einfach immer zur Seite wischen und zahlen ob die App mach ner bestimmten Zahl irgendwann einfach abstürzt?

**Comment by schr3j** [comment]
```Java
// Can be triggered by a view event such as a button press
public void onShareItem(View v) {
    // Get access to bitmap image from view
    ImageView ivImage = (ImageView) findViewById(R.id.ivResult);
    // Get access to the URI for the bitmap
    Uri bmpUri = getLocalBitmapUri(ivImage);
    if (bmpUri != null) {
        // Construct a ShareIntent with link to image
        Intent shareIntent = new Intent();
        shareIntent.setAction(Intent.ACTION_SEND);
        shareIntent.putExtra(Intent.EXTRA_STREAM, bmpUri);
        shareIntent.setType("image/*");
        // Launch sharing dialog for image
        startActivity(Intent.createChooser(shareIntent, "Share Image"));    
    } else {
        // ...sharing failed, handle error
    }
}
```

**Comment by mopsalarm** [comment]
getLocalBitmapUri?

**Comment by schr3j** [comment]
oh.
```Java
// Returns the URI path to the Bitmap displayed in specified ImageView
public Uri getLocalBitmapUri(ImageView imageView) {
    // Extract Bitmap from ImageView drawable
    Drawable drawable = imageView.getDrawable();
    Bitmap bmp = null;
    if (drawable instanceof BitmapDrawable){
       bmp = ((BitmapDrawable) imageView.getDrawable()).getBitmap();
    } else {
       return null;
    }
    // Store image to default external storage directory
    Uri bmpUri = null;
    try {
        File file =  new File(Environment.getExternalStoragePublicDirectory(  
            Environment.DIRECTORY_DOWNLOADS), "share_image_" + System.currentTimeMillis() + ".png");
        file.getParentFile().mkdirs();
        FileOutputStream out = new FileOutputStream(file);
        bmp.compress(Bitmap.CompressFormat.PNG, 90, out);
        out.close();
        bmpUri = Uri.fromFile(file);
    } catch (IOException e) {
        e.printStackTrace();
    }
    return bmpUri;
}
```

**Comment by schr3j** [comment]
Da wird das ganze aber auch erstmal lokal gespeichert...

**Comment by mopsalarm** [comment]
Jepp, und IO im Main Thread. OutputSteam nicht unbedingt geschlossen... So schreibt man schlechte Software.

**Comment by mopsalarm** [comment]
Habs jetzt ohne extra zwischenspeichern implementiert. Ich lade gleich eine apk hoch zum Testen bevor es dann später in die Beta geht.

**Comment by mopsalarm** [comment]
https://www.dropbox.com/s/eutef3g7t7xhnnx/pr0gramm-share.apk?dl=0 Bitte mal testen, ob ihr was teilen könnt.

**Comment by Jaglag** [comment]
Jap läuft 1a!

kann man das gleiche auch mit webm/gifs machen aka share as movie damit alle formate abgedeckt sind?
Und wie läuft das mit der Beta?
Ich hab das häckchen gesetzt im client is das dann ein seperates app oder wird die bestehende auf die beta aktualisiert?
Bin etwas verwirrt da es im playstore eine ähnlich aussehnde app gibt mit Beta Tag.

**Comment by schr3j** [comment]
Die Playstore Beta bekommst du indem du der Betapr0gramm Community auf G+ beitrittst:
https://plus.google.com/communities/110437493632062622082
und dann bei diesem Link:
https://play.google.com/apps/testing/io.github.mopsalarm.pr0gramm.gp
"Tester werden" oder sowas (blauer Button) anklickst ;)

**Comment by mopsalarm** [comment]
Für Videos und Gifs mache ich das erstmal nicht. Videos könnte funktionieren, aber gifs werden, befürchte ich, ich von anderen Programmen oft nicht unterstüzt oder nicht animiert abgespielt. Aber in dem Fall kannst du ja einfach den Link zum Post oder zum Bild/Video direkt verschicken.
Wenn du auf "Beta" in der App drückst, und du sie aus dem PlayStore installiert hast, solltest du auch auf die von schr3j verlinkte Community weitergeleitet werden. Wenn du beigetreten bist, bekommst du automatisch die "pr0gramm navigator" beta, statt der normalen version. "Pr0gramm (Beta)" ist eine andere App

**Comment by mopsalarm** [comment]
Neue Beta ist online!
