### ISSUE TITLE
Zoom auch ohne vollbild

### ISSUE THREAD

**Issue by Jaglag** [mopsalarm/Pr0#84]
Hi wär es möglich an ein Bild zu zoomen ohne extra ein Vollbild zu öffnen. 
Wär super da es nervig ist jedesmal bei kleinem Text ins Vollbild zu gehen um alles lesen zu können. Danke

**Comment by mopsalarm** [comment]
Wäre möglich, aber ich finde das nicht gut. Stell dir vor das Bild ist klein und nimmt nur 30% deines Bildschirms ein. Dann zoomst du ran, dann siehst du das zwar vergrößert, aber weiterhin nur auf 30% deines Bildschirms. Das ist doof. So schlimm finde ich die Vollbild Activity dafür nicht. Außerdem kannst du in den Einstellugen auch den echten "Vollbild" deaktvieren.

**Comment by Jaglag** [comment]
Hmm könnte man dann unter verhalten die Option 1tap fullscrren adden da auf meinem Handy die obere taste nur schwer zu erreichen ist

**Comment by mopsalarm** [comment]
Hm bin ich mäßig begeistert. Aber darüber kann man reden.

**Comment by Jaglag** [comment]
wär ja somit optional und bei großen screens den Daumen oben rechts in die ecke drücken is schon en stück ;)
wär klasse wenn ihr das implementieren würdet!
