### ISSUE TITLE
Image preload

### ISSUE THREAD

**Issue by Jaglag** [mopsalarm/Pr0#85]
Hi noch eine Funktion die Klasse wäre. 
Ein preload der letzte x Bilder variabel einstellbar und zb nur bei wlan aktiv mit variablen Speicher Ort um nicht den Haupt Speicher zu zu Müllen
Danke

**Comment by mopsalarm** [comment]
Ja, habe ich auf dem Schirm. Hoffentlich in den nächsten ein, zwei Wochen

**Comment by Hoerli1337** [comment]
Die Funktion wäre super :)

**Comment by X39** [comment]
hierzu:
http://stackoverflow.com/questions/3425906/creating-temporary-files-in-android

**Comment by mopsalarm** [comment]
@X39 Danke, aber das bringt mir nicht wirklich was. Wenn, würde ich die Datei unter ihrer ID oder ihrer URL abspeichern, dann kann ich sie wiederfinden, ohne eine zusätzliche Datenbank zu pflegen.

Das ist ein auf jedenfall Feature, was ich noch nicht vergessen habe.
Habe die letzten Tage ein wenig Tracking in die App eingebaut und bin erstaunt/enttäuscht, wie die App verwendet wird. Zwischen 1-2% der User schreiben Nachrichten. Dann hätte ich mir den Aufwand auch sparen können :/... Außerdem öffnen scheinbar nur etwa 50% der User am Tag die Drawer-Leiste. Ich weiß nicht, ob die anderen überhaupt wissen, dass es einen Drawer gibt? Habe jetzt mal a/b Testing eingebaut. We'll see...

**Comment by schr3j** [comment]
@mopsalarm Ich weiß ja nicht wie stark die PMs auf pr0gramm im Allgemeinen genutzt werden aber ich denke mal das hält sich in Grenzen. Und zum Thema Drawer: Ich öffne den auch nicht jeden Tag, wenn man Abends nur mal eben top durch scrollt braucht man ihn ja überhaupt nicht ;)

**Comment by mopsalarm** [comment]
http://surveynuts.com/surveys/admin?id=35405&stoken=3766867803217&section=results

Weiß nicht ob ihr das richtig sehen könnt.

**Comment by aPollO2k** [comment]
Ich bin sehr dankbar für die Nachrichten funktion. Ich nutze die App auch nur da sie nahezu alle Funktionen der Website abbildet.
