### ISSUE TITLE
Download Ordner auch auf sd Karte ermöglichen

### ISSUE THREAD

**Issue by Jaglag** [mopsalarm/Pr0#87]
Hi
Sehe hier nur 3 Optionen wie dieser Ordner benannt wird aber keinen Pfad zu einer  sd.
Bitte adden da der Haupt speicher nich durch die Bilder belastet werden soll.

Btw nun wieder 5 Sterne im Play store für den klassen Support hier Danke Jungs!

**Comment by schr3j** [comment]
Wäre vllt. ganz gut freie Ordnerwahl zu ermöglichen..
Hab z.B. diese Lib gefunden die ganz gut aussieht https://android-arsenal.com/details/1/160

**Comment by mopsalarm** [comment]
Könnte man machen. Falls sich der Sache jemand annimmt: bitte möglichst irgendwie abwärtskompatibel machen, oder die alte Einstellung beim ersten Start übernehmen oder so. Wenn es nicht zu viel extra Aufwand ist.

**Comment by Jaglag** [comment]
könnte man gleich verbinden mit dem pre load ordner.
Das der im gleichen kontext mit angegeben werden kann oder halt auf default belassen wie jeder wünscht.

**Comment by mopsalarm** [comment]
Pre loading gibt es nur in der App noch gar nicht

**Comment by mopsalarm** [comment]
Pre loading gibt es nur in der App noch gar nicht
