### ISSUE TITLE
Neu/Top wiederherstellen

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#88]
Habe schon von ganz vielen gehört, dass sie gerne beim öffnen der App wieder bei neu/top sein wollen, wo die aufgehört haben.

**Comment by X39** [comment]
die frage die sich hier stellt ist was ist gemeint mit öffnen?

bei einem neuem öffnen sollte man nicht erwarten das man an der selben stelle weiter "surft", wohingegen beim verbleiben im speicher selbiges geschehen sollte

**Comment by mopsalarm** [comment]
Das stimmt. Momentan kann man die App auch ausschließlich über top verlassen. Wenn man bei Neu auf zurück drückt, öffnet sich gezwungenermaßen Top. Man könnte jedoch top/neu als erste und letzte Seite konfigurierbar machen.

**Comment by schr3j** [comment]
Wenn man eine App in Android verlässt um später an der gleichen Stelle weiter zu machen spammt man ja nicht zurück, sondern drückt auf den Home-Kreis. Und da funktioniert das ganze auch so wie erwartet.

Geht es bei dem issue hier darum bei der gleichen Position im Feed zu sein, oder wollen sie nur in der gleichen Kategorie weitermachen?

**Comment by mopsalarm** [comment]
Kategorie

**Comment by mopsalarm** [comment]
So, die Einstellung ist implementiert.
