### ISSUE TITLE
[Feature Request] Lockscreen/Background image Changer

### ISSUE THREAD

**Issue by Jaglag** [mopsalarm/Pr0#89]
Hi
es wär toll wenn ihr sowas wie:
alle x stunden ein random/newest/popular image (kategorie,tags, suchbegriff oder sonstigem je nach angabe) aus Pr0gramm als Hintergrundbild/lockscreen image zu setzen um immer mal frischen wind aufm Bildschirm zu haben.

**Comment by mopsalarm** [comment]
Toll. Drecks gedrosselte Verbindung. Also direkt finde ich hat es nichts in der App zu suchen, allerdings konnte man über ein Muzei Plugin in der App nachdenken.

**Comment by Jaglag** [comment]
deshalb mein gedanke das als untermenü in den optionen zu implementieren a la lockscreen

**Comment by mopsalarm** [comment]
Mit "direkt hat es nichts in der App zu suchen" meine ich jetzt nicht irgendwie das Optische, sondern die Funktionalität Hintergrundbilder zu setzten oder den Lockscreen zu manipulieren, gehört nicht in die pr0gramm App. Aber wie gesagt, ein Muzei Plugin kann man machen. Wenn ich noch Zeit finde, hacke ich eines zusammen, das sfw:oc oder sfw:earthporn anzeigt. Mal sehen.

**Comment by Jaglag** [comment]
jo supi filter variabel einstellbar bitte das wär klasse!
hat keine eile !

**Comment by mopsalarm** [comment]
Ich schiebe gleich noch eine korrigierte Beta raus, kannst es dann ja mal testen. Bei mir klappts.

**Comment by Jaglag** [comment]
Heh nice danke aber wie/wo aktivier ich das? :D

**Comment by mopsalarm** [comment]
https://play.google.com/store/apps/details?id=net.nurik.roman.muzei

Muzei installieren, als Desktop Hintergrund einstellen und dann in Muzei pr0gramm als Quelle einstellen. Demnächst kann ich noch ne Einstellungsseite dazu bauen. 

Muzei kümmert sich um die ganze Darstellung mit dem Hintergrund etc, die App liefert nur Daten

**Comment by Jaglag** [comment]
achsoo hmm
ich dachte das wird wie bei:
https://play.google.com/store/apps/details?id=com.autowallpaper.free
gelöst das ich nun im handy unter Live Hintergründe einfach Pr0gramm setzen kann.

**Comment by mopsalarm** [comment]
Nein, weil ich mich dann um die Anzeige etc in pr0gramm kümmern muss. So übernimm Muzei das komplett. Du stellst halt Muzei als Livehintergrund ein, und wählst in Muzei pr0gramm aus. Ergebnis ist das selbe, nur Muzei ist getestet, funktioniert und hat noch ein paar mehr Features (Blur, double tap, etc).

**Comment by Jaglag** [comment]
Jo verständlich!
Super teil dieses Muzei kannte ich vorher noch nicht.
Freu mich schon auf die optionen refreshed etwas oft die Bilder atm.
