### ISSUE TITLE
Multi Window Support

### ISSUE THREAD

**Issue by Hoerli1337** [mopsalarm/Pr0#91]
Support für Multi-Window bei Samsung-Geräten und für die Zukunft so wie es ausschaut für Googels Geräte.

**Comment by mopsalarm** [comment]
Für Samsung Geräte nicht, habe so eines nicht. Für Google Geräte kann ich was machen, sobald Android M da ist und man überhaupt was machen muss.

**Comment by Hoerli1337** [comment]
Kann gerne Beta-Tester sein. Bin im Besitz von mehrern Samsung-Geräten mit Multi Window ;)

**Comment by mopsalarm** [comment]
@Hoerli1337 Läuft auf deinem Samsung die Videowiedergabe in der App vernünftig ohne Softwaredekoder?

**Comment by X39** [comment]
moment mal ...
dafür muss man was extra implementieren?!?
was ist das denn für ne dumme lösung!? ...

**Comment by mopsalarm** [comment]
Ja, denke ich auch. Aber vllt ist es mit Android M ja dann besser.

**Comment by X39** [comment]
hoffen wir es
alleine schon aus boykott würde ich es nicht implementieren sonst

**Comment by Hoerli1337** [comment]
@X39 jup ohne Probleme.
Mein Galaxy Note 3 macht alles mit :D

Und ja für Multi Window muss man was einfügen. Alleine geht das nicht. Schätze auch mit Googles Funktion muss man was einbauen.
Wenn ich Zeit dazu finde such ich mal nach nem Code.

**Comment by mopsalarm** [comment]
Okay, man muss scheinbar keinen Code schreiben, sondern nur in der Manifest XML angeben, dass die App Multi window kompatibel ist. Das wiederum finde ich relativ sinnvoll:

http://stackoverflow.com/questions/14111052/adding-multi-window-support-to-android-application

**Comment by mopsalarm** [comment]
Habe es mal ausprobiert, kann es aus Mangel an Samsunggeräten nicht ausprobieren: http://pr0.wibbly-wobbly.de/alpha/multiwindow.apk

**Comment by mopsalarm** [comment]
Rückmeldung, kinder? @Hoerli1337

**Comment by mopsalarm** [comment]
Wenns scheinbar nicht von Interesse ist, dann halt nicht..
