### ISSUE TITLE
Invites

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#93]
Es wäre schön, wenn man Invites mit anderen Menschen über WhatsApp oder so teilen kann. Dabei kann man gleich auch für die App weben!

**Comment by mopsalarm** [comment]
Was haltet ihr da von?

**Comment by schr3j** [comment]
gute idee. Wenn das so umsetzbar ist ;)

**Comment by mopsalarm** [comment]
Oh, habe nicht gesehen, dass das nur über E-Mail geht. Nagut, dann nicht!
