### ISSUE TITLE
Zurück 

### ISSUE THREAD

**Issue by marsteff** [mopsalarm/Pr0#94]
Moien, 

mir ist eben folgendes Szenario passiert:

Hatte NSFW Filter an, und habe mir ein paar Bilder angesehen. Habe dann den Filter ausgemacht (Nur noch sfw) und habe dann die Zurück Taste am Handy gedrückt. Dadurch ist er auf die vorherigen NSFW Bilder gesprungen, was unter Umständen peinlich sein kann, wenn man irgendwem was zeigen will.
Ist das so beabsichtigt? 

In Android ist das ja glaube Standardmäßig so vorgegeben.

**Comment by mopsalarm** [comment]
Du hast schon recht, das ist natürlich nicht wirklich schön. Andererseits: Was ist das gewünschte verhalten? Man möchte ja auch nicht die komplette Historie zurück setzen.

**Comment by schr3j** [comment]
Ich denke der Filter sollte komplett von der History entkoppelt werden und jederzeit nur der aktuell eingestellte Filter verwendet werden.

**Comment by mopsalarm** [comment]
Ja aber was wäre das erwarte verhalten? Feed, nsfw Post, über Tags neuer Feed, Einstellung umstellen, zurück, was passiert mit dem nsfw Post in der history?

**Comment by schr3j** [comment]
Das gleiche wie auf der Website. Es wird angezeigt dass die aktuellen Filtereinstellungen das nicht zulassen. Man könnte ja dann drunter noch einen "nsfw aktivieren" button einfügen, dann kann man es doch anschauen.

**Comment by mopsalarm** [comment]
Hmm, ja
