### ISSUE TITLE
Benutzerprofil kommentare sind sfw gefiltert

### ISSUE THREAD

**Issue by X39** [mopsalarm/Pr0#95]
Nsfw kommentare werden nicht angezeigt in der app

**Comment by mopsalarm** [comment]
Auf der aktuellen Version immer noch nicht?

**Comment by X39** [comment]
Version 1.66

**Comment by mopsalarm** [comment]
Achso Benutzer profile. Gucke morgen mal, heute habe ich keine Lust mehr

**Comment by mopsalarm** [comment]
Ups, doch noch was gemacht.

**Comment by X39** [comment]
du kannst die übrigens mit dem kommentar "fixed #XX" in der commit nachricht automatisch schließen
