### ISSUE TITLE
Falsches Grau

### ISSUE THREAD

**Issue by schr3j** [mopsalarm/Pr0#97]
In der FeedView wird entweder für leere Posts oder für den Hintergrund (oder beides) ein falsches Grau verwendet...
![screenshot_20150706-015650](https://cloud.githubusercontent.com/assets/1710904/8514019/be7565ac-2382-11e5-838e-29cfbe53548e.png)

**Comment by mopsalarm** [comment]
Ich habe gerade 15 Feedback Mails bekommen von Leuten die glauben, die App ginge nicht mehr wegen den schwarzen Bildern. Bei mir Stimmen die Farben übrigens, glaube ich. Prüfe day morgen am PC genauer.

**Comment by schr3j** [comment]
:joy: Ich hab gestern auch locker 2 min mein Internet gecheckt und mich gefragt warum die Bilder nicht laden

Ob die Farben stimmen oder nicht ist anscheinend schwer zu sagen, das scheint ein sehr minimaler Unterschied zu sein. Auf dem Nexus 5 ist der Kontrast sehr deutlich, auf dem Screenshot wenn ich ihn hier auf meinem Macbook (doch ein relativ gutes Display) anschaue passen die Farben auch nicht.

**Comment by mopsalarm** [comment]
Naja kann man ja mal gucken welche farbwerte das sind. Aber ich kann mir
vorstellen dass die jpeg thumbnails einfach falscher Farben haben

**Comment by mopsalarm** [comment]
So, auf dem Screenshot haben die Thumbnails den Farbcode 151517, also "falsches Grau".
