### ISSUE TITLE
Steckenbleiben bei Rückwärtsnavigation

### ISSUE THREAD

**Issue by schr3j** [mopsalarm/Pr0#98]
Wenn ich eine Benachrichtigung bekomme und die anklicke hänge ich danach bei den Nachrichten fest. Entweder sollte wenn der Verlauf leer ist automatisch zurück zum feed gegangen werden oder der Navdrawer auch in den Nachrichten funktionieren.

**Comment by mopsalarm** [comment]
Ja hast du recht. Den navdrawer wird es da wohl nicht geben, aber zurück zur Hauptactivity sollte es gehen.

**Comment by mopsalarm** [comment]
Ist das eigentlich gefixt? Hatte da mal was ausprobiert.
