### ISSUE TITLE
Softwaredekoder für webms

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#99]
Moin,

ich brauch mal eben eure Hilfe zum Testen. Könnt ihr bitte diese Version einmal installieren? http://pr0.wibbly-wobbly.de/alpha/webm.apk

Vielleicht habt ihr schon mitbekommen, dass ich die letzten Tage dran gearbeitet habe, libvpx in die App zu integrieren, um die webms mit libvpx in Software dekodieren zu können (und nicht nur die low-quality mpegs). 

Habe es heute soweit lauffähig bekommen, dass die Videos in Grau angezeigt werden. CPU Last liegt auf meinem alten Xperia Z1 bei HD ungefär gleichauf mit den 320x180px großen MPEGs.

Läufts bei euch, und wenn ja, akzeptabel?

Gruß, Mops!

**Comment by mopsalarm** [comment]
@MetalMatze @schr3j @Graphicscore @kratostav

**Comment by MetalMatze** [comment]
Läuft auf meinem Nexus 5 problemlos. Webm scheint alles zu laufen. Dieser parallex effect, nice! 
Manche Bilder wurden erst mit einem Abstand nach oben angezeigt, bevor die große Version geladen und das Bild oben positioniert war.

**Comment by mopsalarm** [comment]
Das sind die quadratischen Vorschau Bilder aus dem Feed. Die werden zuerst gezeigt solange nichts anderes da ist
